#pragma once

#include <cyten/backends/tensor_backend.h>

#include <pybind11/functional.h>
#include <pybind11/pybind11.h>

#include <memory>
#include <optional>
#include <string>
#include <tuple>
#include <utility>
#include <vector>

namespace cyten {

// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py
// gen_pyb11_trampoline --py-name TensorBackend --header-file
// include/cyten/backends/tensor_backend.h --binding-file pybind/backends/py_trampolines.hpp
// Updated for typed TensorCPtr / SymmetricTensorCPtr / DiagonalTensorCPtr / MaskCPtr args.

/// @brief pybind11 trampoline class for TensorBackend in Python
class PyTensorBackend
  : public TensorBackend
  , public py::trampoline_self_life_support
{
  public:
    using TensorBackend::TensorBackend;

    std::string __repr__() const override
    {
        PYBIND11_OVERRIDE(std::string, TensorBackend, __repr__);
    }
    std::string __str__() const override
    {
        PYBIND11_OVERRIDE(std::string, TensorBackend, __str__);
    }
    void test_tensor_sanity(TensorCPtr a, bool is_diagonal) override
    {
        PYBIND11_OVERRIDE(void, TensorBackend, test_tensor_sanity, a, is_diagonal);
    }
    void test_mask_sanity(MaskCPtr a) override
    {
        PYBIND11_OVERRIDE(void, TensorBackend, test_mask_sanity, a);
    }
    bool is_correct_data_type(TensorBackend::DataCPtr data) const override
    {
        PYBIND11_OVERRIDE_PURE(bool, TensorBackend, is_correct_data_type, data);
    }
    LegPipe::Ptr make_pipe(std::vector<Leg::Ptr> legs, bool is_dual, LegPipe::Ptr pipe) override
    {
        PYBIND11_OVERRIDE(LegPipe::Ptr, TensorBackend, make_pipe, legs, is_dual, pipe);
    }
    TensorBackend::DataPtr act_block_diagonal_square_matrix(
      SymmetricTensorCPtr a,
      BlockUnaryFn block_method,
      std::optional<DtypeMapFn> dtype_map) override
    {
        py::function py_method = py::cpp_function(
          [block_method](BlockBackend::BlockPtr const& b) { return block_method(b); });
        py::object py_map = py::none();
        if (dtype_map) {
            auto map = *dtype_map;
            py_map = py::cpp_function([map](Dtype d) { return map(d); });
        }
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr,
                               TensorBackend,
                               act_block_diagonal_square_matrix,
                               a,
                               py_method,
                               py_map);
    }
    TensorBackend::DataPtr add_trivial_leg(TensorCPtr a,
                                           int64 legs_pos,
                                           bool add_to_domain,
                                           int64 co_domain_pos,
                                           TensorProduct::Ptr new_codomain,
                                           TensorProduct::Ptr new_domain) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr,
                               TensorBackend,
                               add_trivial_leg,
                               a,
                               legs_pos,
                               add_to_domain,
                               co_domain_pos,
                               new_codomain,
                               new_domain);
    }
    bool almost_equal(TensorCPtr a, TensorCPtr b, float64 rtol, float64 atol) override
    {
        PYBIND11_OVERRIDE_PURE(bool, TensorBackend, almost_equal, a, b, rtol, atol);
    }
    TensorBackend::DataPtr apply_mask_to_DiagonalTensor(DiagonalTensorCPtr tensor,
                                                        MaskCPtr mask) override
    {
        PYBIND11_OVERRIDE_PURE(
          TensorBackend::DataPtr, TensorBackend, apply_mask_to_DiagonalTensor, tensor, mask);
    }
    TensorBackend::DataPtr combine_legs(TensorCPtr tensor,
                                        std::vector<std::vector<int64>> leg_idcs_combine,
                                        std::vector<LegPipe::Ptr> pipes,
                                        TensorProduct::Ptr new_codomain,
                                        TensorProduct::Ptr new_domain) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr,
                               TensorBackend,
                               combine_legs,
                               tensor,
                               leg_idcs_combine,
                               pipes,
                               new_codomain,
                               new_domain);
    }
    TensorBackend::DataPtr compose(SymmetricTensorCPtr a, SymmetricTensorCPtr b) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr, TensorBackend, compose, a, b);
    }
    TensorBackend::DataPtr copy_data(TensorCPtr a, std::optional<std::string> device) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr, TensorBackend, copy_data, a, device);
    }
    TensorBackend::DataPtr dagger(TensorCPtr a) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr, TensorBackend, dagger, a);
    }
    BlockBackend::Scalar data_item(TensorBackend::DataPtr a) override
    {
        PYBIND11_OVERRIDE_PURE(BlockBackend::Scalar, TensorBackend, data_item, a);
    }
    bool diagonal_all(DiagonalTensorCPtr a) override
    {
        PYBIND11_OVERRIDE_PURE(bool, TensorBackend, diagonal_all, a);
    }
    bool diagonal_any(DiagonalTensorCPtr a) override
    {
        PYBIND11_OVERRIDE_PURE(bool, TensorBackend, diagonal_any, a);
    }
    TensorBackend::DataPtr diagonal_elementwise_binary(DiagonalTensorCPtr a,
                                                       DiagonalTensorCPtr b,
                                                       BlockBinaryFn func,
                                                       bool partial_zero_is_zero) override
    {
        py::function py_func =
          py::cpp_function([func](BlockBackend::BlockPtr const& x,
                                  BlockBackend::BlockPtr const& y) { return func(x, y); });
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr,
                               TensorBackend,
                               diagonal_elementwise_binary,
                               a,
                               b,
                               py_func,
                               py::dict(),
                               partial_zero_is_zero);
    }
    TensorBackend::DataPtr diagonal_elementwise_unary(DiagonalTensorCPtr a,
                                                      BlockUnaryFn func,
                                                      bool maps_zero_to_zero) override
    {
        py::function py_func =
          py::cpp_function([func](BlockBackend::BlockPtr const& b) { return func(b); });
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr,
                               TensorBackend,
                               diagonal_elementwise_unary,
                               a,
                               py_func,
                               py::dict(),
                               maps_zero_to_zero);
    }
    TensorBackend::DataPtr diagonal_from_block(BlockBackend::BlockPtr a,
                                               TensorProduct::Ptr co_domain,
                                               float64 tol) override
    {
        PYBIND11_OVERRIDE_PURE(
          TensorBackend::DataPtr, TensorBackend, diagonal_from_block, a, co_domain, tol);
    }
    TensorBackend::DataPtr diagonal_from_sector_block_func(SectorBlockFactoryFn func,
                                                           TensorProduct::Ptr co_domain) override
    {
        py::function py_func =
          py::cpp_function([func](std::vector<int64> shape, Sector const& coupled) {
              return func(shape, coupled);
          });
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr,
                               TensorBackend,
                               diagonal_from_sector_block_func,
                               py_func,
                               co_domain);
    }
    TensorBackend::DataPtr diagonal_tensor_from_full_tensor(SymmetricTensorCPtr a,
                                                            std::optional<float64> tol) override
    {
        PYBIND11_OVERRIDE_PURE(
          TensorBackend::DataPtr, TensorBackend, diagonal_tensor_from_full_tensor, a, tol);
    }
    BlockBackend::Scalar diagonal_tensor_trace_full(DiagonalTensorCPtr a) override
    {
        PYBIND11_OVERRIDE_PURE(BlockBackend::Scalar, TensorBackend, diagonal_tensor_trace_full, a);
    }
    BlockBackend::BlockPtr diagonal_tensor_to_block(DiagonalTensorCPtr a) override
    {
        PYBIND11_OVERRIDE_PURE(BlockBackend::BlockPtr, TensorBackend, diagonal_tensor_to_block, a);
    }
    std::tuple<TensorBackend::DataPtr, ElementarySpace::Ptr> diagonal_to_mask(
      DiagonalTensorCPtr tens) override
    {
        PYBIND11_OVERRIDE_PURE(
          PYBIND11_TYPE(std::tuple<TensorBackend::DataPtr, ElementarySpace::Ptr>),
          TensorBackend,
          diagonal_to_mask,
          tens);
    }
    std::tuple<Space::Ptr, TensorBackend::DataPtr> diagonal_transpose(
      DiagonalTensorCPtr tens) override
    {
        PYBIND11_OVERRIDE_PURE(PYBIND11_TYPE(std::tuple<Space::Ptr, TensorBackend::DataPtr>),
                               TensorBackend,
                               diagonal_transpose,
                               tens);
    }
    std::tuple<TensorBackend::DataPtr, TensorBackend::DataPtr, ElementarySpace::Ptr>
    eigh(SymmetricTensorCPtr a, bool new_leg_dual, std::optional<std::string> sort) override
    {
        PYBIND11_OVERRIDE_PURE(
          PYBIND11_TYPE(
            std::tuple<TensorBackend::DataPtr, TensorBackend::DataPtr, ElementarySpace::Ptr>),
          TensorBackend,
          eigh,
          a,
          new_leg_dual,
          sort);
    }
    std::tuple<TensorBackend::DataPtr, TensorBackend::DataPtr, ElementarySpace::Ptr>
    eig(SymmetricTensorCPtr a, bool new_leg_dual, std::optional<std::string> sort) override
    {
        PYBIND11_OVERRIDE_PURE(
          PYBIND11_TYPE(
            std::tuple<TensorBackend::DataPtr, TensorBackend::DataPtr, ElementarySpace::Ptr>),
          TensorBackend,
          eig,
          a,
          new_leg_dual,
          sort);
    }
    std::tuple<TensorBackend::DataPtr, ElementarySpace::Ptr>
    eigvalsh(SymmetricTensorCPtr a, bool new_leg_dual, std::optional<std::string> sort) override
    {
        PYBIND11_OVERRIDE_PURE(
          PYBIND11_TYPE(std::tuple<TensorBackend::DataPtr, ElementarySpace::Ptr>),
          TensorBackend,
          eigvalsh,
          a,
          new_leg_dual,
          sort);
    }
    std::tuple<TensorBackend::DataPtr, ElementarySpace::Ptr>
    eigvals(SymmetricTensorCPtr a, bool new_leg_dual, std::optional<std::string> sort) override
    {
        PYBIND11_OVERRIDE_PURE(
          PYBIND11_TYPE(std::tuple<TensorBackend::DataPtr, ElementarySpace::Ptr>),
          TensorBackend,
          eigvals,
          a,
          new_leg_dual,
          sort);
    }
    TensorBackend::DataPtr eye_data(TensorProduct::Ptr co_domain,
                                    Dtype dtype,
                                    std::string device) override
    {
        PYBIND11_OVERRIDE_PURE(
          TensorBackend::DataPtr, TensorBackend, eye_data, co_domain, dtype, device);
    }
    TensorBackend::DataPtr from_dense_block(BlockBackend::BlockPtr a,
                                            TensorProduct::Ptr codomain,
                                            TensorProduct::Ptr domain,
                                            float64 tol) override
    {
        PYBIND11_OVERRIDE_PURE(
          TensorBackend::DataPtr, TensorBackend, from_dense_block, a, codomain, domain, tol);
    }
    TensorBackend::DataPtr from_dense_block_trivial_sector(BlockBackend::BlockPtr block,
                                                           Space::Ptr leg) override
    {
        PYBIND11_OVERRIDE_PURE(
          TensorBackend::DataPtr, TensorBackend, from_dense_block_trivial_sector, block, leg);
    }
    TensorBackend::DataPtr from_grid(std::vector<std::vector<py::object>> grid,
                                     TensorProduct::Ptr new_codomain,
                                     TensorProduct::Ptr new_domain,
                                     std::vector<std::vector<int64>> left_mult_slices,
                                     std::vector<std::vector<int64>> right_mult_slices,
                                     Dtype dtype,
                                     std::string device) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr,
                               TensorBackend,
                               from_grid,
                               grid,
                               new_codomain,
                               new_domain,
                               left_mult_slices,
                               right_mult_slices,
                               dtype,
                               device);
    }
    TensorBackend::DataPtr from_random_normal(TensorProduct::Ptr codomain,
                                              TensorProduct::Ptr domain,
                                              float64 sigma,
                                              Dtype dtype,
                                              std::string device) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr,
                               TensorBackend,
                               from_random_normal,
                               codomain,
                               domain,
                               sigma,
                               dtype,
                               device);
    }
    TensorBackend::DataPtr from_sector_block_func(SectorBlockFactoryFn func,
                                                  TensorProduct::Ptr codomain,
                                                  TensorProduct::Ptr domain) override
    {
        py::function py_func =
          py::cpp_function([func](std::vector<int64> shape, Sector const& coupled) {
              return func(shape, coupled);
          });
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr,
                               TensorBackend,
                               from_sector_block_func,
                               py_func,
                               codomain,
                               domain);
    }
    TensorBackend::DataPtr from_tree_pairs(
      std::map<std::pair<FusionTree, FusionTree>, BlockBackend::BlockPtr> trees,
      TensorProduct::Ptr codomain,
      TensorProduct::Ptr domain,
      Dtype dtype,
      std::string device) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr,
                               TensorBackend,
                               from_tree_pairs,
                               trees,
                               codomain,
                               domain,
                               dtype,
                               device);
    }
    TensorBackend::DataPtr full_data_from_diagonal_tensor(DiagonalTensorCPtr a) override
    {
        PYBIND11_OVERRIDE_PURE(
          TensorBackend::DataPtr, TensorBackend, full_data_from_diagonal_tensor, a);
    }
    TensorBackend::DataPtr full_data_from_mask(MaskCPtr a, Dtype dtype) override
    {
        PYBIND11_OVERRIDE_PURE(
          TensorBackend::DataPtr, TensorBackend, full_data_from_mask, a, dtype);
    }
    std::string get_device_from_data(TensorBackend::DataPtr a) override
    {
        PYBIND11_OVERRIDE_PURE(std::string, TensorBackend, get_device_from_data, a);
    }
    Dtype get_dtype_from_data(TensorBackend::DataPtr a) override
    {
        PYBIND11_OVERRIDE_PURE(Dtype, TensorBackend, get_dtype_from_data, a);
    }
    BlockBackend::Scalar get_element(SymmetricTensorCPtr a, std::vector<int64> idcs) override
    {
        PYBIND11_OVERRIDE_PURE(BlockBackend::Scalar, TensorBackend, get_element, a, idcs);
    }
    BlockBackend::Scalar get_element_diagonal(DiagonalTensorCPtr a, int64 idx) override
    {
        PYBIND11_OVERRIDE_PURE(BlockBackend::Scalar, TensorBackend, get_element_diagonal, a, idx);
    }
    BlockBackend::Scalar get_element_mask(MaskCPtr a, std::vector<int64> idcs) override
    {
        PYBIND11_OVERRIDE_PURE(BlockBackend::Scalar, TensorBackend, get_element_mask, a, idcs);
    }
    BlockBackend::Scalar inner(SymmetricTensorCPtr a,
                               SymmetricTensorCPtr b,
                               bool do_dagger) override
    {
        PYBIND11_OVERRIDE_PURE(BlockBackend::Scalar, TensorBackend, inner, a, b, do_dagger);
    }
    TensorBackend::DataPtr inv_part_from_dense_block_single_sector(
      BlockBackend::BlockPtr vector,
      Space::Ptr space,
      ElementarySpace::Ptr charge_leg) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr,
                               TensorBackend,
                               inv_part_from_dense_block_single_sector,
                               vector,
                               space,
                               charge_leg);
    }
    BlockBackend::BlockPtr inv_part_to_dense_block_single_sector(
      SymmetricTensorCPtr tensor) override
    {
        PYBIND11_OVERRIDE_PURE(
          BlockBackend::BlockPtr, TensorBackend, inv_part_to_dense_block_single_sector, tensor);
    }
    TensorBackend::DataPtr linear_combination(BlockBackend::Scalar a,
                                              TensorCPtr v,
                                              BlockBackend::Scalar b,
                                              TensorCPtr w) override
    {
        PYBIND11_OVERRIDE_PURE(
          TensorBackend::DataPtr, TensorBackend, linear_combination, a, v, b, w);
    }
    std::tuple<TensorBackend::DataPtr, TensorBackend::DataPtr> lq(
      SymmetricTensorCPtr tensor,
      TensorProduct::Ptr new_co_domain) override
    {
        PYBIND11_OVERRIDE_PURE(
          PYBIND11_TYPE(std::tuple<TensorBackend::DataPtr, TensorBackend::DataPtr>),
          TensorBackend,
          lq,
          tensor,
          new_co_domain);
    }
    std::tuple<TensorBackend::DataPtr, ElementarySpace::Ptr>
    mask_binary_operand(MaskCPtr mask1, MaskCPtr mask2, BlockBinaryFn func) override
    {
        py::function py_func =
          py::cpp_function([func](BlockBackend::BlockPtr const& x,
                                  BlockBackend::BlockPtr const& y) { return func(x, y); });
        PYBIND11_OVERRIDE_PURE(
          PYBIND11_TYPE(std::tuple<TensorBackend::DataPtr, ElementarySpace::Ptr>),
          TensorBackend,
          mask_binary_operand,
          mask1,
          mask2,
          py_func);
    }
    std::tuple<TensorBackend::DataPtr, TensorProduct::Ptr, TensorProduct::Ptr>
    mask_contract_large_leg(TensorCPtr tensor, MaskCPtr mask, int64 leg_idx) override
    {
        PYBIND11_OVERRIDE_PURE(
          PYBIND11_TYPE(
            std::tuple<TensorBackend::DataPtr, TensorProduct::Ptr, TensorProduct::Ptr>),
          TensorBackend,
          mask_contract_large_leg,
          tensor,
          mask,
          leg_idx);
    }
    std::tuple<TensorBackend::DataPtr, TensorProduct::Ptr, TensorProduct::Ptr>
    mask_contract_small_leg(TensorCPtr tensor, MaskCPtr mask, int64 leg_idx) override
    {
        PYBIND11_OVERRIDE_PURE(
          PYBIND11_TYPE(
            std::tuple<TensorBackend::DataPtr, TensorProduct::Ptr, TensorProduct::Ptr>),
          TensorBackend,
          mask_contract_small_leg,
          tensor,
          mask,
          leg_idx);
    }
    TensorBackend::DataPtr mask_dagger(MaskCPtr mask) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr, TensorBackend, mask_dagger, mask);
    }
    std::tuple<TensorBackend::DataPtr, ElementarySpace::Ptr> mask_from_block(
      BlockBackend::BlockPtr a,
      Space::Ptr large_leg) override
    {
        PYBIND11_OVERRIDE_PURE(
          PYBIND11_TYPE(std::tuple<TensorBackend::DataPtr, ElementarySpace::Ptr>),
          TensorBackend,
          mask_from_block,
          a,
          large_leg);
    }
    BlockBackend::BlockPtr mask_to_block(MaskCPtr a) override
    {
        PYBIND11_OVERRIDE_PURE(BlockBackend::BlockPtr, TensorBackend, mask_to_block, a);
    }
    TensorBackend::DataPtr mask_to_diagonal(MaskCPtr a, Dtype dtype) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr, TensorBackend, mask_to_diagonal, a, dtype);
    }
    std::tuple<Space::Ptr, Space::Ptr, TensorBackend::DataPtr> mask_transpose(
      MaskCPtr tens) override
    {
        PYBIND11_OVERRIDE_PURE(
          PYBIND11_TYPE(std::tuple<Space::Ptr, Space::Ptr, TensorBackend::DataPtr>),
          TensorBackend,
          mask_transpose,
          tens);
    }
    std::tuple<TensorBackend::DataPtr, ElementarySpace::Ptr> mask_unary_operand(
      MaskCPtr mask,
      BlockUnaryFn func) override
    {
        py::function py_func =
          py::cpp_function([func](BlockBackend::BlockPtr const& b) { return func(b); });
        PYBIND11_OVERRIDE_PURE(
          PYBIND11_TYPE(std::tuple<TensorBackend::DataPtr, ElementarySpace::Ptr>),
          TensorBackend,
          mask_unary_operand,
          mask,
          py_func);
    }
    TensorBackend::DataPtr move_to_device(TensorCPtr a, std::string device) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr, TensorBackend, move_to_device, a, device);
    }
    TensorBackend::DataPtr mul(BlockBackend::Scalar a, TensorCPtr b) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr, TensorBackend, mul, a, b);
    }
    BlockBackend::Scalar norm(TensorCPtr a) override
    {
        PYBIND11_OVERRIDE_PURE(BlockBackend::Scalar, TensorBackend, norm, a);
    }
    TensorBackend::DataPtr outer(SymmetricTensorCPtr a, SymmetricTensorCPtr b) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr, TensorBackend, outer, a, b);
    }
    TensorBackend::DataPtr partial_compose(SymmetricTensorCPtr a,
                                           SymmetricTensorCPtr b,
                                           int64 a_first_leg,
                                           TensorProduct::Ptr new_codomain,
                                           TensorProduct::Ptr new_domain) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr,
                               TensorBackend,
                               partial_compose,
                               a,
                               b,
                               a_first_leg,
                               new_codomain,
                               new_domain);
    }
    std::tuple<TensorBackend::DataPtr, TensorProduct::Ptr, TensorProduct::Ptr> partial_trace(
      SymmetricTensorCPtr tensor,
      std::vector<std::pair<int64, int64>> pairs,
      std::vector<std::optional<int64>> levels) override
    {
        PYBIND11_OVERRIDE_PURE(
          PYBIND11_TYPE(
            std::tuple<TensorBackend::DataPtr, TensorProduct::Ptr, TensorProduct::Ptr>),
          TensorBackend,
          partial_trace,
          tensor,
          pairs,
          levels);
    }
    TensorBackend::DataPtr permute_legs(TensorCPtr a,
                                        std::vector<int64> codomain_idcs,
                                        std::vector<int64> domain_idcs,
                                        TensorProduct::Ptr new_codomain,
                                        TensorProduct::Ptr new_domain,
                                        bool mixes_codomain_domain,
                                        std::vector<std::optional<int64>> levels,
                                        std::vector<std::optional<bool>> bend_right) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr,
                               TensorBackend,
                               permute_legs,
                               a,
                               codomain_idcs,
                               domain_idcs,
                               new_codomain,
                               new_domain,
                               mixes_codomain_domain,
                               levels,
                               bend_right);
    }
    std::tuple<TensorBackend::DataPtr, TensorBackend::DataPtr> qr(
      SymmetricTensorCPtr a,
      TensorProduct::Ptr new_co_domain) override
    {
        PYBIND11_OVERRIDE_PURE(
          PYBIND11_TYPE(std::tuple<TensorBackend::DataPtr, TensorBackend::DataPtr>),
          TensorBackend,
          qr,
          a,
          new_co_domain);
    }
    BlockBackend::Scalar reduce_DiagonalTensor(DiagonalTensorCPtr tensor,
                                               BlockToScalarFn block_func,
                                               ScalarReduceFn func) override
    {
        py::function py_block = py::cpp_function(
          [block_func](BlockBackend::BlockPtr const& b) { return block_func(b); });
        py::function py_reduce = py::cpp_function(
          [func](std::vector<BlockBackend::Scalar> const& xs) { return func(xs); });
        PYBIND11_OVERRIDE_PURE(
          BlockBackend::Scalar, TensorBackend, reduce_DiagonalTensor, tensor, py_block, py_reduce);
    }
    TensorBackend::DataPtr scale_axis(TensorCPtr a, DiagonalTensorCPtr b, int64 leg) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr, TensorBackend, scale_axis, a, b, leg);
    }
    TensorBackend::DataPtr split_legs(TensorCPtr a,
                                      std::vector<int64> leg_idcs,
                                      TensorProduct::Ptr new_codomain,
                                      TensorProduct::Ptr new_domain) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr,
                               TensorBackend,
                               split_legs,
                               a,
                               leg_idcs,
                               new_codomain,
                               new_domain);
    }
    TensorBackend::DataPtr squeeze_legs(TensorCPtr a, std::vector<int64> idcs) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr, TensorBackend, squeeze_legs, a, idcs);
    }
    bool supports_symmetry(Symmetry::Ptr symmetry) override
    {
        PYBIND11_OVERRIDE_PURE(bool, TensorBackend, supports_symmetry, symmetry);
    }
    std::tuple<TensorBackend::DataPtr, TensorBackend::DataPtr, TensorBackend::DataPtr> svd(
      SymmetricTensorCPtr a,
      TensorProduct::Ptr new_co_domain,
      std::optional<std::string> algorithm) override
    {
        PYBIND11_OVERRIDE_PURE(
          PYBIND11_TYPE(
            std::tuple<TensorBackend::DataPtr, TensorBackend::DataPtr, TensorBackend::DataPtr>),
          TensorBackend,
          svd,
          a,
          new_co_domain,
          algorithm);
    }
    py::object state_tensor_product(BlockBackend::BlockPtr state1,
                                    BlockBackend::BlockPtr state2,
                                    LegPipe::Ptr pipe) override
    {
        PYBIND11_OVERRIDE_PURE(
          py::object, TensorBackend, state_tensor_product, state1, state2, pipe);
    }
    TensorBackend::DataPtr to_block_backend(TensorBackend::DataPtr data,
                                            std::shared_ptr<BlockBackend> block_backend,
                                            std::optional<Dtype> dtype,
                                            std::optional<std::string> device) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr,
                               TensorBackend,
                               to_block_backend,
                               data,
                               block_backend,
                               dtype,
                               device);
    }
    BlockBackend::BlockPtr to_dense_block(TensorCPtr a) override
    {
        PYBIND11_OVERRIDE_PURE(BlockBackend::BlockPtr, TensorBackend, to_dense_block, a);
    }
    BlockBackend::BlockPtr to_dense_block_trivial_sector(TensorCPtr tensor) override
    {
        PYBIND11_OVERRIDE_PURE(
          BlockBackend::BlockPtr, TensorBackend, to_dense_block_trivial_sector, tensor);
    }
    TensorBackend::DataPtr to_dtype(TensorCPtr a, Dtype dtype) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr, TensorBackend, to_dtype, a, dtype);
    }
    BlockBackend::Scalar trace_full(SymmetricTensorCPtr a,
                                    std::vector<int64> idcs1,
                                    std::vector<int64> idcs2) override
    {
        PYBIND11_OVERRIDE_PURE(BlockBackend::Scalar, TensorBackend, trace_full, a, idcs1, idcs2);
    }
    std::tuple<TensorBackend::DataPtr, ElementarySpace::Ptr, float64, float64>
    truncate_singular_values(DiagonalTensorCPtr S,
                             std::optional<int64> chi_max,
                             int64 chi_min,
                             float64 degeneracy_tol,
                             float64 trunc_cut,
                             std::optional<float64> svd_min,
                             bool minimize_error) override
    {
        PYBIND11_OVERRIDE_PURE(
          PYBIND11_TYPE(
            std::tuple<TensorBackend::DataPtr, ElementarySpace::Ptr, float64, float64>),
          TensorBackend,
          truncate_singular_values,
          S,
          chi_max,
          chi_min,
          degeneracy_tol,
          trunc_cut,
          svd_min,
          minimize_error);
    }
    TensorBackend::DataPtr zero_data(TensorProduct::Ptr codomain,
                                     TensorProduct::Ptr domain,
                                     Dtype dtype,
                                     std::string device,
                                     bool all_blocks) override
    {
        PYBIND11_OVERRIDE_PURE(TensorBackend::DataPtr,
                               TensorBackend,
                               zero_data,
                               codomain,
                               domain,
                               dtype,
                               device,
                               all_blocks);
    }
    TensorBackend::DataPtr zero_diagonal_data(TensorProduct::Ptr co_domain,
                                              Dtype dtype,
                                              std::string device) override
    {
        PYBIND11_OVERRIDE_PURE(
          TensorBackend::DataPtr, TensorBackend, zero_diagonal_data, co_domain, dtype, device);
    }
    TensorBackend::DataPtr zero_mask_data(Space::Ptr large_leg, std::string device) override
    {
        PYBIND11_OVERRIDE_PURE(
          TensorBackend::DataPtr, TensorBackend, zero_mask_data, large_leg, device);
    }
    bool is_real(TensorCPtr a) override { PYBIND11_OVERRIDE(bool, TensorBackend, is_real, a); }
    void save_hdf5(py::object hdf5_saver, py::object h5gr, std::string subpath) override
    {
        PYBIND11_OVERRIDE(void, TensorBackend, save_hdf5, hdf5_saver, h5gr, subpath);
    }
}; // trampoline class PyTensorBackend

} // namespace cyten
