#pragma once

#include <cyten/cyten.h>

namespace cyten {

// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_declaration --py-name Leg --header-file include/cyten/symmetries/spaces.h

/// Common base class for a single leg of a tensor.
class Leg {
public:
public:
    Leg(Symmetry::Ptr symmetry, int64 dim, bool is_dual, ndarray_None basis_perm);
    virtual ~Leg() = default;
    /// The dual leg, that is obtained when bending this leg.
    /// property getter
    virtual Leg get_dual() = 0;
    /// property getter
    virtual bool get_is_trivial() = 0;
    /// Permutation that translates between public and internal basis order.
    /// property getter
    ndarray get_basis_perm();
    /// Common setter for :attr:`basis_perm` and :attr:`inverse_basis_perm`.
    virtual TYPEOF_return set_basis_perm(
        Sequence_int__None basis_perm=UNSPECIFIED,
        Sequence_int__None inverse_basis_perm=UNSPECIFIED
    );
    /// Flatten until there are no more pipes.
    /// property getter
    virtual list_ElementarySpace_ get_flat_legs();
    /// Flatten until we get spaces.
    /// property getter
    virtual list_ElementarySpace_ get_flat_spaces();
    /// Inverse permutation of :attr:`basis_perm`.
    /// property getter
    ndarray get_inverse_basis_perm();
    /// property getter
    TYPEOF_return set_inverse_basis_perm(TYPEOF_inverse_basis_perm inverse_basis_perm);
    /// The number of :attr:`flat_legs`.
    /// property getter
    virtual int64 get_num_flat_legs();
    /// A single character arrow, for use in tensor diagrams
    /// property getter
    std::string get_ascii_arrow();
    /// Perform sanity checks.
    virtual TYPEOF_return test_sanity();
    /// Convert to (an appropriate subclass of) :class:`Space`.
    virtual Space as_Space() = 0;
    /// Convert to an isomorphic :class:`ElementarySpace`
    virtual ElementarySpace as_ElementarySpace(bool is_dual=false);
    /// The dual leg, that is obtained when bending this leg.
    /// property getter
    virtual Leg get_dual() = 0;
    /// property getter
    virtual bool get_is_trivial() = 0;
    /// property getter
    TYPEOF_return set_basis_perm(TYPEOF_basis_perm basis_perm);
    /// Flatten until there are no more pipes.
    /// property getter
    virtual list_ElementarySpace_ get_flat_legs();
    /// Flatten until we get spaces.
    /// property getter
    virtual list_ElementarySpace_ get_flat_spaces();
    /// property getter
    TYPEOF_return set_inverse_basis_perm(TYPEOF_inverse_basis_perm inverse_basis_perm);
    /// The number of :attr:`flat_legs`.
    /// property getter
    virtual int64 get_num_flat_legs();
    /// Leg permutation such that combining legs would be in C style.
    virtual list_int_ _flat_leg_permutation(int64 offset=0);
    /// A single character arrow, for use in tensor diagrams
    /// property getter
    std::string get_ascii_arrow();
    virtual bool operator==(TYPEOF_other other) = 0;
    /// Apply the basis_perm, i.e. form ``arr[self.basis_perm]``.
    TYPEOF_return apply_basis_perm(TYPEOF_arr arr, int64 axis=0, bool inverse=false, bool pre_compose=false);
};

} // namespace cyten
