#pragma once

#include <cyten/cyten.h>

namespace cyten {

// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_declaration --py-name SU2 --header-file include/cyten/symmetries/su2.h

/// SU(2) symmetry.
class SU2 : public Group {
public:
    static TYPEOF_fusion_tensor_dtype fusion_tensor_dtype;
    static TYPEOF_spin_zero spin_zero;
    static TYPEOF_spin_half spin_half;
    static TYPEOF_spin_one spin_one;
public:
    SU2(std::string descriptive_name=py::none());
    virtual ~SU2() = default;
    bool is_valid_sector(Sector a);
    bool are_valid_sectors(TYPEOF_sectors sectors);
    Sector fusion_outcomes(Sector a, Sector b);
    bool can_fuse_to(Sector a, Sector b, Sector c);
    int64 sector_dim(Sector a);
    np_NDArray batch_sector_dim(Sector a);
    std::string sector_str(Sector a);
    str __repr__();
    bool _is_equivalent_factor(TYPEOF_other other);
    Sector dual_sector(Sector a);
    Sector dual_sectors(Sector sectors);
    int64 _n_symbol(Sector a, Sector b, Sector c);
    np_NDArray _f_symbol(Sector a, Sector b, Sector c, Sector d, Sector e, Sector f);
    TYPEOF_return frobenius_schur(Sector a);
    float64 qdim(Sector a);
    np_NDArray _r_symbol(Sector a, Sector b, Sector c);
    np_NDArray _fusion_tensor(Sector a, Sector b, Sector c, bool Z_a, bool Z_b);
    np_NDArray Z_iso(Sector a);
};

} // namespace cyten
