#pragma once

#include <cyten/cyten.h>

namespace cyten {

// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_declaration --py-name SUN --header-file include/cyten/symmetries/sun.h

/// SU(N) group symmetry
class SUN : public Group {
public:
    static TYPEOF_fusion_tensor_dtype fusion_tensor_dtype;
public:
    SUN(int64 N, TYPEOF_CGfile CGfile, TYPEOF_Ffile Ffile, TYPEOF_Rfile Rfile, std::string descriptive_name=py::none());
    virtual ~SUN() = default;
    bool is_valid_sector(Sector a);
    bool _is_equivalent_factor(TYPEOF_other other);
    /// Dimension of irrep given as first row of GT pattern
    int64 sector_dim(Sector a);
    str __repr__();
    /// Finds the dual irrep for a given input irrep.
    Sector dual_sector(Sector a);
    int64 hweight_from_CG_hdf5();
    int64 hweight_from_F_hdf5();
    int64 hweight_from_R_hdf5();
    /// Returns True if c appears at least once in the decomposition of a x b and False otherwise.
    bool can_fuse_to(Sector a, Sector b, Sector c);
    /// Returns the fusion multiplicity of an irrep c in the decomposition of a x b.
    int64 _n_symbol(Sector a, Sector b, Sector c);
    /// To every SU(N) irrep, labeled by the first row of a GT pattern, we can assign an integer S.
    int64 S_index_irrep_weight(Sector a);
    /// Returns the highest irrep which appears in the decomposition of a x b.
    Sector highest_irrep_in_decomp(Sector a, Sector b);
    /// Returns a SectorArray of all irreps appearing in the decomposition of  a x b.
    Sector fusion_outcomes(Sector a, Sector b);
    /// Returns a dictionary with irreps as keys and their dimension as values.
    dict dims_of_irreps(Sector a, Sector b);
    /// Returns a dictionary with the outer multiplicities for the irreps in the decomposition of a x b.
    dict outer_multiplicity_from_CG(Sector a, Sector b);
    /// Evaluate a single Clebsch-Gordan coefficient.
    float64 clebschgordan(Sector a, int64 q_a, Sector b, int64 q_b, Sector c, int64 q_c, int64 mu);
    /// Returns the clebsch fusion tensor for the specified input irreps.
    np_NDArray _fusion_tensor(Sector a, Sector b, Sector c, bool Z_a=false, bool Z_b=false);
    /// Returns the F symbol for the specified input irreps calculated from CG coefficients.
    TYPEOF_return _f_symbol_from_CG(Sector a, Sector b, Sector c, Sector d, Sector e, Sector f);
    /// Returns the F symbol for the specified input irreps loaded from the hdf5 file.
    np_NDArray _f_symbol(Sector a, Sector b, Sector c, Sector d, Sector e, Sector f);
    /// Returns the R symbol for the specified input irreps calculated from CG coefficients.
    TYPEOF_return _r_symbol_from_CG(Sector a, Sector b, Sector c);
    /// Returns the R symbol for the specified input irreps from the hdf5 file.
    TYPEOF_return _r_symbol(Sector a, Sector b, Sector c);
    /// Returns the Frobenius-Schur indicator for a given irrep
    int64 frobenius_schur(Sector a);
    TYPEOF_return has_data_in_group(TYPEOF_group group);
    /// Sanity check for Hdf5 files containing CG-coefficients, F-symbols or R-symbols.
    TYPEOF_return sanity_check_hdf5(TYPEOF_file file);
};

} // namespace cyten
// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_declaration --py-name SUN --header-file include/cyten/symmetries/sun.h

/// SU(N) group symmetry
class SUN : public Group {
public:
    static TYPEOF_fusion_tensor_dtype fusion_tensor_dtype;
public:
    SUN(int64 N, TYPEOF_CGfile CGfile, TYPEOF_Ffile Ffile, TYPEOF_Rfile Rfile, std::string descriptive_name=py::none());
    virtual ~SUN() = default;
    bool is_valid_sector(Sector a);
    bool _is_equivalent_factor(TYPEOF_other other);
    /// Dimension of irrep given as first row of GT pattern
    int64 sector_dim(Sector a);
    str __repr__();
    /// Finds the dual irrep for a given input irrep.
    Sector dual_sector(Sector a);
    int64 hweight_from_CG_hdf5();
    int64 hweight_from_F_hdf5();
    int64 hweight_from_R_hdf5();
    /// Returns True if c appears at least once in the decomposition of a x b and False otherwise.
    bool can_fuse_to(Sector a, Sector b, Sector c);
    /// Returns the fusion multiplicity of an irrep c in the decomposition of a x b.
    int64 _n_symbol(Sector a, Sector b, Sector c);
    /// To every SU(N) irrep, labeled by the first row of a GT pattern, we can assign an integer S.
    int64 S_index_irrep_weight(Sector a);
    /// Returns the highest irrep which appears in the decomposition of a x b.
    Sector highest_irrep_in_decomp(Sector a, Sector b);
    /// Returns a SectorArray of all irreps appearing in the decomposition of  a x b.
    Sector fusion_outcomes(Sector a, Sector b);
    /// Returns a dictionary with irreps as keys and their dimension as values.
    dict dims_of_irreps(Sector a, Sector b);
    /// Returns a dictionary with the outer multiplicities for the irreps in the decomposition of a x b.
    dict outer_multiplicity_from_CG(Sector a, Sector b);
    /// Evaluate a single Clebsch-Gordan coefficient.
    float64 clebschgordan(Sector a, int64 q_a, Sector b, int64 q_b, Sector c, int64 q_c, int64 mu);
    /// Returns the clebsch fusion tensor for the specified input irreps.
    np_NDArray _fusion_tensor(Sector a, Sector b, Sector c, bool Z_a=false, bool Z_b=false);
    /// Returns the F symbol for the specified input irreps calculated from CG coefficients.
    TYPEOF_return _f_symbol_from_CG(Sector a, Sector b, Sector c, Sector d, Sector e, Sector f);
    /// Returns the F symbol for the specified input irreps loaded from the hdf5 file.
    np_NDArray _f_symbol(Sector a, Sector b, Sector c, Sector d, Sector e, Sector f);
    /// Returns the R symbol for the specified input irreps calculated from CG coefficients.
    TYPEOF_return _r_symbol_from_CG(Sector a, Sector b, Sector c);
    /// Returns the R symbol for the specified input irreps from the hdf5 file.
    TYPEOF_return _r_symbol(Sector a, Sector b, Sector c);
    /// Returns the Frobenius-Schur indicator for a given irrep
    int64 frobenius_schur(Sector a);
    TYPEOF_return has_data_in_group(TYPEOF_group group);
    /// Sanity check for Hdf5 files containing CG-coefficients, F-symbols or R-symbols.
    TYPEOF_return sanity_check_hdf5(TYPEOF_file file);
};
