
#include "cyten_pybind11.h"
#include <cyten/block_backend/array_api.h>

namespace cyten {

void
bind_array_api(py::module_& m)
{
    // CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_pyb11_binding --py-name ArrayApiBlockBackend --header-file include/cyten/block_backend/array_api.h --binding-file pybind/block_backend/py_array_api.cpp

py::class_<ArrayApiBlockBackendBlockBackend, py::smart_holder> array_api_block_backend(m, "ArrayApiBlockBackend");
array_api_block_backend.doc() = "A block-backend based on a generic Array API compliant library";

array_api_block_backend // init and attributes
    .def(py::init<TYPEOF_api_namespace,std::string>())
; // completed array_api_block_backend attributes

array_api_block_backend //  methods
    .def("as_block", &ArrayApiBlockBackend::as_block,
        py::arg("a"),
        py::arg("dtype") = py::none(),
        py::arg("device") = py::none()
        )
    .def("as_device", &ArrayApiBlockBackend::as_device,
        py::arg("device")
        )
    .def("all", &ArrayApiBlockBackend::all,
        py::arg("a")
        )
    .def("any", &ArrayApiBlockBackend::any,
        py::arg("a")
        )
    .def("tdot", &ArrayApiBlockBackend::tdot,
        py::arg("a"),
        py::arg("b"),
        py::arg("idcs_a"),
        py::arg("idcs_b")
        )
    .def("get_shape", &ArrayApiBlockBackend::get_shape,
        py::arg("a")
        )
    .def("item", &ArrayApiBlockBackend::item,
        py::arg("a")
        )
    .def("get_dtype", &ArrayApiBlockBackend::get_dtype,
        py::arg("a")
        )
    .def("to_dtype", &ArrayApiBlockBackend::to_dtype,
        py::arg("a"),
        py::arg("dtype")
        )
    .def("copy_block", &ArrayApiBlockBackend::copy_block,
        py::arg("a"),
        py::arg("device") = py::none()
        )
    .def("_block_repr_lines", &ArrayApiBlockBackend::_block_repr_lines,
        py::arg("a"),
        py::arg("indent"),
        py::arg("max_width"),
        py::arg("max_lines")
        )
    .def("outer", &ArrayApiBlockBackend::outer,
        py::arg("a"),
        py::arg("b")
        )
    .def("permute_axes", &ArrayApiBlockBackend::permute_axes,
        py::arg("a"),
        py::arg("permutation")
        )
    .def("trace_full", &ArrayApiBlockBackend::trace_full,
        py::arg("a")
        )
    .def("trace_partial", &ArrayApiBlockBackend::trace_partial,
        py::arg("a"),
        py::arg("idcs1"),
        py::arg("idcs2"),
        py::arg("remaining")
        )
    .def("conj", &ArrayApiBlockBackend::conj,
        py::arg("a")
        )
    .def("angle", &ArrayApiBlockBackend::angle,
        py::arg("a")
        )
    .def("real", &ArrayApiBlockBackend::real,
        py::arg("a")
        )
    .def("real_if_close", &ArrayApiBlockBackend::real_if_close,
        py::arg("a"),
        py::arg("tol")
        )
    .def("sqrt", &ArrayApiBlockBackend::sqrt,
        py::arg("a")
        )
    .def("imag", &ArrayApiBlockBackend::imag,
        py::arg("a")
        )
    .def("exp", &ArrayApiBlockBackend::exp,
        py::arg("a")
        )
    .def("log", &ArrayApiBlockBackend::log,
        py::arg("a")
        )
    .def("allclose", &ArrayApiBlockBackend::allclose,
        py::arg("a"),
        py::arg("b"),
        py::arg("rtol") = 1e-05,
        py::arg("atol") = 1e-08
        )
    .def("squeeze_axes", &ArrayApiBlockBackend::squeeze_axes,
        py::arg("a"),
        py::arg("idcs")
        )
    .def("add_axis", &ArrayApiBlockBackend::add_axis,
        py::arg("a"),
        py::arg("pos")
        )
    .def("norm", &ArrayApiBlockBackend::norm,
        py::arg("a"),
        py::arg("order") = 2,
        py::arg("axis") = py::none()
        )
    .def("max", &ArrayApiBlockBackend::max,
        py::arg("a")
        )
    .def("max_abs", &ArrayApiBlockBackend::max_abs,
        py::arg("a")
        )
    .def("min", &ArrayApiBlockBackend::min,
        py::arg("a")
        )
    .def("reshape", &ArrayApiBlockBackend::reshape,
        py::arg("a"),
        py::arg("shape")
        )
    .def("matrix_dot", &ArrayApiBlockBackend::matrix_dot,
        py::arg("a"),
        py::arg("b")
        )
    .def("matrix_svd", &ArrayApiBlockBackend::matrix_svd,
        py::arg("a"),
        py::arg("algorithm")
        )
    .def("possible_svd_algorithms", &ArrayApiBlockBackend::possible_svd_algorithms,
        "Cannot specify algorithms through the array API."
        )
    .def("matrix_qr", &ArrayApiBlockBackend::matrix_qr,
        py::arg("a"),
        py::arg("full")
        )
    .def("matrix_exp", &ArrayApiBlockBackend::matrix_exp,
        py::arg("matrix")
        )
    .def("random_uniform", &ArrayApiBlockBackend::random_uniform,
        py::arg("dims"),
        py::arg("dtype"),
        py::arg("device") = py::none()
        )
    .def("random_normal", &ArrayApiBlockBackend::random_normal,
        py::arg("dims"),
        py::arg("dtype"),
        py::arg("sigma"),
        py::arg("device") = py::none()
        )
    .def("block_from_numpy", &ArrayApiBlockBackend::block_from_numpy,
        py::arg("a"),
        py::arg("dtype") = py::none(),
        py::arg("device") = py::none()
        )
    .def("zeros", &ArrayApiBlockBackend::zeros,
        py::arg("shape"),
        py::arg("dtype"),
        py::arg("device") = py::none()
        )
    .def("ones_block", &ArrayApiBlockBackend::ones_block,
        py::arg("shape"),
        py::arg("dtype"),
        py::arg("device") = py::none()
        )
    .def("eye_matrix", &ArrayApiBlockBackend::eye_matrix,
        py::arg("dim"),
        py::arg("dtype"),
        py::arg("device") = py::none()
        )
    .def("kron", &ArrayApiBlockBackend::kron,
        py::arg("a"),
        py::arg("b")
        )
    .def("get_block_element", &ArrayApiBlockBackend::get_block_element,
        py::arg("a"),
        py::arg("idcs")
        )
    .def("get_device", &ArrayApiBlockBackend::get_device,
        py::arg("a")
        )
    .def("get_diagonal", &ArrayApiBlockBackend::get_diagonal,
        py::arg("a"),
        py::arg("tol")
        )
    .def("block_from_diagonal", &ArrayApiBlockBackend::block_from_diagonal,
        py::arg("diag")
        )
    .def("block_from_mask", &ArrayApiBlockBackend::block_from_mask,
        py::arg("mask"),
        py::arg("dtype")
        )
    .def("sum", &ArrayApiBlockBackend::sum,
        py::arg("a"),
        py::arg("ax")
        )
    .def("sum_all", &ArrayApiBlockBackend::sum_all,
        py::arg("a")
        )
    .def("eigh", &ArrayApiBlockBackend::eigh,
        py::arg("block"),
        py::arg("sort") = py::none()
        )
    .def("eigvalsh", &ArrayApiBlockBackend::eigvalsh,
        py::arg("block"),
        py::arg("sort") = py::none()
        )
    .def("abs_argmax", &ArrayApiBlockBackend::abs_argmax,
        py::arg("block")
        )
    .def("_argsort", &ArrayApiBlockBackend::_argsort,
        py::arg("block"),
        py::arg("axis")
        )
    .def("enlarge_leg", &ArrayApiBlockBackend::enlarge_leg,
        py::arg("block"),
        py::arg("mask"),
        py::arg("axis")
        )
    .def("stable_log", &ArrayApiBlockBackend::stable_log,
        py::arg("block"),
        py::arg("cutoff")
        )
; // completed array_api_block_backend methods
}

}  // namespace cyten
