#pragma once

#include <cyten/tensors/symmetric_tensor.h>

namespace cyten {

// DiagonalTensor declaration follows (codegen + manual improvements).

} // namespace cyten
// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_declaration --py-name DiagonalTensor --header-file include/cyten/tensors/diagonal_tensor.h

/// Special case of a :class:`SymmetricTensor` that is diagonal in the computational basis.
class DiagonalTensor : public SymmetricTensor {
public:
    static TYPEOF__forbidden_dtypes _forbidden_dtypes;
public:
    DiagonalTensor(
        TYPEOF_data data,
        Space::Ptr leg,
        TensorBackend::Ptr backend=py::none(),
        Sequence_list_str_None__None__list_str_None__None labels=py::none()
    );
    virtual ~DiagonalTensor() = default;
    /// Return the single space that makes up to domain and codomain.
    /// property getter
    Space::Ptr get_leg();
    /// Perform sanity checks.
    virtual TYPEOF_return test_sanity() override;
    virtual TYPEOF_return verify_dtype() override;
    virtual TYPEOF_return from_block_func(
        TYPEOF_func func,
        Space::Ptr leg,
        TensorBackend::Ptr backend=py::none(),
        Sequence_list_str_None__None__list_str_None__None labels=py::none(),
        dict func_kwargs=py::none(),
        std::string shape_kw=py::none(),
        Dtype dtype=py::none(),
        std::string device=py::none()
    ) override;
    virtual TYPEOF_return from_dense_block(
        BlockBackend::BlockPtr block,
        Space::Ptr leg,
        TensorBackend::Ptr backend=py::none(),
        Sequence_list_str_None__None__list_str_None__None labels=py::none(),
        Dtype dtype=py::none(),
        float64 tol=1e-06,
        std::string device=py::none(),
        bool understood_braiding=false
    ) override;
    /// Convert a dense 1D block containing the diagonal entries to a DiagonalTensor.
    virtual TYPEOF_return from_diag_block(
        BlockBackend::BlockPtr diag,
        Space::Ptr leg,
        TensorBackend::Ptr backend=py::none(),
        Sequence_list_str_None__None__list_str_None__None labels=py::none(),
        Dtype dtype=py::none(),
        std::string device=py::none(),
        float64 tol=1e-06
    );
    /// The identity map as a DiagonalTensor.
    virtual TYPEOF_return from_eye(
        Space::Ptr leg,
        TensorBackend::Ptr backend=py::none(),
        Sequence_list_str_None__None__list_str_None__None labels=py::none(),
        Dtype dtype=Dtype.float64,
        std::string device=py::none()
    ) override;
    /// Generate a sample from the complex normal distribution.
    virtual TYPEOF_return from_random_normal(
        Space::Ptr leg,
        py::object mean=py::none(),
        float64 sigma=1.0,
        TensorBackend::Ptr backend=py::none(),
        Sequence_list_str_None__None__list_str_None__None labels=py::none(),
        Dtype dtype=Dtype.complex128,
        std::string device=py::none()
    ) override;
    /// Generate a tensor with uniformly random block-entries.
    virtual TYPEOF_return from_random_uniform(
        Space::Ptr leg,
        TensorBackend::Ptr backend=py::none(),
        Sequence_list_str_None__None__list_str_None__None labels=py::none(),
        Dtype dtype=Dtype.complex128,
        std::string device=py::none()
    ) override;
    virtual TYPEOF_return from_sector_block_func(
        TYPEOF_func func,
        Space::Ptr leg,
        TensorBackend::Ptr backend=py::none(),
        Sequence_list_str_None__None__list_str_None__None labels=py::none(),
        dict func_kwargs=py::none(),
        Dtype dtype=py::none(),
        std::string device=py::none()
    ) override;
    /// Create DiagonalTensor from a Tensor.
    virtual py::object from_tensor(SymmetricTensor::Ptr tens, float64 tol=1e-12);
    /// A zero tensor.
    virtual TYPEOF_return from_zero(
        Space::Ptr leg,
        TensorBackend::Ptr backend=py::none(),
        Sequence_list_str_None__None__list_str_None__None labels=py::none(),
        Dtype dtype=Dtype.complex128,
        std::string device=py::none()
    ) override;
    /// Return the single space that makes up to domain and codomain.
    /// property getter
    Space::Ptr get_leg();
    virtual TYPEOF_return __abs__();
    virtual bool operator bool();
    virtual TYPEOF_return operator+(TYPEOF_other other) override;
    bool operator>=(TYPEOF_other other);
    bool operator>(TYPEOF_other other);
    bool operator<=(TYPEOF_other other);
    bool operator<(TYPEOF_other other);
    virtual TYPEOF_return operator*(TYPEOF_other other) override;
    TYPEOF_return __pow__(TYPEOF_other other);
    TYPEOF_return __radd__(TYPEOF_other other);
    virtual TYPEOF_return __rmul__(TYPEOF_other other) override;
    TYPEOF_return __rpow__(TYPEOF_other other);
    TYPEOF_return __rsub__(TYPEOF_other other);
    TYPEOF_return __rtruediv__(TYPEOF_other other);
    virtual TYPEOF_return operator-(TYPEOF_other other) override;
    virtual TYPEOF_return operator/(TYPEOF_other other) override;
    /// For a bool dtype, if all values are True. Raises for other dtypes.
    virtual bool all();
    /// For a bool dtype, if any value is True. Raises for other dtypes.
    virtual bool any();
    virtual py::object as_dtype(Dtype dtype) override;
    virtual TYPEOF_return as_DiagonalTensor(TYPEOF_guarantee_copy guarantee_copy=false, TYPEOF_warning warning=py::none());
    virtual SymmetricTensor::Ptr as_SymmetricTensor(bool guarantee_copy=false, std::string warning=py::none()) override;
    /// Common implementation for the binary dunder methods ``__mul__`` etc.
    virtual TYPEOF_return _binary_operand(
        Number_Scalar_DiagonalTensor other,
        TYPEOF_func func,
        std::string operand,
        bool return_NotImplemented=false,
        bool right=false
    );
    virtual py::object copy(bool deep=true, std::string device=py::none(), Dtype dtype=py::none()) override;
    virtual py::object diagonal() override;
    virtual BlockBackend::BlockPtr diagonal_as_block(Dtype dtype=py::none());
    virtual np_NDArray diagonal_as_numpy(TYPEOF_numpy_dtype numpy_dtype=py::none());
    virtual py::object elementwise_almost_equal(py::object other, float64 rtol=1e-05, TYPEOF_atol atol=1e-08);
    /// An elementwise function acting on two diagonal tensors.
    virtual py::object _elementwise_binary(
        py::object other,
        TYPEOF_func func,
        dict func_kwargs=py::none(),
        bool partial_zero_is_zero=false
    );
    /// An elementwise function acting on a diagonal tensor.
    virtual py::object _elementwise_unary(TYPEOF_func func, dict func_kwargs=py::none(), bool maps_zero_to_zero=false);
    virtual Scalar _get_item(list_int_ idx) override;
    virtual TYPEOF_return max();
    virtual TYPEOF_return min();
    virtual TYPEOF_return move_to_device(std::string device) override;
    virtual py::object to_backend(TensorBackend::Ptr backend, Dtype dtype=py::none(), std::string device=py::none()) override;
    virtual BlockBackend::BlockPtr to_dense_block(
        list_int_str_ leg_order=py::none(),
        Dtype dtype=py::none(),
        bool understood_braiding=false
    ) override;
    /// Export DiagonalTensor to hdf5 such that it can be re-imported with from_hdf5
    virtual TYPEOF_return save_hdf5(TYPEOF_hdf5_saver hdf5_saver, TYPEOF_h5gr h5gr, TYPEOF_subpath subpath) override;
    /// Import DiagonalTensor from hdf5
    virtual TYPEOF_return from_hdf5(TYPEOF_hdf5_loader hdf5_loader, TYPEOF_h5gr h5gr, TYPEOF_subpath subpath) override;
};
