#pragma once

#include <cyten/tensors/diagonal_tensor.h>

namespace cyten {

// Mask declaration will be appended by codegen.

} // namespace cyten
// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_declaration --py-name Mask --header-file include/cyten/tensors/mask.h

/// A boolean mask that can be used to project or enlarge a leg.
class Mask : public Tensor {
public:
    static TYPEOF__forbidden_dtypes _forbidden_dtypes;
public:
    Mask(
        TYPEOF_data data,
        ElementarySpace::Ptr space_in,
        ElementarySpace::Ptr space_out,
        bool is_projection=py::none(),
        TensorBackend::Ptr backend=py::none(),
        Sequence_list_str_None__None__list_str_None__None labels=py::none()
    );
    virtual ~Mask() = default;
    /// property getter
    ElementarySpace::Ptr get_large_leg();
    /// property getter
    ElementarySpace::Ptr get_small_leg();
    /// Perform sanity checks.
    virtual TYPEOF_return test_sanity() override;
    /// property getter
    ElementarySpace::Ptr get_large_leg();
    /// property getter
    ElementarySpace::Ptr get_small_leg();
    /// The identity map as a Mask, i.e. the mask that keeps all states and discards none.
    TYPEOF_return from_eye(
        ElementarySpace::Ptr leg,
        bool is_projection=true,
        TensorBackend::Ptr backend=py::none(),
        Sequence_list_str_None__None__list_str_None__None labels=py::none(),
        std::string device=py::none()
    );
    /// Create a projection Mask from a boolean block.
    TYPEOF_return from_block_mask(
        BlockBackend::BlockPtr block_mask,
        Space::Ptr large_leg,
        TensorBackend::Ptr backend=py::none(),
        Sequence_list_str_None__None__list_str_None__None labels=py::none(),
        std::string device=py::none()
    );
    /// Create a projection Mask from a boolean DiagonalTensor.
    TYPEOF_return from_DiagonalTensor(DiagonalTensor::Ptr diag);
    /// Create a projection Mask from the indices that are kept.
    TYPEOF_return from_indices(
        int64 indices,
        Space::Ptr large_leg,
        TensorBackend::Ptr backend=py::none(),
        Sequence_list_str_None__None__list_str_None__None labels=py::none(),
        std::string device=py::none()
    );
    /// Create a random projection Mask.
    TYPEOF_return from_random(
        Space::Ptr large_leg,
        Space::Ptr small_leg=py::none(),
        TensorBackend::Ptr backend=py::none(),
        float64 p_keep=0.5,
        int64 min_keep=0,
        Sequence_list_str_None__None__list_str_None__None labels=py::none(),
        std::string device=py::none(),
        np_random_Generator np_random=np.random.default_rng()
    );
    /// The zero projection Mask, that discards all states and keeps none.
    TYPEOF_return from_zero(
        Space::Ptr large_leg,
        TensorBackend::Ptr backend=py::none(),
        Sequence_list_str_None__None__list_str_None__None labels=py::none(),
        std::string device=py::none()
    );
    TYPEOF_return operator&(TYPEOF_other other);
    bool operator bool();
    virtual bool operator==(TYPEOF_other other) override;
    TYPEOF_return operator~();
    bool operator!=(TYPEOF_other other);
    TYPEOF_return operator|(TYPEOF_other other);
    TYPEOF_return __rand__(TYPEOF_other other);
    TYPEOF_return __ror__(TYPEOF_other other);
    TYPEOF_return __rxor__(TYPEOF_other other);
    TYPEOF_return operator^(TYPEOF_other other);
    /// If the mask keeps all basis elements
    bool all();
    /// If the mask keeps any basis elements
    bool any();
    BlockBackend::BlockPtr as_block_mask();
    np_NDArray as_numpy_mask();
    virtual Mask::Ptr as_dtype(Dtype dtype) override;
    DiagonalTensor::Ptr as_DiagonalTensor(TYPEOF_dtype dtype=Dtype.complex128);
    virtual SymmetricTensor::Ptr as_SymmetricTensor(
        bool guarantee_copy=false,
        std::string warning=py::none(),
        TYPEOF_dtype dtype=Dtype.complex128
    ) override;
    /// Utility function for a shared implementation of binary functions.
    Mask::Ptr _binary_operand(bool_Mask other, TYPEOF_func func, std::string operand, bool return_NotImplemented=true);
    virtual Mask::Ptr copy(bool deep=true, std::string device=py::none(), Dtype dtype=py::none()) override;
    virtual Scalar _get_item(list_int_ idx) override;
    /// Alias for :meth:`orthogonal_complement`
    TYPEOF_return logical_not();
    virtual TYPEOF_return move_to_device(std::string device) override;
    /// The "opposite" Mask, that keeps exactly what self discards and vv.
    TYPEOF_return orthogonal_complement();
    virtual Mask::Ptr to_backend(TensorBackend::Ptr backend, Dtype dtype=py::none(), std::string device=py::none()) override;
    virtual BlockBackend::BlockPtr to_dense_block(
        list_int_str_ leg_order=py::none(),
        Dtype dtype=py::none(),
        bool understood_braiding=false
    ) override;
    virtual np_NDArray to_numpy(
        list_int_str_ leg_order=py::none(),
        TYPEOF_numpy_dtype numpy_dtype=py::none(),
        bool understood_braiding=false
    ) override;
    Mask::Ptr _unary_operand(TYPEOF_func func);
    /// Export Mask to hdf5 such that it can be re-imported with from_hdf5
    TYPEOF_return save_hdf5(TYPEOF_hdf5_saver hdf5_saver, TYPEOF_h5gr h5gr, TYPEOF_subpath subpath);
    /// Import Mask from hdf5
    TYPEOF_return from_hdf5(TYPEOF_hdf5_loader hdf5_loader, TYPEOF_h5gr h5gr, TYPEOF_subpath subpath);
};
