#pragma once

#include <cyten/block_backend/block_backend.h>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <vector>

namespace cyten {

// ArrayApiBlockBackend declaration (codegen draft follows)

} // namespace cyten
// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_declaration --py-name ArrayApiBlockBackend --header-file include/cyten/block_backend/array_api.h

/// A block-backend based on a generic Array API compliant library
class ArrayApiBlockBackend public BlockBackend {
public:
public:
    ArrayApiBlockBackend(TYPEOF_api_namespace api_namespace, std::string default_device="cpu");
    virtual ~ArrayApiBlockBackend() = default;
    virtual BlockPtr as_block(TYPEOF_a a, Dtype dtype=py::none(), std::string device=py::none()) override;
    virtual std::string as_device(std::string device) override;
    virtual bool all(TYPEOF_a a) override;
    virtual bool any(TYPEOF_a a) override;
    virtual BlockPtr tdot(BlockPtr a, BlockPtr b, list_int_ idcs_a, list_int_ idcs_b) override;
    virtual tuple_int_ get_shape(BlockPtr a) override;
    virtual float64 item(BlockPtr a) override;
    virtual Dtype get_dtype(BlockPtr a) override;
    virtual BlockPtr to_dtype(BlockPtr a, Dtype dtype) override;
    virtual BlockPtr copy_block(BlockPtr a, std::string device=py::none()) override;
    virtual list_str_ _block_repr_lines(BlockPtr a, std::string indent, int64 max_width, int64 max_lines) override;
    virtual BlockPtr outer(BlockPtr a, BlockPtr b) override;
    virtual BlockPtr permute_axes(BlockPtr a, list_int_ permutation) override;
    virtual float64 trace_full(BlockPtr a) override;
    virtual BlockPtr trace_partial(BlockPtr a, list_int_ idcs1, list_int_ idcs2, list_int_ remaining) override;
    virtual BlockPtr conj(BlockPtr a) override;
    virtual BlockPtr angle(BlockPtr a) override;
    virtual BlockPtr real(BlockPtr a) override;
    virtual BlockPtr real_if_close(BlockPtr a, float64 tol) override;
    virtual BlockPtr sqrt(BlockPtr a) override;
    virtual BlockPtr imag(BlockPtr a) override;
    virtual BlockPtr exp(BlockPtr a) override;
    virtual BlockPtr log(BlockPtr a) override;
    virtual bool allclose(BlockPtr a, BlockPtr b, float64 rtol=1e-05, float64 atol=1e-08) override;
    virtual BlockPtr squeeze_axes(BlockPtr a, list_int_ idcs) override;
    virtual BlockPtr add_axis(BlockPtr a, int64 pos) override;
    virtual float64 norm(BlockPtr a, int64 order=2, int64 axis=py::none()) override;
    virtual float64 max(BlockPtr a) override;
    virtual float64 max_abs(BlockPtr a) override;
    virtual float64 min(BlockPtr a) override;
    virtual BlockPtr reshape(BlockPtr a, tuple_int_ shape) override;
    virtual BlockPtr matrix_dot(BlockPtr a, BlockPtr b) override;
    virtual tuple_Block_Block_Block_ matrix_svd(BlockPtr a, std::string algorithm) override;
    /// Cannot specify algorithms through the array API.
    list_str_ possible_svd_algorithms();
    virtual tuple_Block_Block_ matrix_qr(BlockPtr a, bool full) override;
    virtual BlockPtr matrix_exp(BlockPtr matrix) override;
    virtual BlockPtr random_uniform(list_int_ dims, Dtype dtype, std::string device=py::none()) override;
    virtual BlockPtr random_normal(list_int_ dims, Dtype dtype, float64 sigma, std::string device=py::none()) override;
    virtual BlockPtr block_from_numpy(np_NDArray a, Dtype dtype=py::none(), std::string device=py::none()) override;
    virtual BlockPtr zeros(list_int_ shape, Dtype dtype, std::string device=py::none()) override;
    virtual BlockPtr ones_block(list_int_ shape, Dtype dtype, std::string device=py::none()) override;
    virtual BlockPtr eye_matrix(int64 dim, Dtype dtype, std::string device=py::none()) override;
    virtual BlockPtr kron(BlockPtr a, BlockPtr b) override;
    virtual complex128 get_block_element(BlockPtr a, list_int_ idcs) override;
    virtual std::string get_device(BlockPtr a) override;
    virtual BlockPtr get_diagonal(BlockPtr a, float64 tol) override;
    virtual BlockPtr block_from_diagonal(BlockPtr diag) override;
    virtual BlockPtr block_from_mask(BlockPtr mask, Dtype dtype) override;
    virtual BlockPtr sum(BlockPtr a, int64 ax) override;
    virtual float64 sum_all(BlockPtr a) override;
    virtual tuple_Block_Block_ eigh(BlockPtr block, std::string sort=py::none()) override;
    virtual BlockPtr eigvalsh(BlockPtr block, std::string sort=py::none()) override;
    virtual list_int_ abs_argmax(BlockPtr block) override;
    virtual BlockPtr _argsort(BlockPtr block, int64 axis) override;
    virtual BlockPtr enlarge_leg(BlockPtr block, BlockPtr mask, int64 axis) override;
    virtual BlockPtr stable_log(BlockPtr block, float64 cutoff) override;
};
