#include <cyten/block_backend/array_api.h>

namespace cyten {

// ArrayApiBlockBackend definitions (codegen draft follows)

} // namespace cyten
// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_definition --py-name ArrayApiBlockBackend --header-file include/cyten/block_backend/array_api.h --src-file src/block_backend/array_api.cpp

using std::complex_literals::operatori; // 1.i for complex numbers
ArrayApiBlockBackend::ArrayApiBlockBackend(int api_namespace, const std::string & default_device) {
    /* CHECKME: converted from following python code:
     * self._api = api_namespace
     * self.BlockCls = type(api_namespace.zero(1))
     *         self.cyten_dtype_map = {
     *             api_namespace.float32: Dtype.float32,
     *             api_namespace.float64: Dtype.float64,
     *             api_namespace.complex64: Dtype.complex64,
     *             api_namespace.complex128: Dtype.complex128,
     *             api_namespace.bool: Dtype.bool,
     *             None: None,
     *         }
     *         self.backend_dtype_map = {
     *             Dtype.float32: api_namespace.float32,
     *             Dtype.float64: api_namespace.float64,
     *             Dtype.complex64: api_namespace.complex64,
     *             Dtype.complex128: api_namespace.complex128,
     *             Dtype.bool: api_namespace.bool,
     *             None: None,
     *         }
     * super().__init__(default_device=default_device)
     */
    _api = api_namespace;
    BlockCls = type(api_namespace.zero(1));
    cyten_dtype_map = {{api_namespace.float32, Dtype.float32}, {api_namespace.float64, Dtype.float64}, {api_namespace.complex64, Dtype.complex64}, {api_namespace.complex128, Dtype.complex128}, {api_namespace.bool, Dtype.bool}, {py::none(), py::none()}};
    backend_dtype_map = {{Dtype.float32, api_namespace.float32}, {Dtype.float64, api_namespace.float64}, {Dtype.complex64, api_namespace.complex64}, {Dtype.complex128, api_namespace.complex128}, {Dtype.bool, api_namespace.bool}, {py::none(), py::none()}};
    super().__init__(py::arg({keyword.key}) = val) /* CHECKME: keywords ['default_device'] */;
}

int ArrayApiBlockBackend::as_block(int a, int dtype, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     *         if device is None and not hasattr(a, 'device'):
     *             device = self.default_device
     * block = self._api.asarray(a, dtype=self.backend_dtype_map[dtype], device=device)
     *         if dtype != Dtype.bool:
     *             # force float or complex dtype without multiplying
     *             block = 1.0 * block
     * return block
     */
    if (device == py::none() && !(hasattr(a, "device"))) {
        device = default_device;
    }
    auto /* CHECKME: type? */ block = _api.asarray(a, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype', 'device'] */;
    if (dtype != Dtype.bool) {
        // force float or complex dtype without multiplying
        block = 1.0 * block;
    }
    return block;
}

std::string ArrayApiBlockBackend::as_device(std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     *         if device is None:
     *             device = self.default_device
     * # need to do this hack, since the API does not provide a unified way to instantiate
     * # device objects. making this block also guarantees that device is valid and available.
     * return str(self.ones_block([1], device=device).device)
     */
    if (device == py::none()) {
        device = default_device;
    }
    // need to do this hack, since the API does not provide a unified way to instantiate
    // device objects. making this block also guarantees that device is valid and available.
    return str(ones_block({1}, py::arg({keyword.key}) = val) /* CHECKME: keywords ['device'] */.device);
}

bool ArrayApiBlockBackend::all(const int & a) {
    /* CHECKME: converted from following python code:
     * return self._api.all(a)
     */
    return _api.all(a);
}

bool ArrayApiBlockBackend::any(const int & a) {
    /* CHECKME: converted from following python code:
     * return self._api.any(a)
     */
    return _api.any(a);
}

int ArrayApiBlockBackend::tdot(const int & a, const int & b, const int & idcs_a, const int & idcs_b) {
    /* CHECKME: converted from following python code:
     * return self._api.tensordot(a, b, (idcs_a, idcs_b))
     */
    return _api.tensordot(a, b, std::make_tuple(idcs_a, idcs_b));
}

tuple_int_ ArrayApiBlockBackend::get_shape(BlockPtr a) {
    /* CHECKME: converted from following python code:
     * shape = a.shape
     *         if None in shape:
     *             raise RuntimeError('Inconsistnet block. Unknown dimensions with None in shape not allowed.')
     * return shape
     */
    auto /* CHECKME: type? */ shape = a.shape;
    if (py::none() /* FIXME: In */ shape) {
        throw std::runtime_error("Inconsistnet block. Unknown dimensions with None in shape not allowed.");
    }
    return shape;
}

int ArrayApiBlockBackend::item(const int & a) {
    /* CHECKME: converted from following python code:
     *         if self.is_real(a):
     *             return float(a)
     * return complex(a)
     */
    if (is_real(a)) {
        return float(a);
    }
    return complex(a);
}

Dtype ArrayApiBlockBackend::get_dtype(BlockPtr a) {
    /* CHECKME: converted from following python code:
     * return self.cyten_dtype_map[a.dtype]
     */
    return cyten_dtype_map[a.dtype];
}

int ArrayApiBlockBackend::to_dtype(const int & a, int dtype) {
    /* CHECKME: converted from following python code:
     * return self._api.astype(a, self.backend_dtype_map[dtype])
     */
    return _api.astype(a, backend_dtype_map[dtype]);
}

int ArrayApiBlockBackend::copy_block(const int & a, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     * return self._api.asarray(a, copy=True, device=device)
     */
    return _api.asarray(a, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['copy', 'device'] */;
}

int ArrayApiBlockBackend::_block_repr_lines(const int & a, const std::string & indent, int max_width, int max_lines) {
    /* CHECKME: converted from following python code:
     * lines = [f'{indent}{line}' for line in str(a).split('\n')]
     *         if len(lines) > max_lines:
     *             first = (max_lines - 1) // 2
     *             last = max_lines - 1 - first
     *             lines = lines[:first] + [f'{indent}...'] + lines[-last:]
     * return lines
     */
    auto /* CHECKME: type? */ lines = /* FIXME: ListComp: [f'{indent}{line}' for line in str(a).split('\n')] */;
    if (len(lines) > max_lines) {
        auto /* CHECKME: type? */ first = max_lines - 1 / 2;
        auto /* CHECKME: type? */ last = max_lines - 1 - first;
        lines = lines[std::slice(0, first, 1)] + {std::format("{}...", indent)} + lines[std::slice(-last, (lines.size() - -last), 1)];
    }
    return lines;
}

int ArrayApiBlockBackend::outer(const int & a, const int & b) {
    /* CHECKME: converted from following python code:
     * return self._api.tensordot(a, b, 0)
     */
    return _api.tensordot(a, b, 0);
}

int ArrayApiBlockBackend::permute_axes(const int & a, const int & permutation) {
    /* CHECKME: converted from following python code:
     * return self._api.permute_dims(a, permutation)
     */
    return _api.permute_dims(a, permutation);
}

int ArrayApiBlockBackend::trace_full(const int & a) {
    /* CHECKME: converted from following python code:
     * shape = a.shape
     * num_trace = len(shape) // 2
     * trace_dim = np.prod(shape[:num_trace])
     * perm = [*range(num_trace), *reversed(range(num_trace, 2 * num_trace))]
     * a = self._api.reshape(self._api.permute_dims(a, perm), (trace_dim, trace_dim))
     * res = self._api.linalg.trace(a)
     * # performs trace along last two axes
     * return self.item(res)
     */
    auto /* CHECKME: type? */ shape = a.shape;
    auto /* CHECKME: type? */ num_trace = len(shape) / 2;
    auto /* CHECKME: type? */ trace_dim = np.prod(shape[std::slice(0, num_trace, 1)]);
    auto /* CHECKME: type? */ perm = {/* FIXME: Starred: *range(num_trace) */, /* FIXME: Starred: *reversed(range(num_trace, 2 * num_trace)) */};
    a = _api.reshape(_api.permute_dims(a, perm), std::make_tuple(trace_dim, trace_dim));
    auto /* CHECKME: type? */ res = _api.linalg.trace(a);
    /* performs trace along last two axes */
    return item(res);
}

int ArrayApiBlockBackend::trace_partial(const int & a, const int & idcs1, const int & idcs2, const int & remaining_idcs) {
    /* CHECKME: converted from following python code:
     * a = self._api.permute_dims(a, remaining + idcs1 + idcs2)
     * trace_dim = np.prod(a.shape[len(remaining) : len(remaining) + len(idcs1)])
     * a = self._api.reshape(a, (-1, trace_dim, trace_dim))
     * return self._api.linalg.trace(a)
     */
    a = _api.permute_dims(a, remaining + idcs1 + idcs2);
    auto /* CHECKME: type? */ trace_dim = np.prod(a.shape[std::slice(len(remaining), (len(remaining) + len(idcs1) - len(remaining)), 1)]);
    a = _api.reshape(a, std::make_tuple(-1, trace_dim, trace_dim));
    return _api.linalg.trace(a);
}

int ArrayApiBlockBackend::conj(const int & a) {
    /* CHECKME: converted from following python code:
     * return self._api.conj(a)
     */
    return _api.conj(a);
}

int ArrayApiBlockBackend::angle(const int & a) {
    /* CHECKME: converted from following python code:
     * raise NotImplementedError(f'{self} does not support angle.')
     */
    throw std::logic_error(std::format("{} does not support angle.", self  /* FIXME: standalone self reference */));
}

int ArrayApiBlockBackend::real(const int & a) {
    /* CHECKME: converted from following python code:
     * return self._api.real(a)
     */
    return _api.real(a);
}

int ArrayApiBlockBackend::real_if_close(const int & a, int tol) {
    /* CHECKME: converted from following python code:
     * raise NotImplementedError(f'{self} does not support real_if_close.')
     */
    throw std::logic_error(std::format("{} does not support real_if_close.", self  /* FIXME: standalone self reference */));
}

int ArrayApiBlockBackend::sqrt(const int & a) {
    /* CHECKME: converted from following python code:
     * raise NotImplementedError(f'{self} does not support sqrt.')
     */
    throw std::logic_error(std::format("{} does not support sqrt.", self  /* FIXME: standalone self reference */));
}

int ArrayApiBlockBackend::imag(const int & a) {
    /* CHECKME: converted from following python code:
     * return self._api.imag(a)
     */
    return _api.imag(a);
}

int ArrayApiBlockBackend::exp(const int & a) {
    /* CHECKME: converted from following python code:
     * return self._api.exp(a)
     */
    return _api.exp(a);
}

int ArrayApiBlockBackend::log(const int & a) {
    /* CHECKME: converted from following python code:
     * return self._api.log(a)
     */
    return _api.log(a);
}

bool ArrayApiBlockBackend::allclose(const int & a, const int & b, int rtol, int atol) {
    /* CHECKME: converted from following python code:
     * res = self._api.all(self._api.abs(a - b) <= (atol + rtol * self._api.abs(b)))
     * return self.item(res)
     */
    auto /* CHECKME: type? */ res = _api.all(_api.abs(a - b) <= atol + rtol * _api.abs(b));
    return item(res);
}

int ArrayApiBlockBackend::squeeze_axes(const int & a, const int & idcs) {
    /* CHECKME: converted from following python code:
     * return self._api.squeeze(a, tuple(idcs))
     */
    return _api.squeeze(a, tuple(idcs));
}

int ArrayApiBlockBackend::add_axis(const int & a, int pos) {
    /* CHECKME: converted from following python code:
     * return self._api.expand_dims(a, axis=pos)
     */
    return _api.expand_dims(a, py::arg({keyword.key}) = val) /* CHECKME: keywords ['axis'] */;
}

int ArrayApiBlockBackend::norm(const int & a, int order, int axis) {
    /* CHECKME: converted from following python code:
     * res = self._api.linalg.vector_norm(a, axis=axis, ord=order)
     *         if axis is None:
     *             res = self.item(res)
     * return res
     */
    auto /* CHECKME: type? */ res = _api.linalg.vector_norm(a, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['axis', 'ord'] */;
    if (axis == py::none()) {
        res = item(res);
    }
    return res;
}

int ArrayApiBlockBackend::max(const int & a) {
    /* CHECKME: converted from following python code:
     * return self.item(self._api.max(a))
     */
    return item(_api.max(a));
}

int ArrayApiBlockBackend::max_abs(const int & a) {
    /* CHECKME: converted from following python code:
     * return self.item(self._api.max(self._api.abs(a)))
     */
    return item(_api.max(_api.abs(a)));
}

int ArrayApiBlockBackend::min(const int & a) {
    /* CHECKME: converted from following python code:
     * return self.item(self._api.min(a))
     */
    return item(_api.min(a));
}

int ArrayApiBlockBackend::reshape(const int & a, const int & shape) {
    /* CHECKME: converted from following python code:
     * return self._api.reshape(a, shape)
     */
    return _api.reshape(a, shape);
}

int ArrayApiBlockBackend::matrix_dot(const int & a, const int & b) {
    /* CHECKME: converted from following python code:
     * return self._api.matmul(a, b)
     */
    return _api.matmul(a, b);
}

int ArrayApiBlockBackend::matrix_svd(const int & a, std::optional<std::string> algorithm) {
    /* CHECKME: converted from following python code:
     *         if algorithm is None:
     *             algorithm = 'default'
     *         if algorithm != 'default':
     *             raise ValueError(f'SVD algorithm not supported: {algorithm}')
     * self._api.linalg.svd(a, full_matrices=False)
     */
    if (algorithm == py::none()) {
        algorithm = "default";
    }
    if (algorithm != "default") {
        throw std::invalid_argument(std::format("SVD algorithm not supported: {}", algorithm));
    }
    _api.linalg.svd(a, py::arg({keyword.key}) = val) /* CHECKME: keywords ['full_matrices'] */;
}

/// Cannot specify algorithms through the array API.
const int & ArrayApiBlockBackend::possible_svd_algorithms() {
    /* CHECKME: converted from following python code:
     * return ['default']
     */
    return {"default"};
}

int ArrayApiBlockBackend::matrix_qr(const int & a, bool full) {
    /* CHECKME: converted from following python code:
     * return self._api.linalg.qr(a, mode='complete' if full else 'reduced')
     */
    return _api.linalg.qr(a, py::arg({keyword.key}) = val) /* CHECKME: keywords ['mode'] */;
}

int ArrayApiBlockBackend::matrix_exp(const int & matrix) {
    /* CHECKME: converted from following python code:
     * raise NotImplementedError(f'{self} does not support matrix_exp.')
     */
    throw std::logic_error(std::format("{} does not support matrix_exp.", self  /* FIXME: standalone self reference */));
}

int ArrayApiBlockBackend::random_uniform(const int & dims, int dtype, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     * # API does not specify random generation, so we generate in numpy and convert
     * res = np.random.uniform(-1, 1, size=dims)
     *         if not dtype.is_real:
     *             res += 1.0j * np.random.uniform(-1, 1, size=dims)
     * return self._api.asarray(res, device=device)
     */
    // API does not specify random generation, so we generate in numpy and convert
    auto /* CHECKME: type? */ res = np.random.uniform(-1, 1, py::arg({keyword.key}) = val) /* CHECKME: keywords ['size'] */;
    if (!dtype.is_real) {
        res += 1i * np.random.uniform(-1, 1, py::arg({keyword.key}) = val) /* CHECKME: keywords ['size'] */;
    }
    return _api.asarray(res, py::arg({keyword.key}) = val) /* CHECKME: keywords ['device'] */;
}

int ArrayApiBlockBackend::random_normal(const int & dims, int dtype, int sigma, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     * res = np.random.normal(loc=0, scale=sigma, size=dims)
     *         if not dtype.is_real:
     *             res += 1.0j * np.random.normal(loc=0, scale=sigma, size=dims)
     * return self._api.asarray(res, device=device)
     */
    auto /* CHECKME: type? */ res = np.random.normal(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['loc', 'scale', 'size'] */;
    if (!dtype.is_real) {
        res += 1i * np.random.normal(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['loc', 'scale', 'size'] */;
    }
    return _api.asarray(res, py::arg({keyword.key}) = val) /* CHECKME: keywords ['device'] */;
}

int ArrayApiBlockBackend::block_from_numpy(const int & a, int dtype, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     * return self._api.asarray(a, dtype=self.backend_dtype_map[dtype], device=device)
     */
    return _api.asarray(a, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype', 'device'] */;
}

int ArrayApiBlockBackend::zeros(const int & shape, int dtype, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     * return self._api.zeros(shape, dtype=self.backend_dtype_map[dtype], device=device)
     */
    return _api.zeros(shape, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype', 'device'] */;
}

int ArrayApiBlockBackend::ones_block(const int & shape, int dtype, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     * return self._api.ones(shape, dtype=self.backend_dtype_map[dtype], device=device)
     */
    return _api.ones(shape, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype', 'device'] */;
}

int ArrayApiBlockBackend::eye_matrix(int dim, int dtype, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     * return self._api.eye(dim, dtype=self.backend_dtype_map[dtype], device=device)
     */
    return _api.eye(dim, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype', 'device'] */;
}

int ArrayApiBlockBackend::kron(const int & a, const int & b) {
    /* CHECKME: converted from following python code:
     * # is this really not in the API...?
     * # should be able to do this via mul and reshape?
     * raise NotImplementedError(f'{self} does not support kron.')
     */
    // is this really not in the API...?
    // should be able to do this via mul and reshape?
    throw std::logic_error(std::format("{} does not support kron.", self  /* FIXME: standalone self reference */));
}

int ArrayApiBlockBackend::get_block_element(const int & a, const int & idcs) {
    /* CHECKME: converted from following python code:
     * return self.item(a[tuple(idcs)])
     */
    return item(a[tuple(idcs)]);
}

std::string ArrayApiBlockBackend::get_device(BlockPtr a) {
    /* CHECKME: converted from following python code:
     * return self.as_device(a.device)
     */
    return as_device(a.device);
}

int ArrayApiBlockBackend::get_diagonal(const int & a, int tol) {
    /* CHECKME: converted from following python code:
     * assert a.ndim == 2
     * res = self._api.diagonal(a)
     *         if tol is not None:
     *             if not self.allclose(a, self.block_from_diagonal(res), rtol=0, atol=tol):
     *                 raise ValueError('Not a diagonal block.')
     * return res
     */
    /* FIXME: Assert: assert a.ndim == 2 */
    auto /* CHECKME: type? */ res = _api.diagonal(a);
    if (tol != py::none()) {
        if (!(allclose(a, block_from_diagonal(res), py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['rtol', 'atol'] */)) {
            throw std::invalid_argument("Not a diagonal block.");
        }
    }
    return res;
}

int ArrayApiBlockBackend::block_from_diagonal(const int & diag) {
    /* CHECKME: converted from following python code:
     * raise NotImplementedError(f'{self} does not support block_from_diagonal.')
     */
    throw std::logic_error(std::format("{} does not support block_from_diagonal.", self  /* FIXME: standalone self reference */));
}

int ArrayApiBlockBackend::block_from_mask(const int & mask, int dtype) {
    /* CHECKME: converted from following python code:
     * raise NotImplementedError(f'{self} does not support block_from_mask.')
     */
    throw std::logic_error(std::format("{} does not support block_from_mask.", self  /* FIXME: standalone self reference */));
}

int ArrayApiBlockBackend::sum(const int & a, int ax) {
    /* CHECKME: converted from following python code:
     * return self._api.sum(a, axis=ax)
     */
    return _api.sum(a, py::arg({keyword.key}) = val) /* CHECKME: keywords ['axis'] */;
}

int ArrayApiBlockBackend::sum_all(const int & a) {
    /* CHECKME: converted from following python code:
     * return self.item(self._api.sum(a))
     */
    return item(_api.sum(a));
}

int ArrayApiBlockBackend::eigh(const int & block, std::optional<std::string> sort) {
    /* CHECKME: converted from following python code:
     * w, v = self._api.linalg.eigh(block)
     *         if sort is not None:
     *             perm = self.argsort(w, sort)
     *             w = w[perm]
     *             v = v[:, perm]
     * return w, v
     */
    std::make_tuple(w, v) = _api.linalg.eigh(block);
    if (sort != py::none()) {
        auto /* CHECKME: type? */ perm = argsort(w, sort);
        auto /* CHECKME: type? */ w = w[perm];
        auto /* CHECKME: type? */ v = /* Multidimensional slice using std::gslice
 * NOTE: Requires v_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   v_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
v[std::gslice(perm * v_strides[1], std::valarray<std::size_t>{v.shape(0), 1}, std::valarray<std::size_t>{v_strides[0], v_strides[1]})];
    }
    return std::make_tuple(w, v);
}

int ArrayApiBlockBackend::eigvalsh(const int & block, std::optional<std::string> sort) {
    /* CHECKME: converted from following python code:
     * w = self._api.linalg.eigvalsh(block)
     *         if sort is not None:
     *             perm = self.argsort(w, sort)
     *             w = w[perm]
     * return w
     */
    auto /* CHECKME: type? */ w = _api.linalg.eigvalsh(block);
    if (sort != py::none()) {
        auto /* CHECKME: type? */ perm = argsort(w, sort);
        w = w[perm];
    }
    return w;
}

int ArrayApiBlockBackend::abs_argmax(const int & block) {
    /* CHECKME: converted from following python code:
     * flat_idx = self._api.argmax(self._api.abs(block))
     * # OPTIMIZE numpy has np.unravel_indices. no analogue here?
     * idcs = []
     *         for dim in reversed(block.shape):
     *             flat_idx, idx = divmod(flat_idx, dim)
     *             idcs.append(idx)
     * return idcs
     */
    auto /* CHECKME: type? */ flat_idx = _api.argmax(_api.abs(block));
    // OPTIMIZE numpy has np.unravel_indices. no analogue here?
    auto /* CHECKME: type? */ idcs = {} /* FIXME: empty list */;
    /* FIXME: for loop:         for dim in reversed(block.shape):
            flat_idx, idx = divmod(flat_idx, dim)
            idcs.append(idx) */
    return idcs;
}

int ArrayApiBlockBackend::_argsort(const int & block, int axis) {
    /* CHECKME: converted from following python code:
     * return self._api.argsort(block, axis=axis)
     */
    return _api.argsort(block, py::arg({keyword.key}) = val) /* CHECKME: keywords ['axis'] */;
}

int ArrayApiBlockBackend::enlarge_leg(const int & block, const int & mask, int axis) {
    /* CHECKME: converted from following python code:
     * shape = list(block.shape)
     * shape[axis] = len(mask)
     * res = self._api.zeros(shape, dtype=block.dtype)
     * idcs = [slice(None, None, None)] * len(shape)
     * idcs[axis] = mask
     * res[idcs] = self.copy_block(block)
     * # OPTIMIZE copy needed?
     * return res
     */
    auto /* CHECKME: type? */ shape = list(block.shape);
    shape[axis] = len(mask);
    auto /* CHECKME: type? */ res = _api.zeros(shape, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */;
    auto /* CHECKME: type? */ idcs = {slice(py::none(), py::none(), py::none())} * len(shape);
    idcs[axis] = mask;
    res[idcs] = copy_block(block);
    /* OPTIMIZE copy needed? */
    return res;
}

int ArrayApiBlockBackend::stable_log(const int & block, int cutoff) {
    /* CHECKME: converted from following python code:
     * return self._api.where(block > cutoff, self._api.log(block), 0.0)
     */
    return _api.where(block > cutoff, _api.log(block), 0.0);
}

int ArrayApiBlockBackend::as_scalar(int z) {
    // FIXME: implement
}

std::shared_ptr<ArrayApiBlockBackend> ArrayApiBlockBackend::from_hdf5(
    int hdf5_loader,
    int h5gr,
    const std::string & subpath
) {
    // FIXME: implement
}

int ArrayApiBlockBackend::api() {
    // FIXME: implement
}

std::string ArrayApiBlockBackend::get_backend_name() {
    // FIXME: implement
}

int ArrayApiBlockBackend::apply_leg_permutations(const int & block, const int ) {
    // FIXME: implement
}

int ArrayApiBlockBackend::abs(const int & a) {
    // FIXME: implement
}

int ArrayApiBlockBackend::apply_mask(const int & block, const int & mask, int ax) {
    // FIXME: implement
}

int ArrayApiBlockBackend::cutoff_inverse(const int & a, int cutoff) {
    // FIXME: implement
}

int ArrayApiBlockBackend::scale_axis(const int & block, const int & factors, int axis) {
    // FIXME: implement
}

int ArrayApiBlockBackend::tile(const int & a, int repeats) {
    // FIXME: implement
}

int ArrayApiBlockBackend::multiply_blocks(const int & a, const int & b) {
    // FIXME: implement
}

bool ArrayApiBlockBackend::is_correct_block_type(const int & block) {
    // FIXME: implement
}

int ArrayApiBlockBackend::dtype_from_api(int api_dtype) {
    // FIXME: implement
}

int ArrayApiBlockBackend::dtype_to_api(int dtype) {
    // FIXME: implement
}

const int * ArrayApiBlockBackend::ptr(const int & b) {
    // FIXME: implement
}

int ArrayApiBlockBackend::obj(const int & b) {
    // FIXME: implement
}

int ArrayApiBlockBackend::wrap(int arr) {
    // FIXME: implement
}
