#include <cyten/block_backend/torch.h>

namespace cyten {

// TorchBlockBackend definitions will be generated / filled below.

// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_definition --py-name TorchBlockBackend --header-file include/cyten/block_backend/torch.h --src-file src/block_backend/torch.cpp

using std::complex_literals::operatori; // 1.i for complex numbers
TorchBlockBackend::TorchBlockBackend(const std::string & default_device) {
    /* CHECKME: converted from following python code:
     * global torch_module
     *         try:
     *             import torch
     *         except ImportError as e:
     *             raise ImportError('Could not import torch. Use a different backend or install torch.') from e
     * torch_module = torch
     *         self.cyten_dtype_map = {
     *             torch.float32: Dtype.float32,
     *             torch.float64: Dtype.float64,
     *             torch.complex64: Dtype.complex64,
     *             torch.complex128: Dtype.complex128,
     *             torch.bool: Dtype.bool,
     *             None: None,
     *         }
     *         self.backend_dtype_map = {
     *             Dtype.float32: torch.float32,
     *             Dtype.float64: torch.float64,
     *             Dtype.complex64: torch.complex64,
     *             Dtype.complex128: torch.complex128,
     *             Dtype.bool: torch.bool,
     *             None: None,
     *         }
     * self.BlockCls = torch.Tensor
     * super().__init__(default_device=default_device)
     */
    /* FIXME: Global: global torch_module */
    /* FIXME: Try:         try:
            import torch
        except ImportError as e:
            raise ImportError('Could not import torch. Use a different backend or install torch.') from e */
    auto /* CHECKME: type? */ torch_module = torch;
    cyten_dtype_map = {{torch.float32, Dtype.float32}, {torch.float64, Dtype.float64}, {torch.complex64, Dtype.complex64}, {torch.complex128, Dtype.complex128}, {torch.bool, Dtype.bool}, {py::none(), py::none()}};
    backend_dtype_map = {{Dtype.float32, torch.float32}, {Dtype.float64, torch.float64}, {Dtype.complex64, torch.complex64}, {Dtype.complex128, torch.complex128}, {Dtype.bool, torch.bool}, {py::none(), py::none()}};
    BlockCls = torch.Tensor;
    super().__init__(py::arg({keyword.key}) = val) /* CHECKME: keywords ['default_device'] */;
}

int TorchBlockBackend::abs(const int & a) {
    /* CHECKME: converted from following python code:
     * return torch_module.abs(a)
     */
    return torch_module.abs(a);
}

int TorchBlockBackend::as_block(int a, int dtype, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     * # TODO good error handling if a device does not support a given dtype
     *         if isinstance(a, Block):
     *             a = a.to_numpy()
     * block = torch_module.as_tensor(a, dtype=self.backend_dtype_map[dtype], device=self.as_device(device))
     *         if dtype != Dtype.bool:
     *             block = 1.0 * block  # force int to float.
     * return block
     */
    // TODO good error handling if a device does not support a given dtype
    if (isinstance(a, Block)) {
        a = a.to_numpy();
    }
    auto /* CHECKME: type? */ block = torch_module.as_tensor(a, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype', 'device'] */;
    if (dtype != Dtype.bool) {
        block = 1.0 * block;
        /* force int to float. */
    }
    return block;
}

std::string TorchBlockBackend::as_device(std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     *         if device is None:
     *             device = self.default_device
     * res = torch_module.device(device)
     *         if res.index is None:
     *             res = torch_module.device(device, index=0)
     * return str(res)
     */
    if (device == py::none()) {
        device = default_device;
    }
    auto /* CHECKME: type? */ res = torch_module.device(device);
    if (res.index == py::none()) {
        res = torch_module.device(device, py::arg({keyword.key}) = val) /* CHECKME: keywords ['index'] */;
    }
    return str(res);
}

int TorchBlockBackend::abs_argmax(const int & block) {
    /* CHECKME: converted from following python code:
     * flat_idx = torch_module.argmax(torch_module.abs(block))
     * # OPTIMIZE numpy has np.unravel_indices. no analogue here?
     * idcs = []
     *         for dim in reversed(block.shape):
     *             flat_idx, idx = divmod(flat_idx, dim)
     *             idcs.append(idx)
     * return idcs
     */
    auto /* CHECKME: type? */ flat_idx = torch_module.argmax(torch_module.abs(block));
    // OPTIMIZE numpy has np.unravel_indices. no analogue here?
    auto /* CHECKME: type? */ idcs = {} /* FIXME: empty list */;
    /* FIXME: for loop:         for dim in reversed(block.shape):
            flat_idx, idx = divmod(flat_idx, dim)
            idcs.append(idx) */
    return idcs;
}

int TorchBlockBackend::add_axis(const int & a, int pos) {
    /* CHECKME: converted from following python code:
     * return torch_module.unsqueeze(a, pos)
     */
    return torch_module.unsqueeze(a, pos);
}

bool TorchBlockBackend::all(const int & a) {
    /* CHECKME: converted from following python code:
     * return torch_module.all(a)
     */
    return torch_module.all(a);
}

bool TorchBlockBackend::allclose(const int & a, const int & b, int rtol, int atol) {
    /* CHECKME: converted from following python code:
     * a = torch_module.as_tensor(a)
     * b = torch_module.as_tensor(b)
     * a, b = self.to_same_dtype(a, b)
     * return torch_module.allclose(a, b, rtol=rtol, atol=atol)
     */
    a = torch_module.as_tensor(a);
    b = torch_module.as_tensor(b);
    std::make_tuple(a, b) = to_same_dtype(a, b);
    return torch_module.allclose(a, b, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['rtol', 'atol'] */;
}

int TorchBlockBackend::angle(const int & a) {
    /* CHECKME: converted from following python code:
     * return torch_module.angle(a)
     */
    return torch_module.angle(a);
}

bool TorchBlockBackend::any(const int & a) {
    /* CHECKME: converted from following python code:
     * return torch_module.any(a)
     */
    return torch_module.any(a);
}

int TorchBlockBackend::_argsort(const int & block, int axis) {
    /* CHECKME: converted from following python code:
     * return torch_module.argsort(block, dim=axis)
     */
    return torch_module.argsort(block, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dim'] */;
}

int TorchBlockBackend::conj(const int & a) {
    /* CHECKME: converted from following python code:
     * return torch_module.conj(a)
     */
    return torch_module.conj(a);
}

int TorchBlockBackend::copy_block(const int & a, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     * res = a.clone().detach()
     *         if device is not None:
     *             res = res.to(self.as_device(device))
     * return res
     */
    auto /* CHECKME: type? */ res = a.clone().detach();
    if (device != py::none()) {
        res = res.to(as_device(device));
    }
    return res;
}

Dtype TorchBlockBackend::get_dtype(BlockPtr a) {
    /* CHECKME: converted from following python code:
     * return self.cyten_dtype_map[a.dtype]
     */
    return cyten_dtype_map[a.dtype];
}

int TorchBlockBackend::eigh(const int & block, std::optional<std::string> sort) {
    /* CHECKME: converted from following python code:
     * w, v = torch_module.linalg.eigh(block)
     *         if sort is not None:
     *             perm = self.argsort(w, sort)
     *             w = w[perm]
     *             v = v[:, perm]
     * return w, v
     */
    std::make_tuple(w, v) = torch_module.linalg.eigh(block);
    if (sort != py::none()) {
        auto /* CHECKME: type? */ perm = argsort(w, sort);
        auto /* CHECKME: type? */ w = w[perm];
        auto /* CHECKME: type? */ v = /* Multidimensional slice using std::gslice
 * NOTE: Requires v_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   v_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
v[std::gslice(perm * v_strides[1], std::valarray<std::size_t>{v.shape(0), 1}, std::valarray<std::size_t>{v_strides[0], v_strides[1]})];
    }
    return std::make_tuple(w, v);
}

int TorchBlockBackend::eigvalsh(const int & block, std::optional<std::string> sort) {
    /* CHECKME: converted from following python code:
     * w = torch_module.linalg.eigvalsh(block)
     *         if sort is not None:
     *             perm = self.argsort(w, sort)
     *             w = w[perm]
     * return w
     */
    auto /* CHECKME: type? */ w = torch_module.linalg.eigvalsh(block);
    if (sort != py::none()) {
        auto /* CHECKME: type? */ perm = argsort(w, sort);
        w = w[perm];
    }
    return w;
}

int TorchBlockBackend::enlarge_leg(const int & block, const int & mask, int axis) {
    /* CHECKME: converted from following python code:
     * shape = list(block.shape)
     * shape[axis] = len(mask)
     * res = torch_module.zeros(shape, dtype=block.dtype, device=block.device)
     * idcs = [slice(None, None, None)] * len(shape)
     * idcs[axis] = mask
     * res[tuple(idcs)] = self.copy_block(block)
     * # OPTIMIZE copy needed?
     * return res
     */
    auto /* CHECKME: type? */ shape = list(block.shape);
    shape[axis] = len(mask);
    auto /* CHECKME: type? */ res = torch_module.zeros(shape, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype', 'device'] */;
    auto /* CHECKME: type? */ idcs = {slice(py::none(), py::none(), py::none())} * len(shape);
    idcs[axis] = mask;
    res[tuple(idcs)] = copy_block(block);
    /* OPTIMIZE copy needed? */
    return res;
}

int TorchBlockBackend::exp(const int & a) {
    /* CHECKME: converted from following python code:
     * return torch_module.exp(a)
     */
    return torch_module.exp(a);
}

int TorchBlockBackend::block_from_diagonal(const int & diag) {
    /* CHECKME: converted from following python code:
     * return torch_module.diag(diag)
     */
    return torch_module.diag(diag);
}

int TorchBlockBackend::block_from_mask(const int & mask, int dtype) {
    /* CHECKME: converted from following python code:
     * (M,) = mask.shape
     * N = torch_module.sum(mask)
     * res = torch_module.zeros((N, M), dtype=self.backend_dtype_map[dtype])
     * res[torch_module.arange(N), mask] = 1
     * return res
     */
    std::make_tuple(M) = mask.shape;
    auto /* CHECKME: type? */ N = torch_module.sum(mask);
    auto /* CHECKME: type? */ res = torch_module.zeros(std::make_tuple(N, M), py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */;
    /* Multidimensional slice using std::gslice
 * NOTE: Requires res_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   res_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
res[std::gslice(torch_module.arange(N) * res_strides[0] + mask * res_strides[1], std::valarray<std::size_t>{1, 1}, std::valarray<std::size_t>{res_strides[0], res_strides[1]})] = 1;
    return res;
}

int TorchBlockBackend::block_from_numpy(const int & a, int dtype, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     * return torch_module.tensor(a, device=self.as_device(device), dtype=self.backend_dtype_map[dtype])
     */
    return torch_module.tensor(a, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['device', 'dtype'] */;
}

std::string TorchBlockBackend::get_device(BlockPtr a) {
    /* CHECKME: converted from following python code:
     * res = a.device
     *         if res.index is None:
     *             res = torch_module.device(res.type, index=0)
     * return str(res)
     */
    auto /* CHECKME: type? */ res = a.device;
    if (res.index == py::none()) {
        res = torch_module.device(res.type, py::arg({keyword.key}) = val) /* CHECKME: keywords ['index'] */;
    }
    return str(res);
}

int TorchBlockBackend::get_diagonal(const int & a, int tol) {
    /* CHECKME: converted from following python code:
     * res = torch_module.diagonal(a)
     *         if tol is not None:
     *             if not torch_module.allclose(res, torch_module.diag(a), atol=tol):
     *                 raise ValueError('Not a diagonal block.')
     * return res
     */
    auto /* CHECKME: type? */ res = torch_module.diagonal(a);
    if (tol != py::none()) {
        if (!(torch_module.allclose(res, torch_module.diag(a), py::arg({keyword.key}) = val) /* CHECKME: keywords ['atol'] */)) {
            throw std::invalid_argument("Not a diagonal block.");
        }
    }
    return res;
}

int TorchBlockBackend::imag(const int & a) {
    /* CHECKME: converted from following python code:
     *         if not a.dtype.is_complex:
     *             return torch_module.zeros_like(a)
     * return torch_module.imag(a)
     */
    if (!a.dtype.is_complex) {
        return torch_module.zeros_like(a);
    }
    return torch_module.imag(a);
}

int TorchBlockBackend::inner(const int & a, const int & b, bool do_dagger) {
    /* CHECKME: converted from following python code:
     * a, b = self.to_same_dtype(a, b, at_least=torch_module.float16)
     *         if do_dagger:
     *             res = torch_module.tensordot(torch_module.conj(a), b, a.ndim)
     *         else:
     *             res = torch_module.tensordot(a, b, [tuple(range(a.ndim)), tuple(reversed(range(a.ndim)))])
     * return self.item(res)
     */
    std::make_tuple(a, b) = to_same_dtype(a, b, py::arg({keyword.key}) = val) /* CHECKME: keywords ['at_least'] */;
    if (do_dagger) {
        auto /* CHECKME: type? */ res = torch_module.tensordot(torch_module.conj(a), b, a.ndim);
    } else {
        res = torch_module.tensordot(a, b, {tuple(range(a.ndim)), tuple(reversed(range(a.ndim)))});
    }
    return item(res);
}

int TorchBlockBackend::item(const int & a) {
    /* CHECKME: converted from following python code:
     *         if a.dtype.is_complex:
     *             return complex(a)
     *         else:
     *             return float(a)
     */
    if (a.dtype.is_complex) {
        return complex(a);
    } else {
        return float(a);
    }
}

int TorchBlockBackend::kron(const int & a, const int & b) {
    /* CHECKME: converted from following python code:
     * a, b = self.to_same_dtype(a, b)
     * return torch_module.kron(a, b)
     */
    std::make_tuple(a, b) = to_same_dtype(a, b);
    return torch_module.kron(a, b);
}

int TorchBlockBackend::log(const int & a) {
    /* CHECKME: converted from following python code:
     * return torch_module.log(a)
     */
    return torch_module.log(a);
}

int TorchBlockBackend::max(const int & a) {
    /* CHECKME: converted from following python code:
     * return self.item(torch_module.max(a))
     */
    return item(torch_module.max(a));
}

int TorchBlockBackend::max_abs(const int & a) {
    /* CHECKME: converted from following python code:
     * return self.item(torch_module.max(torch_module.abs(a)))
     */
    return item(torch_module.max(torch_module.abs(a)));
}

int TorchBlockBackend::min(const int & a) {
    /* CHECKME: converted from following python code:
     * return self.item(torch_module.min(a))
     */
    return item(torch_module.min(a));
}

int TorchBlockBackend::norm(const int & a, int order, int axis) {
    /* CHECKME: converted from following python code:
     * res = torch_module.linalg.vector_norm(a, ord=order, dim=axis)
     *         if axis is None:
     *             res = self.item(res)
     * return res
     */
    auto /* CHECKME: type? */ res = torch_module.linalg.vector_norm(a, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['ord', 'dim'] */;
    if (axis == py::none()) {
        res = item(res);
    }
    return res;
}

int TorchBlockBackend::outer(const int & a, const int & b) {
    /* CHECKME: converted from following python code:
     * a, b = self.to_same_dtype(a, b, at_least=torch_module.float16)
     * return torch_module.tensordot(a, b, ([], []))
     */
    std::make_tuple(a, b) = to_same_dtype(a, b, py::arg({keyword.key}) = val) /* CHECKME: keywords ['at_least'] */;
    return torch_module.tensordot(a, b, std::make_tuple({} /* FIXME: empty list */, {} /* FIXME: empty list */));
}

int TorchBlockBackend::permute_axes(const int & a, const int & permutation) {
    /* CHECKME: converted from following python code:
     * res = torch_module.permute(a, permutation)
     * # OPTIMIZE copy needed? permute says its a view...
     * res = self.copy_block(res)
     * return res
     */
    auto /* CHECKME: type? */ res = torch_module.permute(a, permutation);
    // OPTIMIZE copy needed? permute says its a view...
    res = copy_block(res);
    return res;
}

int TorchBlockBackend::random_uniform(const int & dims, int dtype, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     * # rand samples between 0 and 1; we want to sample between -1 and 1
     * offset = -1
     *         if dtype.is_complex:
     *             offset -= 1j
     * return offset + 2 * torch_module.rand(*dims, dtype=self.backend_dtype_map[dtype], device=self.as_device(device))
     */
    // rand samples between 0 and 1; we want to sample between -1 and 1
    auto /* CHECKME: type? */ offset = -1;
    if (dtype.is_complex) {
        offset -= 1i;
    }
    return offset + 2 * torch_module.rand(/* FIXME: Starred: *dims */, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype', 'device'] */;
}

int TorchBlockBackend::random_normal(const int & dims, int dtype, int sigma, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     * # OPTIMIZE Note that if device is CUDA, this function synchronizes the device with the CPU
     * mean = torch_module.zeros(size=dims, dtype=self.backend_dtype_map[dtype], device=self.as_device(device))
     * # avoid complex dtype in std (leads to error in torch_module.normal)
     * # dtype of result == dtype of mean
     * std = sigma * torch_module.ones_like(mean, device=device, dtype=torch_module.float64)
     * return torch_module.normal(mean, std)
     */
    // OPTIMIZE Note that if device is CUDA, this function synchronizes the device with the CPU
    auto /* CHECKME: type? */ mean = torch_module.zeros(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['size', 'dtype', 'device'] */;
    // avoid complex dtype in std (leads to error in torch_module.normal)
    // dtype of result == dtype of mean
    auto /* CHECKME: type? */ std = sigma * torch_module.ones_like(mean, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['device', 'dtype'] */;
    return torch_module.normal(mean, std);
}

int TorchBlockBackend::real(const int & a) {
    /* CHECKME: converted from following python code:
     * return torch_module.real(a)
     */
    return torch_module.real(a);
}

int TorchBlockBackend::real_if_close(const int & a, int tol) {
    /* CHECKME: converted from following python code:
     * eps = 2.2204460492503131e-16
     * # TODO make it actually depend on the dtype!!
     *         if torch_module.all(torch_module.abs(self.imag(a)) < tol * eps):
     *             a = torch_module.real(a)
     * return a
     */
    auto /* CHECKME: type? */ eps = 2.220446049250313e-16;
    /* TODO make it actually depend on the dtype!! */
    if (torch_module.all(torch_module.abs(imag(a)) < tol * eps)) {
        a = torch_module.real(a);
    }
    return a;
}

int TorchBlockBackend::tile(const int & a, int repeats) {
    /* CHECKME: converted from following python code:
     * return a.repeat(repeats)
     */
    return a.repeat(repeats);
}

int TorchBlockBackend::_block_repr_lines(const int & a, const std::string & indent, int max_width, int max_lines) {
    /* CHECKME: converted from following python code:
     * torch_module.set_printoptions(linewidth=max_width - len(indent))
     * lines = [f'{indent}{line}' for line in repr(a).split('\n')]
     * torch_module.set_printoptions(profile='default')
     *         if len(lines) > max_lines:
     *             first = (max_lines - 1) // 2
     *             last = max_lines - 1 - first
     *             lines = lines[:first] + [f'{indent}...'] + lines[-last:]
     * return lines
     */
    torch_module.set_printoptions(py::arg({keyword.key}) = val) /* CHECKME: keywords ['linewidth'] */;
    auto /* CHECKME: type? */ lines = /* FIXME: ListComp: [f'{indent}{line}' for line in repr(a).split('\n')] */;
    torch_module.set_printoptions(py::arg({keyword.key}) = val) /* CHECKME: keywords ['profile'] */;
    if (len(lines) > max_lines) {
        auto /* CHECKME: type? */ first = max_lines - 1 / 2;
        auto /* CHECKME: type? */ last = max_lines - 1 - first;
        lines = lines[std::slice(0, first, 1)] + {std::format("{}...", indent)} + lines[std::slice(-last, (lines.size() - -last), 1)];
    }
    return lines;
}

int TorchBlockBackend::reshape(const int & a, const int & shape) {
    /* CHECKME: converted from following python code:
     * return torch_module.reshape(a, tuple(shape))
     */
    return torch_module.reshape(a, tuple(shape));
}

tuple_int_ TorchBlockBackend::get_shape(BlockPtr a) {
    /* CHECKME: converted from following python code:
     * return tuple(a.shape)
     */
    return tuple(a.shape);
}

int TorchBlockBackend::sqrt(const int & a) {
    /* CHECKME: converted from following python code:
     * return torch_module.sqrt(a)
     */
    return torch_module.sqrt(a);
}

int TorchBlockBackend::squeeze_axes(const int & a, const int & idcs) {
    /* CHECKME: converted from following python code:
     * idx = tuple(0 if ax in idcs else slice(None, None, None) for ax in range(len(a.shape)))
     * return a[idx]
     */
    auto /* CHECKME: type? */ idx = tuple(/* FIXME: GeneratorExp: (0 if ax in idcs else slice(None, None, None) for ax in range(len(a.shape))) */);
    return a[idx];
}

int TorchBlockBackend::stable_log(const int & block, int cutoff) {
    /* CHECKME: converted from following python code:
     * return torch_module.where(block > cutoff, torch_module.log(block), 0.0)
     */
    return torch_module.where(block > cutoff, torch_module.log(block), 0.0);
}

int TorchBlockBackend::sum(const int & a, int ax) {
    /* CHECKME: converted from following python code:
     * return torch_module.sum(a, ax)
     */
    return torch_module.sum(a, ax);
}

int TorchBlockBackend::sum_all(const int & a) {
    /* CHECKME: converted from following python code:
     * return self.item(torch_module.sum(a))
     */
    return item(torch_module.sum(a));
}

int TorchBlockBackend::tdot(const int & a, const int & b, const int & idcs_a, const int & idcs_b) {
    /* CHECKME: converted from following python code:
     * a, b = self.to_same_dtype(a, b, at_least=torch_module.float16)
     * return torch_module.tensordot(a, b, (idcs_a, idcs_b))
     */
    std::make_tuple(a, b) = to_same_dtype(a, b, py::arg({keyword.key}) = val) /* CHECKME: keywords ['at_least'] */;
    return torch_module.tensordot(a, b, std::make_tuple(idcs_a, idcs_b));
}

int TorchBlockBackend::to_dtype(const int & a, int dtype) {
    /* CHECKME: converted from following python code:
     * return a.type(self.backend_dtype_map[dtype])
     */
    return a.type(backend_dtype_map[dtype]);
}

int TorchBlockBackend::trace_full(const int & a) {
    /* CHECKME: converted from following python code:
     * num_trace = a.ndim // 2
     * trace_dim = prod(a.shape[:num_trace])
     * perm = [*range(num_trace), *reversed(range(num_trace, 2 * num_trace))]
     * a = torch_module.reshape(torch_module.permute(a, perm), (trace_dim, trace_dim))
     * return self.item(a.diagonal(offset=0, dim1=0, dim2=1).sum(0))
     */
    auto /* CHECKME: type? */ num_trace = a.ndim / 2;
    auto /* CHECKME: type? */ trace_dim = prod(a.shape[std::slice(0, num_trace, 1)]);
    auto /* CHECKME: type? */ perm = {/* FIXME: Starred: *range(num_trace) */, /* FIXME: Starred: *reversed(range(num_trace, 2 * num_trace)) */};
    a = torch_module.reshape(torch_module.permute(a, perm), std::make_tuple(trace_dim, trace_dim));
    return item(a.diagonal(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['offset', 'dim1', 'dim2'] */.sum(0));
}

int TorchBlockBackend::trace_partial(const int & a, const int & idcs1, const int & idcs2, const int & remaining_idcs) {
    /* CHECKME: converted from following python code:
     * a = torch_module.permute(a, remaining + idcs1 + idcs2)
     * trace_dim = int(prod(a.shape[len(remaining) : len(remaining) + len(idcs1)]))
     * a = torch_module.reshape(a, a.shape[: len(remaining)] + (trace_dim, trace_dim))
     * return a.diagonal(offset=0, dim1=-1, dim2=-2).sum(-1)
     */
    a = torch_module.permute(a, remaining + idcs1 + idcs2);
    auto /* CHECKME: type? */ trace_dim = int(prod(a.shape[std::slice(len(remaining), (len(remaining) + len(idcs1) - len(remaining)), 1)]));
    a = torch_module.reshape(a, a.shape[std::slice(0, len(remaining), 1)] + std::make_tuple(trace_dim, trace_dim));
    return a.diagonal(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['offset', 'dim1', 'dim2'] */.sum(-1);
}

int TorchBlockBackend::eye_matrix(int dim, int dtype, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     * return torch_module.eye(dim, dtype=self.backend_dtype_map[dtype], device=self.as_device(device))
     */
    return torch_module.eye(dim, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype', 'device'] */;
}

int TorchBlockBackend::get_block_element(const int & a, const int & idcs) {
    /* CHECKME: converted from following python code:
     * return self.item(a[tuple(idcs)])
     */
    return item(a[tuple(idcs)]);
}

int TorchBlockBackend::matrix_dot(const int & a, const int & b) {
    /* CHECKME: converted from following python code:
     * a, b = self.to_same_dtype(a, b)
     * return torch_module.matmul(a, b)
     */
    std::make_tuple(a, b) = to_same_dtype(a, b);
    return torch_module.matmul(a, b);
}

int TorchBlockBackend::matrix_exp(const int & matrix) {
    /* CHECKME: converted from following python code:
     * raise NotImplementedError(f'{self} does not support matrix_exp yet.')
     */
    throw std::logic_error(std::format("{} does not support matrix_exp yet.", self  /* FIXME: standalone self reference */));
}

int TorchBlockBackend::matrix_log(const int & matrix) {
    /* CHECKME: converted from following python code:
     * raise NotImplementedError(f'{self} does not support matrix_log yet.')
     */
    throw std::logic_error(std::format("{} does not support matrix_log yet.", self  /* FIXME: standalone self reference */));
}

int TorchBlockBackend::matrix_qr(const int & a, bool full) {
    /* CHECKME: converted from following python code:
     * return torch_module.linalg.qr(a, mode='complete' if full else 'reduced')
     */
    return torch_module.linalg.qr(a, py::arg({keyword.key}) = val) /* CHECKME: keywords ['mode'] */;
}

int TorchBlockBackend::matrix_svd(const int & a, std::optional<std::string> algorithm) {
    /* CHECKME: converted from following python code:
     *         if a.device.type == 'cuda':
     *             if algorithm is None:
     *                 algorithm = 'gesvd'
     *             assert algorithm in self.possible_svd_algorithms()
     *         else:
     *             if algorithm == 'gesvd':
     *                 algorithm = None
     *             if algorithm is not None:
     *                 msg = 'For torch, the algorithm keyword is only supported on CUDA hardware'
     *                 raise ValueError(msg)
     * U, S, V = torch_module.linalg.svd(a, full_matrices=False, driver=algorithm)
     * return U, S, V
     */
    if (a.device.type == "cuda") {
        if (algorithm == py::none()) {
            algorithm = "gesvd";
        }
        /* FIXME: Assert: assert algorithm in self.possible_svd_algorithms() */
    } else {
        if (algorithm == "gesvd") {
            algorithm = py::none();
        }
        if (algorithm != py::none()) {
            auto /* CHECKME: type? */ msg = "For torch, the algorithm keyword is only supported on CUDA hardware";
            throw std::invalid_argument(msg);
        }
    }
    std::make_tuple(U, S, V) = torch_module.linalg.svd(a, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['full_matrices', 'driver'] */;
    return std::make_tuple(U, S, V);
}

const int & TorchBlockBackend::possible_svd_algorithms() {
    /* CHECKME: converted from following python code:
     * return ['gesvdj', 'gesvda', 'gesvd']
     */
    return {"gesvdj", "gesvda", "gesvd"};
}

int TorchBlockBackend::ones_block(const int & shape, int dtype, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     * return torch_module.ones(list(shape), dtype=self.backend_dtype_map[dtype], device=self.as_device(device))
     */
    return torch_module.ones(list(shape), py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype', 'device'] */;
}

int TorchBlockBackend::to_same_dtype(const int & a, const int & b, int at_least) {
    /* CHECKME: converted from following python code:
     * # OPTIMIZE is there something built in to torch?
     * dtype = torch_module.promote_types(a.dtype, b.dtype)
     *         if at_least is not None:
     *             dtype = torch_module.promote_types(dtype, at_least)
     *         if a.dtype != dtype:
     *             a = torch_module.as_tensor(a, dtype=dtype)
     *         if b.dtype != dtype:
     *             b = torch_module.as_tensor(b, dtype=dtype)
     * return a, b
     */
    // OPTIMIZE is there something built in to torch?
    auto /* CHECKME: type? */ dtype = torch_module.promote_types(a.dtype, b.dtype);
    if (at_least != py::none()) {
        dtype = torch_module.promote_types(dtype, at_least);
    }
    if (a.dtype != dtype) {
        a = torch_module.as_tensor(a, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */;
    }
    if (b.dtype != dtype) {
        b = torch_module.as_tensor(b, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */;
    }
    return std::make_tuple(a, b);
}

/// Wait for asynchronous processes (if any) to finish
TYPEOF_return TorchBlockBackend::synchronize() {
    /* CHECKME: converted from following python code:
     * # how do we know which devices to synchronize??
     * raise NotImplementedError(f'{self} does not support synchronize yet.')
     */
    // how do we know which devices to synchronize??
    throw std::logic_error(std::format("{} does not support synchronize yet.", self  /* FIXME: standalone self reference */));
}

int TorchBlockBackend::zeros(const int & shape, int dtype, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     * return torch_module.zeros(list(shape), dtype=self.backend_dtype_map[dtype], device=self.as_device(device))
     */
    return torch_module.zeros(list(shape), py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype', 'device'] */;
}

int TorchBlockBackend::as_scalar(int z) {
    // FIXME: implement
}

TorchBlockBackend * TorchBlockBackend::from_factory(const std::string & device) {
    // FIXME: implement
}

std::shared_ptr<TorchBlockBackend> TorchBlockBackend::from_factory_shared(const std::string & device) {
    // FIXME: implement
}

std::shared_ptr<TorchBlockBackend> TorchBlockBackend::from_hdf5(int hdf5_loader, int h5gr, const std::string & subpath) {
    // FIXME: implement
}

std::string TorchBlockBackend::get_backend_name() {
    // FIXME: implement
}

int TorchBlockBackend::apply_leg_permutations(const int & block, const int ) {
    // FIXME: implement
}

int TorchBlockBackend::apply_mask(const int & block, const int & mask, int ax) {
    // FIXME: implement
}

int TorchBlockBackend::cutoff_inverse(const int & a, int cutoff) {
    // FIXME: implement
}

int TorchBlockBackend::linear_combination(const int & a_coef, const int & v, const int & b_coef, const int & w) {
    // FIXME: implement
}

int TorchBlockBackend::mul(const int & a, const int & b) {
    // FIXME: implement
}

int TorchBlockBackend::scale_axis(const int & block, const int & factors, int axis) {
    // FIXME: implement
}

int TorchBlockBackend::multiply_blocks(const int & a, const int & b) {
    // FIXME: implement
}

bool TorchBlockBackend::is_correct_block_type(const int & block) {
    // FIXME: implement
}

const int * TorchBlockBackend::ptr(const int & b) {
    // FIXME: implement
}

const int & TorchBlockBackend::tens(const int & b) {
    // FIXME: implement
}

int TorchBlockBackend::wrap(int tensor) {
    // FIXME: implement
}

int TorchBlockBackend::parse_device(const std::string & device) {
    // FIXME: implement
}

} // namespace cyten
