#include <cyten/symmetries/spaces.h>

namespace cyten {

// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_definition --py-name Leg --header-file include/cyten/symmetries/spaces.h --src-file src/symmetries/spaces.cpp

Leg::Leg(Symmetry::Ptr symmetry, float64 dim, bool is_dual, std::optional<std::vector<int64>> basis_perm) {
    /* CHECKME: converted from following python code:
     * self.symmetry = symmetry
     * self.dim = dim
     * self.is_dual = is_dual
     *         if basis_perm is None:
     *             self._basis_perm = self._inverse_basis_perm = None
     *         else:
     *             if not symmetry.can_be_dropped:
     *                 msg = f'basis_perm is meaningless for {symmetry}.'
     *                 raise SymmetryError(msg)
     *             self._basis_perm = basis_perm = np.asarray(basis_perm, dtype=int)
     *             self._inverse_basis_perm = inverse_permutation(basis_perm)
     */
    symmetry = symmetry;
    dim = dim;
    is_dual = is_dual;
    if (basis_perm == py::none()) {
        /* FIXME: multiple assignment: self._basis_perm = self._inverse_basis_perm = None */
    } else {
        if (!symmetry.can_be_dropped) {
            auto /* CHECKME: type? */ msg = std::format("basis_perm is meaningless for {}.", symmetry);
            throw std::runtime_error(msg);
        }
        /* FIXME: multiple assignment: self._basis_perm = basis_perm = np.asarray(basis_perm, dtype=int) */
        _inverse_basis_perm = inverse_permutation(basis_perm);
    }
}

/// Permutation that translates between public and internal basis order.
/// property getter
ndarray Leg::get_basis_perm() {
    /* CHECKME: converted from following python code:
     *         if not self.symmetry.can_be_dropped:
     *             msg = f'basis_perm is meaningless for {self.symmetry}.'
     *             raise SymmetryError(msg)
     *         if self._basis_perm is None:
     *             return np.arange(self.dim)
     * return self._basis_perm
     */
    if (!symmetry.can_be_dropped) {
        auto /* CHECKME: type? */ msg = std::format("basis_perm is meaningless for {}.", symmetry);
        throw std::runtime_error(msg);
    }
    if (_basis_perm == py::none()) {
        return np.arange(dim);
    }
    return _basis_perm;
}

/// Common setter for :attr:`basis_perm` and :attr:`inverse_basis_perm`.
void Leg::set_basis_perm(std::optional<std::vector<int64>> basis_perm) {
    /* CHECKME: converted from following python code:
     *         if basis_perm is UNSPECIFIED and inverse_basis_perm is UNSPECIFIED:
     *             raise ValueError('Must specify at least one of the arguments')
     *         if basis_perm is UNSPECIFIED:
     *             if inverse_basis_perm is None:
     *                 basis_perm = None
     *             else:
     *                 inverse_basis_perm = np.asarray(inverse_basis_perm, int)
     *                 assert inverse_basis_perm.shape == (self.dim,)
     *                 basis_perm = inverse_permutation(inverse_basis_perm)
     *         elif inverse_basis_perm is UNSPECIFIED:
     *             if basis_perm is None:
     *                 inverse_basis_perm = None
     *             else:
     *                 basis_perm = np.asarray(basis_perm, int)
     *                 assert basis_perm.shape == (self.dim,)
     *                 inverse_basis_perm = inverse_permutation(basis_perm)
     *         elif basis_perm is None and inverse_basis_perm is None:
     *             pass
     *         elif basis_perm is None or inverse_basis_perm is None:
     *             raise ValueError('Can not mix None with an explicit permutation')
     *         else:
     *             basis_perm = np.asarray(basis_perm, int)
     *             assert basis_perm.shape == (self.dim,)
     *             inverse_basis_perm = np.asarray(inverse_basis_perm, int)
     *             assert inverse_basis_perm.shape == (self.dim,)
     *             if not np.all(basis_perm[inverse_basis_perm] == np.arange(self.dim)):
     *                 raise ValueError('The given permutations are not mutually inverse!')
     * self._basis_perm = basis_perm
     * self._inverse_basis_perm = inverse_basis_perm
     */
    if (basis_perm == UNSPECIFIED && inverse_basis_perm == UNSPECIFIED) {
        throw std::invalid_argument("Must specify at least one of the arguments");
    }
    if (basis_perm == UNSPECIFIED) {
        if (inverse_basis_perm == py::none()) {
            basis_perm = py::none();
        } else {
            inverse_basis_perm = np.asarray(inverse_basis_perm, int);
            /* FIXME: Assert: assert inverse_basis_perm.shape == (self.dim,) */
            basis_perm = inverse_permutation(inverse_basis_perm);
        }
    } else {
        if (inverse_basis_perm == UNSPECIFIED) {
            if (basis_perm == py::none()) {
                inverse_basis_perm = py::none();
            } else {
                basis_perm = np.asarray(basis_perm, int);
                /* FIXME: Assert: assert basis_perm.shape == (self.dim,) */
                inverse_basis_perm = inverse_permutation(basis_perm);
            }
        } else {
            if (basis_perm == py::none() && inverse_basis_perm == py::none()) {
                // pass
            } else {
                if (basis_perm == py::none() || inverse_basis_perm == py::none()) {
                    throw std::invalid_argument("Can not mix None with an explicit permutation");
                } else {
                    basis_perm = np.asarray(basis_perm, int);
                    /* FIXME: Assert: assert basis_perm.shape == (self.dim,) */
                    inverse_basis_perm = np.asarray(inverse_basis_perm, int);
                    /* FIXME: Assert: assert inverse_basis_perm.shape == (self.dim,) */
                    if (!(np.all(basis_perm[inverse_basis_perm] == np.arange(dim)))) {
                        throw std::invalid_argument("The given permutations are not mutually inverse!");
                    }
                }
            }
        }
    }
    _basis_perm = basis_perm;
    _inverse_basis_perm = inverse_basis_perm;
}

/// Flatten until there are no more pipes.
/// property getter
std::vector<Ptr> Leg::flat_legs() {
    /* CHECKME: converted from following python code:
     * return [self]
     */
    return {self  /* FIXME: standalone self reference */};
}

/// Flatten until we get spaces.
/// property getter
std::vector<Ptr> Leg::flat_spaces() {
    /* CHECKME: converted from following python code:
     * return [self]
     */
    return {self  /* FIXME: standalone self reference */};
}

/// Inverse permutation of :attr:`basis_perm`.
/// property getter
ndarray Leg::get_inverse_basis_perm() {
    /* CHECKME: converted from following python code:
     *         if not self.symmetry.can_be_dropped:
     *             msg = f'basis_perm is meaningless for {self.symmetry}.'
     *             raise SymmetryError(msg)
     *         if self._inverse_basis_perm is None:
     *             return np.arange(self.dim)
     * return self._inverse_basis_perm
     */
    if (!symmetry.can_be_dropped) {
        auto /* CHECKME: type? */ msg = std::format("basis_perm is meaningless for {}.", symmetry);
        throw std::runtime_error(msg);
    }
    if (_inverse_basis_perm == py::none()) {
        return np.arange(dim);
    }
    return _inverse_basis_perm;
}

/// property getter
void Leg::set_inverse_basis_perm(std::optional<std::vector<int64>> inverse_basis_perm) {
    /* CHECKME: converted from following python code:
     * self.set_basis_perm(inverse_basis_perm=inverse_basis_perm)
     */
    set_basis_perm(py::arg({keyword.key}) = val) /* CHECKME: keywords ['inverse_basis_perm'] */;
}

/// The number of :attr:`flat_legs`.
/// property getter
int64 Leg::num_flat_legs() {
    /* CHECKME: converted from following python code:
     * return 1
     */
    return 1;
}

/// A single character arrow, for use in tensor diagrams
/// property getter
std::string Leg::ascii_arrow() {
    /* CHECKME: converted from following python code:
     * is_pipe = isinstance(self, LegPipe)
     *         if isinstance(self, ElementarySpace):
     *             return {
     *                 (False, False): 'v',
     *                 (False, True): '▼',
     *                 (True, False): '^',
     *                 (True, True): '▲',
     *             }[self.is_dual, is_pipe]
     *         if is_pipe:
     *             return '║'
     * raise RuntimeError
     * # should have already covered all cases
     */
    auto /* CHECKME: type? */ is_pipe = isinstance(self  /* FIXME: standalone self reference */, LegPipe);
    if (isinstance(self  /* FIXME: standalone self reference */, ElementarySpace)) {
        return /* Multidimensional slice using std::gslice
 * NOTE: Requires {{std::make_tuple(false, false), "v"}, {std::make_tuple(false, true), "▼"}, {std::make_tuple(true, false), "^"}, {std::make_tuple(true, true), "▲"}}_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   {{std::make_tuple(false, false), "v"}, {std::make_tuple(false, true), "▼"}, {std::make_tuple(true, false), "^"}, {std::make_tuple(true, true), "▲"}}_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
{{std::make_tuple(false, false), "v"}, {std::make_tuple(false, true), "▼"}, {std::make_tuple(true, false), "^"}, {std::make_tuple(true, true), "▲"}}[std::gslice(is_dual * {{std::make_tuple(false, false), "v"}, {std::make_tuple(false, true), "▼"}, {std::make_tuple(true, false), "^"}, {std::make_tuple(true, true), "▲"}}_strides[0] + is_pipe * {{std::make_tuple(false, false), "v"}, {std::make_tuple(false, true), "▼"}, {std::make_tuple(true, false), "^"}, {std::make_tuple(true, true), "▲"}}_strides[1], std::valarray<std::size_t>{1, 1}, std::valarray<std::size_t>{{{std::make_tuple(false, false), "v"}, {std::make_tuple(false, true), "▼"}, {std::make_tuple(true, false), "^"}, {std::make_tuple(true, true), "▲"}}_strides[0], {{std::make_tuple(false, false), "v"}, {std::make_tuple(false, true), "▼"}, {std::make_tuple(true, false), "^"}, {std::make_tuple(true, true), "▲"}}_strides[1]})];
    }
    if (is_pipe) {
        return "║";
    }
    throw std::runtime_error("");
    /* should have already covered all cases */
}

/// Perform sanity checks.
void Leg::test_sanity() {
    /* CHECKME: converted from following python code:
     *         if not self.symmetry.can_be_dropped:
     *             assert self._basis_perm is None
     *         if self._basis_perm is None:
     *             assert self._inverse_basis_perm is None
     *         else:
     *             assert self._inverse_basis_perm is not None
     *             assert self._basis_perm.shape == self._inverse_basis_perm.shape == (self.dim,)
     *             assert len(np.unique(self._basis_perm)) == self.dim  # is a permutation
     *             assert len(np.unique(self._inverse_basis_perm)) == self.dim  # is a permutation
     *             assert np.all(self._basis_perm[self._inverse_basis_perm] == np.arange(self.dim))
     */
    if (!symmetry.can_be_dropped) {
        /* FIXME: Assert: assert self._basis_perm is None */
    }
    if (_basis_perm == py::none()) {
        /* FIXME: Assert: assert self._inverse_basis_perm is None */
    } else {
        /* FIXME: Assert: assert self._inverse_basis_perm is not None */
        /* FIXME: Assert: assert self._basis_perm.shape == self._inverse_basis_perm.shape == (self.dim,) */
        /* FIXME: Assert: assert len(np.unique(self._basis_perm)) == self.dim */
        /* is a permutation */
        /* FIXME: Assert: assert len(np.unique(self._inverse_basis_perm)) == self.dim */
        /* is a permutation */
        /* FIXME: Assert: assert np.all(self._basis_perm[self._inverse_basis_perm] == np.arange(self.dim)) */
    }
}

/// Convert to an isomorphic :class:`ElementarySpace`
py::object Leg::as_ElementarySpace(bool is_dual) {
    /* CHECKME: converted from following python code:
     * # can be overridden for performance
     * return self.as_Space().as_ElementarySpace(is_dual=is_dual)
     */
    // can be overridden for performance
    return as_Space().as_ElementarySpace(py::arg({keyword.key}) = val) /* CHECKME: keywords ['is_dual'] */;
}

/// property getter
std::vector<int64> Leg::basis_perm() {
    /* CHECKME: converted from following python code:
     * self.set_basis_perm(basis_perm=basis_perm)
     */
    set_basis_perm(py::arg({keyword.key}) = val) /* CHECKME: keywords ['basis_perm'] */;
}

/// Flatten until there are no more pipes.
/// property getter
std::vector<Ptr> Leg::flat_legs() {
    /* CHECKME: converted from following python code:
     * return [self]
     */
    return {self  /* FIXME: standalone self reference */};
}

/// Flatten until we get spaces.
/// property getter
std::vector<Ptr> Leg::flat_spaces() {
    /* CHECKME: converted from following python code:
     * return [self]
     */
    return {self  /* FIXME: standalone self reference */};
}

/// property getter
void Leg::set_inverse_basis_perm(std::optional<std::vector<int64>> inverse_basis_perm) {
    /* CHECKME: converted from following python code:
     * self.set_basis_perm(inverse_basis_perm=inverse_basis_perm)
     */
    set_basis_perm(py::arg({keyword.key}) = val) /* CHECKME: keywords ['inverse_basis_perm'] */;
}

/// The number of :attr:`flat_legs`.
/// property getter
int64 Leg::num_flat_legs() {
    /* CHECKME: converted from following python code:
     * return 1
     */
    return 1;
}

/// Leg permutation such that combining legs would be in C style.
std::vector<int64> Leg::_flat_leg_permutation(int64 offset) {
    /* CHECKME: converted from following python code:
     * return [offset]
     */
    return {offset};
}

/// A single character arrow, for use in tensor diagrams
/// property getter
std::string Leg::ascii_arrow() {
    /* CHECKME: converted from following python code:
     * is_pipe = isinstance(self, LegPipe)
     *         if isinstance(self, ElementarySpace):
     *             return {
     *                 (False, False): 'v',
     *                 (False, True): '▼',
     *                 (True, False): '^',
     *                 (True, True): '▲',
     *             }[self.is_dual, is_pipe]
     *         if is_pipe:
     *             return '║'
     * raise RuntimeError
     * # should have already covered all cases
     */
    is_pipe = isinstance(self  /* FIXME: standalone self reference */, LegPipe);
    if (isinstance(self  /* FIXME: standalone self reference */, ElementarySpace)) {
        return /* Multidimensional slice using std::gslice
 * NOTE: Requires {{std::make_tuple(false, false), "v"}, {std::make_tuple(false, true), "▼"}, {std::make_tuple(true, false), "^"}, {std::make_tuple(true, true), "▲"}}_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   {{std::make_tuple(false, false), "v"}, {std::make_tuple(false, true), "▼"}, {std::make_tuple(true, false), "^"}, {std::make_tuple(true, true), "▲"}}_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
{{std::make_tuple(false, false), "v"}, {std::make_tuple(false, true), "▼"}, {std::make_tuple(true, false), "^"}, {std::make_tuple(true, true), "▲"}}[std::gslice(is_dual * {{std::make_tuple(false, false), "v"}, {std::make_tuple(false, true), "▼"}, {std::make_tuple(true, false), "^"}, {std::make_tuple(true, true), "▲"}}_strides[0] + is_pipe * {{std::make_tuple(false, false), "v"}, {std::make_tuple(false, true), "▼"}, {std::make_tuple(true, false), "^"}, {std::make_tuple(true, true), "▲"}}_strides[1], std::valarray<std::size_t>{1, 1}, std::valarray<std::size_t>{{{std::make_tuple(false, false), "v"}, {std::make_tuple(false, true), "▼"}, {std::make_tuple(true, false), "^"}, {std::make_tuple(true, true), "▲"}}_strides[0], {{std::make_tuple(false, false), "v"}, {std::make_tuple(false, true), "▼"}, {std::make_tuple(true, false), "^"}, {std::make_tuple(true, true), "▲"}}_strides[1]})];
    }
    if (is_pipe) {
        return "║";
    }
    throw std::runtime_error("");
    /* should have already covered all cases */
}

/// Apply the basis_perm, i.e. form ``arr[self.basis_perm]``.
py::array Leg::apply_basis_perm(py::array arr, int64 axis, bool inverse, bool pre_compose) {
    /* CHECKME: converted from following python code:
     * # this implementation assumes _basis_perm. AbelianLegPipe overrides this method.
     * perm = self._inverse_basis_perm if inverse else self._basis_perm
     *         if perm is None:
     *             # perm is identity permutation
     *             return arr
     *         if pre_compose:
     *             assert axis == 0
     *             return perm[arr]
     * return np.take(arr, perm, axis=axis)
     */
    // this implementation assumes _basis_perm. AbelianLegPipe overrides this method.
    auto /* CHECKME: type? */ perm = inverse ? _inverse_basis_perm : _basis_perm;
    if (perm == py::none()) {
        // perm is identity permutation
        return arr;
    }
    if (pre_compose) {
        /* FIXME: Assert: assert axis == 0 */
        return perm[arr];
    }
    return np.take(arr, perm, py::arg({keyword.key}) = val) /* CHECKME: keywords ['axis'] */;
}

} // namespace cyten
