
#include <cyten/symmetries/su2.h>

namespace cyten {

// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_definition --py-name SU2 --header-file include/cyten/symmetries/su2.h --src-file src/symmetries/su2.cpp

SU2::SU2(std::optional<std::string> descriptive_name) {
    /* CHECKME: converted from following python code:
     *         Group.__init__(
     *             self,
     *             fusion_style=FusionStyle.multiple_unique,
     *             trivial_sector=np.array([0], dtype=int),
     *             group_name='SU(2)',
     *             num_sectors=np.inf,
     *             has_complex_topological_data=False,
     *             descriptive_name=descriptive_name,
     *         )
     */
    Group.__init__(self  /* FIXME: standalone self reference */, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['fusion_style', 'trivial_sector', 'group_name', 'num_sectors', 'has_complex_topological_data', 'descriptive_name'] */;
}

bool SU2::is_valid_sector(Sector a) {
    /* CHECKME: converted from following python code:
     * return getattr(a, 'shape', ()) == (1,) and (a >= 0)
     */
    return getattr(a, "shape", std::tuple<>()) == std::make_tuple(1) && a >= 0;
}

bool SU2::are_valid_sectors(const SectorArray & sectors) {
    /* CHECKME: converted from following python code:
     * shape = getattr(sectors, 'shape', ())
     * return len(shape) == 2 and shape[1] == 1 and np.all(sectors >= 0)
     */
    auto /* CHECKME: type? */ shape = getattr(sectors, "shape", std::tuple<>());
    return len(shape) == 2 && shape[1] == 1 && np.all(sectors >= 0);
}

SectorArray SU2::fusion_outcomes(Sector a, Sector b) {
    /* CHECKME: converted from following python code:
     * # J_tot = |J1 - J2|, ..., J1 + J2
     * JJ_min = np.abs(a - b).item()
     * JJ_max = (a + b).item()
     * return np.arange(JJ_min, JJ_max + 2, 2)[:, np.newaxis]
     */
    // J_tot = |J1 - J2|, ..., J1 + J2
    auto /* CHECKME: type? */ JJ_min = np.abs(a - b).item();
    auto /* CHECKME: type? */ JJ_max = a + b.item();
    return /* Multidimensional slice using std::gslice
 * NOTE: Requires np.arange(JJ_min, JJ_max + 2, 2)_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   np.arange(JJ_min, JJ_max + 2, 2)_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
np.arange(JJ_min, JJ_max + 2, 2)[std::gslice(np.newaxis * np.arange(JJ_min, JJ_max + 2, 2)_strides[1], std::valarray<std::size_t>{np.arange(JJ_min, JJ_max + 2, 2).shape(0), 1}, std::valarray<std::size_t>{np.arange(JJ_min, JJ_max + 2, 2)_strides[0], np.arange(JJ_min, JJ_max + 2, 2)_strides[1]})];
}

bool SU2::can_fuse_to(Sector a, Sector b, Sector c) {
    /* CHECKME: converted from following python code:
     * return (c <= a + b) and (a <= b + c) and (b <= c + a) and ((a + b + c) % 2 == 0)
     */
    return c <= a + b && a <= b + c && b <= c + a && a + b + c % 2 == 0;
}

int64 SU2::sector_dim(Sector a) {
    /* CHECKME: converted from following python code:
     * # dim = 2 * J + 1 = jj + 1
     * return a[0] + 1
     */
    // dim = 2 * J + 1 = jj + 1
    return a[0] + 1;
}

py::array SU2::batch_sector_dim(const SectorArray & a) {
    /* CHECKME: converted from following python code:
     * # dim = 2 * J + 1 = jj + 1
     *         if len(a) == 0:
     *             return np.zeros([0], dtype=int)
     * return a[:, 0] + 1
     */
    // dim = 2 * J + 1 = jj + 1
    if (len(a) == 0) {
        return np.zeros({0}, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */;
    }
    return /* Multidimensional slice using std::gslice
 * NOTE: Requires a_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   a_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
a[std::gslice(0, std::valarray<std::size_t>{a.shape(0), 1}, std::valarray<std::size_t>{a_strides[0], a_strides[1]})] + 1;
}

std::string SU2::sector_str(Sector a) {
    /* CHECKME: converted from following python code:
     * jj = a[0]
     * j_str = str(jj // 2) if jj % 2 == 0 else f'{jj}/2'
     * return f'{jj} (J={j_str})'
     */
    auto /* CHECKME: type? */ jj = a[0];
    auto /* CHECKME: type? */ j_str = jj % 2 == 0 ? str(jj / 2) : std::format("{}/2", jj);
    return std::format("{} (J={})", jj, j_str);
}

str SU2::__repr__() {
    /* CHECKME: converted from following python code:
     * name_str = '' if self.descriptive_name is None else f'"{self.descriptive_name}"'
     * return f'SU2Symmetry({name_str})'
     */
    auto /* CHECKME: type? */ name_str = descriptive_name == py::none() ? "" : std::format("\"{}\"", descriptive_name);
    return std::format("SU2Symmetry({})", name_str);
}

bool SU2::_is_equivalent_factor(const SymmetryFactor & other) {
    /* CHECKME: converted from following python code:
     * return isinstance(other, SU2)
     */
    return isinstance(other, SU2);
}

Sector SU2::dual_sector(Sector a) {
    /* CHECKME: converted from following python code:
     * # all sectors are self-dual
     * return a
     */
    // all sectors are self-dual
    return a;
}

SectorArray SU2::dual_sectors(const SectorArray & sectors) {
    /* CHECKME: converted from following python code:
     * return sectors
     */
    return sectors;
}

int64 SU2::_n_symbol(Sector a, Sector b, Sector c) {
    /* CHECKME: converted from following python code:
     * return 1
     */
    return 1;
}

py::array SU2::_f_symbol(Sector a, Sector b, Sector c, Sector d, Sector e, Sector f) {
    /* CHECKME: converted from following python code:
     * # OPTIMIZE: jutho has a special case if all sectors are trivial ...?
     * from . import _su2data
     * return _su2data.f_symbol(a[0], b[0], c[0], d[0], e[0], f[0])
     */
    // OPTIMIZE: jutho has a special case if all sectors are trivial ...?
    /* FIXME: ImportFrom: from . import _su2data */
    return _su2data.f_symbol(a[0], b[0], c[0], d[0], e[0], f[0]);
}

int64 SU2::frobenius_schur(Sector a) {
    /* CHECKME: converted from following python code:
     * # +1 for integer spin (i.e. even `a`), -1 for half integer
     * return 1 - 2 * (a[0] % 2)
     */
    // +1 for integer spin (i.e. even `a`), -1 for half integer
    return 1 - 2 * a[0] % 2;
}

float64 SU2::qdim(Sector a) {
    /* CHECKME: converted from following python code:
     * return a[0] + 1
     */
    return a[0] + 1;
}

py::array SU2::_r_symbol(Sector a, Sector b, Sector c) {
    /* CHECKME: converted from following python code:
     * # R symbol is +1 if ``j_sum = (j_a + j_b - j_c)`` is even, -1 otherwise.
     * # Note that (j_a + j_b - j_c) is integer by fusion rule and that e.g. ``a == 2 * j_a``.
     * # For even (odd) j_sum, we get that ``(a + b - c) % 4`` is 0 (2),
     * # such that ``1 - (a + b - c) % 4`` is 1 (-1). It has shape ``(1,)``.
     * return 1 - (a + b - c) % 4
     */
    // R symbol is +1 if ``j_sum = (j_a + j_b - j_c)`` is even, -1 otherwise.
    // Note that (j_a + j_b - j_c) is integer by fusion rule and that e.g. ``a == 2 * j_a``.
    // For even (odd) j_sum, we get that ``(a + b - c) % 4`` is 0 (2),
    // such that ``1 - (a + b - c) % 4`` is 1 (-1). It has shape ``(1,)``.
    return 1 - a + b - c % 4;
}

py::array SU2::_fusion_tensor(Sector a, Sector b, Sector c, bool Z_a, bool Z_b) {
    /* CHECKME: converted from following python code:
     * from . import _su2data
     * X = _su2data.fusion_tensor(a[0], b[0], c[0])
     *         if Z_a and Z_b:
     *             # [µ, m_a, m_b, m_c] @ [m_a, m_abar*] -> [µ, m_b, m_c, m_abar*]
     *             X = np.tensordot(X, self.Z_iso(self.dual_sector(a)), (1, 0))
     *             # [µ, m_b, m_c, m_abar*] @ [m_b, m_bbar*] -> [µ, m_c, m_abar*, m_bbar*]
     *             X = np.tensordot(X, self.Z_iso(self.dual_sector(b)), (1, 0))
     *             X = np.transpose(X, [0, 2, 3, 1])
     *         elif Z_a:
     *             # [µ, m_a, m_b, m_c] @ [m_a, m_abar*] -> [µ, m_b, m_c, m_abar*]
     *             X = np.tensordot(X, self.Z_iso(self.dual_sector(a)), (1, 0))
     *             X = np.transpose(X, [0, 3, 1, 2])
     *         elif Z_b:
     *             # [µ, m_a, m_b, m_c] @ [m_b, m_bbar*] -> [µ, m_a, m_c, m_bbar*]
     *             X = np.tensordot(X, self.Z_iso(self.dual_sector(b)), (2, 0))
     *             X = np.transpose(X, [0, 1, 3, 2])
     * return X
     */
    /* FIXME: ImportFrom: from . import _su2data */
    auto /* CHECKME: type? */ X = _su2data.fusion_tensor(a[0], b[0], c[0]);
    if (Z_a && Z_b) {
        // [µ, m_a, m_b, m_c] @ [m_a, m_abar*] -> [µ, m_b, m_c, m_abar*]
        X = np.tensordot(X, Z_iso(dual_sector(a)), std::make_tuple(1, 0));
        // [µ, m_b, m_c, m_abar*] @ [m_b, m_bbar*] -> [µ, m_c, m_abar*, m_bbar*]
        X = np.tensordot(X, Z_iso(dual_sector(b)), std::make_tuple(1, 0));
        X = np.transpose(X, {0, 2, 3, 1});
    } else {
        if (Z_a) {
            // [µ, m_a, m_b, m_c] @ [m_a, m_abar*] -> [µ, m_b, m_c, m_abar*]
            X = np.tensordot(X, Z_iso(dual_sector(a)), std::make_tuple(1, 0));
            X = np.transpose(X, {0, 3, 1, 2});
        } else {
            if (Z_b) {
                // [µ, m_a, m_b, m_c] @ [m_b, m_bbar*] -> [µ, m_a, m_c, m_bbar*]
                X = np.tensordot(X, Z_iso(dual_sector(b)), std::make_tuple(2, 0));
                X = np.transpose(X, {0, 1, 3, 2});
            }
        }
    }
    return X;
}

py::array SU2::Z_iso(Sector a) {
    /* CHECKME: converted from following python code:
     * from . import _su2data
     * return _su2data.Z_iso(a[0])
     */
    /* FIXME: ImportFrom: from . import _su2data */
    return _su2data.Z_iso(a[0]);
}

std::string SU2::repr() {
    // FIXME: implement
}

} // namespace cyten
