#include "cyten/symmetries/trees.h"

namespace cyten {

} // namespace cyten
// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/scripts/pybind11_codegen.py gen_cpp_definition --py-name FusionTree --header-file include/cyten/symmetries/trees.h --src-file src/symmetries/trees.cpp

FusionTree::FusionTree(
    Symmetry::Ptr symmetry,
    SectorArray uncoupled,
    Sector coupled,
    std::vector<std::uint8_t> are_dual,
    SectorArray inner_sectors,
    std::optional<std::vector<int64>> multiplicities
) {
    /* CHECKME: converted from following python code:
     * # N uncoupled sectors
     * # N flags: is there a Z isomorphism above the uncoupled sector
     * # N - 2 internal sectors
     * # N - 1 multiplicity labels; all 0 per default
     * # OPTIMIZE demand SectorArray / ndarray (not list) and skip conversions?
     * assert isinstance(symmetry, Symmetry)
     * self.symmetry = symmetry
     * self.uncoupled = as_sector_array(uncoupled, sector_ind_len=symmetry.sector_ind_len)
     * self.num_uncoupled = len(uncoupled)
     * self.num_vertices = num_vertices = max(len(uncoupled) - 1, 0)
     * self.num_inner_edges = max(len(uncoupled) - 2, 0)
     * self.coupled = as_sector(coupled)
     * self.are_dual = np.asarray(are_dual, dtype=bool)
     *         if len(inner_sectors) == 0:
     *             inner_sectors = symmetry.empty_sector_array
     * # empty lists are by default converted to arrays with dtype=float, which leads to issues in __hash__
     * self.inner_sectors = as_sector_array(inner_sectors, sector_ind_len=symmetry.sector_ind_len)
     *         if multiplicities is None:
     *             multiplicities = np.zeros((num_vertices,), dtype=int)
     * self.multiplicities = np.asarray(multiplicities, dtype=int)
     * self.fusion_style = symmetry.fusion_style
     * self.is_abelian = symmetry.is_abelian
     * self.braiding_style = symmetry.braiding_style
     */
    /* N uncoupled sectors */
    // N flags: is there a Z isomorphism above the uncoupled sector
    // N - 2 internal sectors
    // N - 1 multiplicity labels; all 0 per default
    // OPTIMIZE demand SectorArray / ndarray (not list) and skip conversions?
    /* FIXME: Assert: assert isinstance(symmetry, Symmetry) */
    symmetry = symmetry;
    uncoupled = as_sector_array(uncoupled, py::arg({keyword.key}) = val) /* CHECKME: keywords ['sector_ind_len'] */;
    num_uncoupled = len(uncoupled);
    /* FIXME: multiple assignment: self.num_vertices = num_vertices = max(len(uncoupled) - 1, 0) */
    num_inner_edges = max(len(uncoupled) - 2, 0);
    coupled = as_sector(coupled);
    are_dual = np.asarray(are_dual, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */;
    if (len(inner_sectors) == 0) {
        inner_sectors = symmetry.empty_sector_array;
    }
    // empty lists are by default converted to arrays with dtype=float, which leads to issues in __hash__
    inner_sectors = as_sector_array(inner_sectors, py::arg({keyword.key}) = val) /* CHECKME: keywords ['sector_ind_len'] */;
    if (multiplicities == py::none()) {
        multiplicities = np.zeros(std::make_tuple(num_vertices), py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */;
    }
    multiplicities = np.asarray(multiplicities, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */;
    fusion_style = symmetry.fusion_style;
    is_abelian = symmetry.is_abelian;
    braiding_style = symmetry.braiding_style;
}

/// The uncoupled sectors *above* any Z isomorphisms.
/// property getter
SectorArray FusionTree::pre_Z_uncoupled() {
    /* CHECKME: converted from following python code:
     * res = self.uncoupled.copy()
     * duals = self.symmetry.dual_sectors(res[self.are_dual])
     *         for i, dual in zip(np.flatnonzero(self.are_dual), duals):
     *             res[int(i)] = dual
     * return res
     */
    auto /* CHECKME: type? */ res = uncoupled.copy();
    auto /* CHECKME: type? */ duals = symmetry.dual_sectors(res[are_dual]);
    /* NOTE: Using C++23 std::views::zip (requires -std=c++23)
     * For C++20, use std::ranges::views::zip or implement custom zip.
     * Alternative libraries: range-v3 (ranges::views::zip)
     */
    for (auto [i, dual] : std::views::zip(np.flatnonzero(are_dual), duals)) {
        res[int(i)] = dual;
    }
    return res;
}

/// Perform sanity checks.
void FusionTree::test_sanity() {
    /* CHECKME: converted from following python code:
     * assert self.symmetry.are_valid_sectors(self.uncoupled), 'invalid uncoupled'
     * assert self.symmetry.is_valid_sector(self.coupled), 'invalid coupled'
     * assert len(self.are_dual) == self.num_uncoupled, 'wrong length of are_dual'
     * assert len(self.inner_sectors) == self.num_inner_edges, 'wrong length of inner_sectors'
     * assert self.symmetry.are_valid_sectors(self.inner_sectors), 'invalid inner sectors'
     * assert len(self.multiplicities) == self.num_vertices, 'invalid length of multiplicities'
     * # special cases: no vertices
     *         if self.num_uncoupled == 0:
     *             assert self.coupled == self.symmetry.trivial_sector
     *         if self.num_uncoupled == 1:
     *             assert self.uncoupled[0] == self.coupled
     * # otherwise, check fusion rules at every vertex
     *         for n in range(self.num_vertices):
     *             a, b, mu, c = self.vertex_labels(n)
     *             N = self.symmetry.n_symbol(a, b, c)
     *             assert N > 0, 'inconsistent fusion'
     *             assert 0 <= mu < N, 'invalid multiplicity label'
     */
    /* FIXME: Assert: assert self.symmetry.are_valid_sectors(self.uncoupled), 'invalid uncoupled' */
    /* FIXME: Assert: assert self.symmetry.is_valid_sector(self.coupled), 'invalid coupled' */
    /* FIXME: Assert: assert len(self.are_dual) == self.num_uncoupled, 'wrong length of are_dual' */
    /* FIXME: Assert: assert len(self.inner_sectors) == self.num_inner_edges, 'wrong length of inner_sectors' */
    /* FIXME: Assert: assert self.symmetry.are_valid_sectors(self.inner_sectors), 'invalid inner sectors' */
    /* FIXME: Assert: assert len(self.multiplicities) == self.num_vertices, 'invalid length of multiplicities' */
    // special cases: no vertices
    if (num_uncoupled == 0) {
        /* FIXME: Assert: assert self.coupled == self.symmetry.trivial_sector */
    }
    if (num_uncoupled == 1) {
        /* FIXME: Assert: assert self.uncoupled[0] == self.coupled */
    }
    // otherwise, check fusion rules at every vertex
    for (auto n = 0; n < num_vertices; ++n) {
        std::make_tuple(a, b, mu, c) = vertex_labels(n);
        auto /* CHECKME: type? */ N = symmetry.n_symbol(a, b, c);
        /* FIXME: Assert: assert N > 0, 'inconsistent fusion' */
        /* FIXME: Assert: assert 0 <= mu < N, 'invalid multiplicity label' */
    }
}

/// Assume an abelian symmetry and build the unique tree with the given `uncoupled`.
FusionTree FusionTree::from_abelian_symmetry(
    Symmetry::Ptr symmetry,
    const SectorArray & uncoupled,
    const std::vector<std::uint8_t> & are_dual
) {
    /* CHECKME: converted from following python code:
     * assert symmetry.is_abelian
     *         if len(uncoupled) == 0:
     *             return cls.from_empty(symmetry=symmetry)
     *         if len(uncoupled) == 1:
     *             return cls.from_sector(symmetry=symmetry, sector=uncoupled[0], is_dual=are_dual[0])
     * fusion_outcomes = []
     * last_sector = uncoupled[0]
     *         for a in uncoupled[1:]:
     *             f = symmetry.fusion_outcomes(last_sector, a)[0]
     *             fusion_outcomes.append(f)
     *             last_sector = f
     *         return FusionTree(
     *             symmetry=symmetry,
     *             uncoupled=uncoupled,
     *             coupled=fusion_outcomes[-1],
     *             are_dual=are_dual,
     *             inner_sectors=fusion_outcomes[:-1],
     *             multiplicities=None,
     *         )
     */
    /* FIXME: Assert: assert symmetry.is_abelian */
    if (len(uncoupled) == 0) {
        return cls.from_empty(py::arg({keyword.key}) = val) /* CHECKME: keywords ['symmetry'] */;
    }
    if (len(uncoupled) == 1) {
        return cls.from_sector(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['symmetry', 'sector', 'is_dual'] */;
    }
    auto /* CHECKME: type? */ fusion_outcomes = {} /* FIXME: empty list */;
    auto /* CHECKME: type? */ last_sector = uncoupled[0];
    /* FIXME: for loop:         for a in uncoupled[1:]:
            f = symmetry.fusion_outcomes(last_sector, a)[0]
            fusion_outcomes.append(f)
            last_sector = f */
    return FusionTree(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['symmetry', 'uncoupled', 'coupled', 'are_dual', 'inner_sectors', 'multiplicities'] */;
}

/// The empty tree with no uncoupled sectors.
FusionTree FusionTree::from_empty(Symmetry::Ptr symmetry) {
    /* CHECKME: converted from following python code:
     *         return FusionTree(
     *             symmetry,
     *             uncoupled=symmetry.empty_sector_array,
     *             coupled=symmetry.trivial_sector,
     *             are_dual=[],
     *             inner_sectors=symmetry.empty_sector_array,
     *             multiplicities=[],
     *         )
     */
    return FusionTree(symmetry, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['uncoupled', 'coupled', 'are_dual', 'inner_sectors', 'multiplicities'] */;
}

/// A tree with a single uncoupled sector and no nodes.
FusionTree FusionTree::from_sector(Symmetry::Ptr symmetry, Sector sector, bool is_dual) {
    /* CHECKME: converted from following python code:
     *         return FusionTree(
     *             symmetry,
     *             uncoupled=sector_array_from_sector(as_sector(sector)),
     *             coupled=sector,
     *             are_dual=[is_dual],
     *             inner_sectors=symmetry.empty_sector_array,
     *             multiplicities=[],
     *         )
     */
    return FusionTree(symmetry, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['uncoupled', 'coupled', 'are_dual', 'inner_sectors', 'multiplicities'] */;
}

/// The uncoupled sectors *above* any Z isomorphisms.
/// property getter
SectorArray FusionTree::pre_Z_uncoupled() {
    /* CHECKME: converted from following python code:
     * res = self.uncoupled.copy()
     * duals = self.symmetry.dual_sectors(res[self.are_dual])
     *         for i, dual in zip(np.flatnonzero(self.are_dual), duals):
     *             res[int(i)] = dual
     * return res
     */
    res = uncoupled.copy();
    duals = symmetry.dual_sectors(res[are_dual]);
    /* NOTE: Using C++23 std::views::zip (requires -std=c++23)
     * For C++20, use std::ranges::views::zip or implement custom zip.
     * Alternative libraries: range-v3 (ranges::views::zip)
     */
    for (auto [i, dual] : std::views::zip(np.flatnonzero(are_dual), duals)) {
        res[int(i)] = dual;
    }
    return res;
}

int FusionTree::__hash__() {
    /* CHECKME: converted from following python code:
     *         if self.symmetry.is_abelian:
     *             # inner sectors are completely determined by uncoupled, all multiplicities are 0
     *             unique_identifier = [self.are_dual, self.coupled, self.uncoupled]
     *         elif self.symmetry.has_unique_fusion:
     *             # all multiplicities are 0
     *             unique_identifier = [self.are_dual, self.coupled, self.uncoupled, self.inner_sectors]
     *         else:
     *             unique_identifier = [self.are_dual, self.coupled, self.uncoupled, self.inner_sectors, self.multiplicities]
     * values = []
     *         for arr in unique_identifier:
     *             if isinstance(arr, SectorArray):
     *                 values.append(tuple(arr))
     *             elif isinstance(arr, Sector):
     *                 values.append(arr)
     *             else:
     *                 values.append(tuple(np.asarray(arr).tolist()))
     * return hash(tuple(values))
     */
    if (symmetry.is_abelian) {
        // inner sectors are completely determined by uncoupled, all multiplicities are 0
        auto /* CHECKME: type? */ unique_identifier = {are_dual, coupled, uncoupled};
    } else {
        if (symmetry.has_unique_fusion) {
            // all multiplicities are 0
            unique_identifier = {are_dual, coupled, uncoupled, inner_sectors};
        } else {
            unique_identifier = {are_dual, coupled, uncoupled, inner_sectors, multiplicities};
        }
    }
    auto /* CHECKME: type? */ values = {} /* FIXME: empty list */;
    /* FIXME: for loop:         for arr in unique_identifier:
            if isinstance(arr, SectorArray):
                values.append(tuple(arr))
            elif isinstance(arr, Sector):
                values.append(arr)
            else:
                values.append(tuple(np.asarray(arr).tolist())) */
    return hash(tuple(values));
}

bool FusionTree::operator==(const FusionTree & other) {
    /* CHECKME: converted from following python code:
     *         if not isinstance(other, FusionTree):
     *             return False
     *         return (
     *             np.all(self.are_dual == other.are_dual)
     *             and self.coupled == other.coupled
     *             and rows_equal(self.uncoupled, other.uncoupled)
     *             and rows_equal(self.inner_sectors, other.inner_sectors)
     *             and np.all(self.multiplicities == other.multiplicities)
     *         )
     */
    if (!(isinstance(other, FusionTree))) {
        return false;
    }
    return np.all(are_dual == other.are_dual) && coupled == other.coupled && rows_equal(uncoupled, other.uncoupled) && rows_equal(inner_sectors, other.inner_sectors) && np.all(multiplicities == other.multiplicities);
}

/// The :meth:`ascii_diagram` as a 2D array of single characters.
np_NDArray FusionTree::_ascii_diagram(
    bool dagger,
    TYPEOF_uncoupled_padding uncoupled_padding,
    TYPEOF_inner_sector_padding inner_sector_padding
) {
    /* CHECKME: converted from following python code:
     * # We build a splitting tree (dagger=True), and if dagger=False, we mirror it at the end
     * assert uncoupled_padding > 0
     * assert inner_sector_padding >= 0
     * uncoupled_strs = [self.symmetry.sector_str(a) for a in self.uncoupled]
     * pre_Z_uncoupled_strs = [self.symmetry.sector_str(a) for a in self.pre_Z_uncoupled]
     * # single-letter sectors dont work with the design choice of attaching wires to the
     * # second character of a sector -> make them at least 2 characters
     * uncoupled_strs = [s.rjust(2) for s in uncoupled_strs]
     * pre_Z_uncoupled_strs = [s.rjust(2) for s in pre_Z_uncoupled_strs]
     * # pad the uncoupled sectors in a single column to a consistent width
     * uncoupled_widths = [max(len(s), len(s2)) for s, s2 in zip(uncoupled_strs, pre_Z_uncoupled_strs)]
     * uncoupled_strs = [s.ljust(w) for w, s in zip(uncoupled_widths, uncoupled_strs)]
     * pre_Z_uncoupled_strs = [s.ljust(w) for w, s in zip(uncoupled_widths, pre_Z_uncoupled_strs)]
     * # special cases with no fusion vertices
     *         if self.num_uncoupled == 0:
     *             return np.array(list('empty FusionTree'), dtype=str)[:, None]
     *         if self.num_uncoupled == 1:
     *             ascii = np.full((uncoupled_widths[0], 5), ' ', dtype=str)
     *             ascii[:, 0] = list(uncoupled_strs[0])
     *             # note: arrows are the same no matter if dagger or not
     *             ascii[1, [1, 2, 3]] = ['v', 'Z', '^'] if self.are_dual[0] else ['v', '│', 'v']
     *             ascii[:, 4] = list(pre_Z_uncoupled_strs[0])
     *             if not dagger:
     *                 ascii = ascii[:, ::-1]
     *             return ascii
     * coupled_str = self.symmetry.sector_str(self.coupled)
     * inner_sector_strs = [self.symmetry.sector_str(s) for s in self.inner_sectors]
     * # step 1: build just the bare tree without inner sectors or multiplicity labels
     * #         only remember where they would go
     * vertex_positions = []
     * # positions of the ┴
     * num_rows_uncoupled = 5
     * num_rows_coupled = 1
     * num_rows = num_rows_uncoupled + 2 * self.num_vertices + num_rows_coupled
     * uncoupled_pos = [sum(uncoupled_widths[:i]) + i * uncoupled_padding for i in range(self.num_uncoupled)]
     * num_cols = sum(uncoupled_widths) + self.num_uncoupled * uncoupled_padding
     * ascii = np.full((num_cols, num_rows), ' ', dtype=str)
     * # last line: pre_Z_uncoupled
     *         for pos, s in zip(uncoupled_pos, uncoupled_strs):
     *             ascii[pos : pos + len(s), -1] = list(s)
     * # line -2: Z or vertical wires
     *         for pos, has_Z in zip(uncoupled_pos, self.are_dual):
     *             # note: arrows are the same no matter if dagger or not
     *             ascii[pos + 1, [-4, -3, -2]] = ['v', 'Z', '^'] if has_Z else ['v', '│', 'v
     * # line -3: uncoupled
     *         for pos, s in zip(uncoupled_pos, pre_Z_uncoupled_strs):
     *             ascii[pos : pos + len(s), -5] = list(s)
     * # fusion vertices
     * row = num_rows - 1 - num_rows_uncoupled
     * left_wire = uncoupled_pos[0] + 1
     *         for n in range(self.num_vertices):
     *             right_wire = uncoupled_pos[n + 1] + 1
     *             ascii[right_wire, row + 1 : -num_rows_uncoupled] = '│'
     *             vertex = (left_wire + right_wire) // 2
     *             ascii[left_wire, row] = '╭' if dagger else '╰'
     *             ascii[left_wire + 1 : vertex, row] = '─'
     *             ascii[vertex, row] = '┴' if dagger else '┬'
     *             vertex_positions.append((vertex, row))
     *             ascii[vertex + 1 : right_wire, row] = '─'
     *             ascii[right_wire, row] = '╮' if dagger else '╯'
     *             ascii[vertex, row - 1] = '│'
     *             # for next iteration:
     *             left_wire = vertex
     *             row = row - 2
     * assert row == 0
     * coupled_pos = left_wire - 1
     * ascii[coupled_pos : coupled_pos + len(coupled_str), 0] = list(coupled_str)
     * left_overhangs = {}
     * # {row: extra_str}
     *         for (x, y), s in zip(vertex_positions[:-1], inner_sector_strs):
     *             row = y - 1  # one above the vertex
     *             start = x - len(s)
     *             if start < 0:
     *                 left_overhangs[row] = s[: abs(start)]
     *                 ascii[:x, row] = list(s[abs(start) :])
     *             else:
     *                 ascii[start:x, row] = list(s)
     *         if len(left_overhangs) > 0:
     *             extra_left = np.full((max(len(s) for s in left_overhangs.values()), num_rows), ' ', str)
     *             for row, extra_s in left_overhangs.items():
     *                 extra_left[-len(extra_s) :, row] = list(extra_s)
     *         else:
     *             extra_left = np.zeros((0, num_rows), str)
     *         if not self.symmetry.has_unique_fusion:
     *             # need to print multiplicities
     *             for (x, y), mult in zip(vertex_positions, self.multiplicities):
     *                 mult = str(mult)
     *                 if len(mult) == 1:
     *                     ascii[x, y] = mult
     *                 elif len(mult) == 2:
     *                     ascii[x : x + 2, y] = list(mult)
     *                 elif len(mult) == 3:
     *                     ascii[x - 1 : x + 2, y] = list(mult)
     *                 else:
     *                     raise NotImplementedError('Multiplicity with >3 digits not supported.')
     * # finalize
     * ascii = np.concatenate([extra_left, ascii], axis=0)
     *         if not dagger:
     *             ascii = ascii[:, ::-1]
     * return ascii
     */
    // We build a splitting tree (dagger=True), and if dagger=False, we mirror it at the end
    /* FIXME: Assert: assert uncoupled_padding > 0 */
    /* FIXME: Assert: assert inner_sector_padding >= 0 */
    auto /* CHECKME: type? */ uncoupled_strs = /* FIXME: ListComp: [self.symmetry.sector_str(a) for a in self.uncoupled] */;
    auto /* CHECKME: type? */ pre_Z_uncoupled_strs = /* FIXME: ListComp: [self.symmetry.sector_str(a) for a in self.pre_Z_uncoupled] */;
    // single-letter sectors dont work with the design choice of attaching wires to the
    // second character of a sector -> make them at least 2 characters
    uncoupled_strs = /* FIXME: ListComp: [s.rjust(2) for s in uncoupled_strs] */;
    pre_Z_uncoupled_strs = /* FIXME: ListComp: [s.rjust(2) for s in pre_Z_uncoupled_strs] */;
    // pad the uncoupled sectors in a single column to a consistent width
    auto /* CHECKME: type? */ uncoupled_widths = /* FIXME: ListComp: [max(len(s), len(s2)) for s, s2 in zip(uncoupled_strs, pre_Z_uncoupled_strs)] */;
    uncoupled_strs = /* FIXME: ListComp: [s.ljust(w) for w, s in zip(uncoupled_widths, uncoupled_strs)] */;
    pre_Z_uncoupled_strs = /* FIXME: ListComp: [s.ljust(w) for w, s in zip(uncoupled_widths, pre_Z_uncoupled_strs)] */;
    // special cases with no fusion vertices
    if (num_uncoupled == 0) {
        return /* Multidimensional slice using std::gslice
 * NOTE: Requires np.array(list("empty FusionTree"), py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   np.array(list("empty FusionTree"), py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
np.array(list("empty FusionTree"), py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */[std::gslice(py::none() * np.array(list("empty FusionTree"), py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */_strides[1], std::valarray<std::size_t>{np.array(list("empty FusionTree"), py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */.shape(0), 1}, std::valarray<std::size_t>{np.array(list("empty FusionTree"), py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */_strides[0], np.array(list("empty FusionTree"), py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */_strides[1]})];
    }
    if (num_uncoupled == 1) {
        auto /* CHECKME: type? */ ascii = np.full(std::make_tuple(uncoupled_widths[0], 5), " ", py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */;
        /* Multidimensional slice using std::gslice
 * NOTE: Requires ascii_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   ascii_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
ascii[std::gslice(0, std::valarray<std::size_t>{ascii.shape(0), 1}, std::valarray<std::size_t>{ascii_strides[0], ascii_strides[1]})] = list(uncoupled_strs[0]);
        // note: arrows are the same no matter if dagger or not
        /* Multidimensional slice using std::gslice
 * NOTE: Requires ascii_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   ascii_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
ascii[std::gslice(1 * ascii_strides[0] + {1, 2, 3} * ascii_strides[1], std::valarray<std::size_t>{1, 1}, std::valarray<std::size_t>{ascii_strides[0], ascii_strides[1]})] = are_dual[0] ? {"v", "Z", "^"} : {"v", "│", "v"};
        /* Multidimensional slice using std::gslice
 * NOTE: Requires ascii_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   ascii_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
ascii[std::gslice(4 * ascii_strides[1], std::valarray<std::size_t>{ascii.shape(0), 1}, std::valarray<std::size_t>{ascii_strides[0], ascii_strides[1]})] = list(pre_Z_uncoupled_strs[0]);
        if (!dagger) {
            ascii = /* Multidimensional slice using std::gslice
 * NOTE: Requires ascii_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   ascii_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
ascii[std::gslice(0, std::valarray<std::size_t>{ascii.shape(0), ascii.shape(1)}, std::valarray<std::size_t>{ascii_strides[0], ascii_strides[1] * -1})];
        }
        return ascii;
    }
    auto /* CHECKME: type? */ coupled_str = symmetry.sector_str(coupled);
    auto /* CHECKME: type? */ inner_sector_strs = /* FIXME: ListComp: [self.symmetry.sector_str(s) for s in self.inner_sectors] */;
    // step 1: build just the bare tree without inner sectors or multiplicity labels
    //         only remember where they would go
    auto /* CHECKME: type? */ vertex_positions = {} /* FIXME: empty list */;
    /* positions of the ┴ */
    auto /* CHECKME: type? */ num_rows_uncoupled = 5;
    auto /* CHECKME: type? */ num_rows_coupled = 1;
    auto /* CHECKME: type? */ num_rows = num_rows_uncoupled + 2 * num_vertices + num_rows_coupled;
    auto /* CHECKME: type? */ uncoupled_pos = /* FIXME: ListComp: [sum(uncoupled_widths[:i]) + i * uncoupled_padding for i in range(self.num_uncoupled)] */;
    auto /* CHECKME: type? */ num_cols = sum(uncoupled_widths) + num_uncoupled * uncoupled_padding;
    ascii = np.full(std::make_tuple(num_cols, num_rows), " ", py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */;
    // last line: pre_Z_uncoupled
    /* NOTE: Using C++23 std::views::zip (requires -std=c++23)
     * For C++20, use std::ranges::views::zip or implement custom zip.
     * Alternative libraries: range-v3 (ranges::views::zip)
     */
    for (auto [pos, s] : std::views::zip(uncoupled_pos, uncoupled_strs)) {
        /* Multidimensional slice using std::gslice
 * NOTE: Requires ascii_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   ascii_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
ascii[std::gslice(pos * ascii_strides[0] + -1 * ascii_strides[1], std::valarray<std::size_t>{(pos + len(s) - pos), 1}, std::valarray<std::size_t>{ascii_strides[0], ascii_strides[1]})] = list(s);
    }
    // line -2: Z or vertical wires
    /* NOTE: Using C++23 std::views::zip (requires -std=c++23)
     * For C++20, use std::ranges::views::zip or implement custom zip.
     * Alternative libraries: range-v3 (ranges::views::zip)
     */
    for (auto [pos, has_Z] : std::views::zip(uncoupled_pos, are_dual)) {
        // note: arrows are the same no matter if dagger or not
        /* Multidimensional slice using std::gslice
 * NOTE: Requires ascii_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   ascii_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
ascii[std::gslice(pos + 1 * ascii_strides[0] + {-4, -3, -2} * ascii_strides[1], std::valarray<std::size_t>{1, 1}, std::valarray<std::size_t>{ascii_strides[0], ascii_strides[1]})] = has_Z ? {"v", "Z", "^"} : {"v", "│", "v"};
    }
    // line -3: uncoupled
    /* NOTE: Using C++23 std::views::zip (requires -std=c++23)
     * For C++20, use std::ranges::views::zip or implement custom zip.
     * Alternative libraries: range-v3 (ranges::views::zip)
     */
    for (auto [pos, s] : std::views::zip(uncoupled_pos, pre_Z_uncoupled_strs)) {
        /* Multidimensional slice using std::gslice
 * NOTE: Requires ascii_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   ascii_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
ascii[std::gslice(pos * ascii_strides[0] + -5 * ascii_strides[1], std::valarray<std::size_t>{(pos + len(s) - pos), 1}, std::valarray<std::size_t>{ascii_strides[0], ascii_strides[1]})] = list(s);
    }
    // fusion vertices
    auto /* CHECKME: type? */ row = num_rows - 1 - num_rows_uncoupled;
    auto /* CHECKME: type? */ left_wire = uncoupled_pos[0] + 1;
    for (auto n = 0; n < num_vertices; ++n) {
        auto /* CHECKME: type? */ right_wire = uncoupled_pos[n + 1] + 1;
        /* Multidimensional slice using std::gslice
 * NOTE: Requires ascii_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   ascii_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
ascii[std::gslice(right_wire * ascii_strides[0] + row + 1 * ascii_strides[1], std::valarray<std::size_t>{1, (-num_rows_uncoupled - row + 1)}, std::valarray<std::size_t>{ascii_strides[0], ascii_strides[1]})] = "│";
        auto /* CHECKME: type? */ vertex = left_wire + right_wire / 2;
        /* Multidimensional slice using std::gslice
 * NOTE: Requires ascii_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   ascii_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
ascii[std::gslice(left_wire * ascii_strides[0] + row * ascii_strides[1], std::valarray<std::size_t>{1, 1}, std::valarray<std::size_t>{ascii_strides[0], ascii_strides[1]})] = dagger ? "╭" : "╰";
        /* Multidimensional slice using std::gslice
 * NOTE: Requires ascii_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   ascii_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
ascii[std::gslice(left_wire + 1 * ascii_strides[0] + row * ascii_strides[1], std::valarray<std::size_t>{(vertex - left_wire + 1), 1}, std::valarray<std::size_t>{ascii_strides[0], ascii_strides[1]})] = "─";
        /* Multidimensional slice using std::gslice
 * NOTE: Requires ascii_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   ascii_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
ascii[std::gslice(vertex * ascii_strides[0] + row * ascii_strides[1], std::valarray<std::size_t>{1, 1}, std::valarray<std::size_t>{ascii_strides[0], ascii_strides[1]})] = dagger ? "┴" : "┬";
        vertex_positions.append(std::make_tuple(vertex, row));
        /* Multidimensional slice using std::gslice
 * NOTE: Requires ascii_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   ascii_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
ascii[std::gslice(vertex + 1 * ascii_strides[0] + row * ascii_strides[1], std::valarray<std::size_t>{(right_wire - vertex + 1), 1}, std::valarray<std::size_t>{ascii_strides[0], ascii_strides[1]})] = "─";
        /* Multidimensional slice using std::gslice
 * NOTE: Requires ascii_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   ascii_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
ascii[std::gslice(right_wire * ascii_strides[0] + row * ascii_strides[1], std::valarray<std::size_t>{1, 1}, std::valarray<std::size_t>{ascii_strides[0], ascii_strides[1]})] = dagger ? "╮" : "╯";
        /* Multidimensional slice using std::gslice
 * NOTE: Requires ascii_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   ascii_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
ascii[std::gslice(vertex * ascii_strides[0] + row - 1 * ascii_strides[1], std::valarray<std::size_t>{1, 1}, std::valarray<std::size_t>{ascii_strides[0], ascii_strides[1]})] = "│";
        // for next iteration:
        left_wire = vertex;
        row = row - 2;
    }
    /* FIXME: Assert: assert row == 0 */
    auto /* CHECKME: type? */ coupled_pos = left_wire - 1;
    /* Multidimensional slice using std::gslice
 * NOTE: Requires ascii_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   ascii_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
ascii[std::gslice(coupled_pos * ascii_strides[0], std::valarray<std::size_t>{(coupled_pos + len(coupled_str) - coupled_pos), 1}, std::valarray<std::size_t>{ascii_strides[0], ascii_strides[1]})] = list(coupled_str);
    auto /* CHECKME: type? */ left_overhangs = {};
    /* {row: extra_str} */
    /* FIXME: complex zip target pattern */
    if (len(left_overhangs) > 0) {
        auto /* CHECKME: type? */ extra_left = np.full(std::make_tuple(max(/* FIXME: GeneratorExp: (len(s) for s in left_overhangs.values()) */), num_rows), " ", str);
        /* FIXME: for loop:             for row, extra_s in left_overhangs.items():
                extra_left[-len(extra_s) :, row] = list(extra_s) */
    } else {
        extra_left = np.zeros(std::make_tuple(0, num_rows), str);
    }
    if (!symmetry.has_unique_fusion) {
        // need to print multiplicities
        /* FIXME: complex zip target pattern */
    }
    // finalize
    ascii = np.concatenate({extra_left, ascii}, py::arg({keyword.key}) = val) /* CHECKME: keywords ['axis'] */;
    if (!dagger) {
        ascii = /* Multidimensional slice using std::gslice
 * NOTE: Requires ascii_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   ascii_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
ascii[std::gslice(0, std::valarray<std::size_t>{ascii.shape(0), ascii.shape(1)}, std::valarray<std::size_t>{ascii_strides[0], ascii_strides[1] * -1})];
    }
    return ascii;
}

/// Visual representation of the tree as ASCII art.
std::string FusionTree::ascii_diagram(bool dagger) {
    /* CHECKME: converted from following python code:
     * ascii = self._ascii_diagram(dagger=dagger)
     * return '\n'.join(''.join(row) for row in ascii.T)
     */
    auto /* CHECKME: type? */ ascii = _ascii_diagram(py::arg({keyword.key}) = val) /* CHECKME: keywords ['dagger'] */;
    return "
".join(/* FIXME: GeneratorExp: (''.join(row) for row in ascii.T) */);
}

/// Helper function for string representation.
std::string FusionTree::_str_uncoupled_coupled(
    TYPEOF_symmetry symmetry,
    TYPEOF_uncoupled uncoupled,
    TYPEOF_coupled coupled,
    TYPEOF_are_dual are_dual
) {
    /* CHECKME: converted from following python code:
     * uncoupled_1 = []
     * # before Zs
     * uncoupled_2 = []
     * # after Zs
     *         for a, is_dual in zip(uncoupled, are_dual):
     *             a_str = symmetry.sector_str(a)
     *             uncoupled_2.append(a_str)
     *             if is_dual:
     *                 uncoupled_1.append(f'dual({symmetry.sector_str(symmetry.dual_sector(a))})')
     *             else:
     *                 uncoupled_1.append(a_str)
     * before_Z = f'({", ".join(uncoupled_1)})'
     * after_Z = f'({", ".join(uncoupled_2)})'
     * final = symmetry.sector_str(coupled)
     * return f'{before_Z} -> {after_Z} -> {final}'
     */
    auto /* CHECKME: type? */ uncoupled_1 = {} /* FIXME: empty list */;
    /* before Zs */
    auto /* CHECKME: type? */ uncoupled_2 = {} /* FIXME: empty list */;
    /* after Zs */
    /* NOTE: Using C++23 std::views::zip (requires -std=c++23)
     * For C++20, use std::ranges::views::zip or implement custom zip.
     * Alternative libraries: range-v3 (ranges::views::zip)
     */
    for (auto [a, is_dual] : std::views::zip(uncoupled, are_dual)) {
        auto /* CHECKME: type? */ a_str = symmetry.sector_str(a);
        uncoupled_2.append(a_str);
        if (is_dual) {
            uncoupled_1.append(std::format("dual({})", symmetry.sector_str(symmetry.dual_sector(a))));
        } else {
            uncoupled_1.append(a_str);
        }
    }
    auto /* CHECKME: type? */ before_Z = std::format("({})", ", ".join(uncoupled_1));
    auto /* CHECKME: type? */ after_Z = std::format("({})", ", ".join(uncoupled_2));
    auto /* CHECKME: type? */ final = symmetry.sector_str(coupled);
    return std::format("{} -> {} -> {}", before_Z, after_Z, final);
}

/// Bend a leg on a tree-pair, return the resulting linear combination of tree-pairs.
FusionTreePairLinearCombination FusionTree::bend_leg(
    const FusionTree & X,
    const FusionTree & Y,
    bool bend_downward,
    bool do_conj
) {
    /* CHECKME: converted from following python code:
     *         if not bend_downward:
     *             # OPTIMIZE: do it explicitly instead?
     *             # bend_up(dagger(Y) @ X)
     *             # == dagger(dagger(bend_up(dagger(Y) @ X))
     *             # == dagger(bend_down(dagger(dagger(Y) @ X))))
     *             # == dagger(bend_down(dagger(X) @ Y))
     *             # == dagger(sum_i b_i (dagger(X_i) @ Y_i))
     *             # == sum_i conj(b_i) dagger(Y_i) @ X_i
     *             # i.e. we need to swap the order of inputs and invert bend_downward,
     *             # then for the result, swap the trees back and conj the coefficients (invert do_conj)
     *             other = FusionTree.bend_leg(Y, X, bend_downward=True, do_conj=not do_conj)
     *             return {(Y_i, X_i): b_i for (X_i, Y_i), b_i in other.items()}
     * # OPTIMIZE remove input checks?
     * assert Y.symmetry == X.symmetry
     * symmetry = Y.symmetry
     * assert Y.coupled == X.coupled
     * c = Y.coupled
     *         if Y.num_uncoupled == 0:
     *             raise ValueError('No leg to be bent.')
     * is_dual = Y.are_dual[-1]
     *         if Y.num_uncoupled == 1:
     *             X_i = FusionTree.from_empty(symmetry)
     *             Y_i = X.extended(
     *                 new_uncoupled=symmetry.dual_sector(c), mu=0, new_coupled=symmetry.trivial_sector, is_dual=not is_dual
     *             )
     *             b_i = symmetry.sqrt_qdim(c)
     *             if is_dual:
     *                 b_i = b_i * symmetry.frobenius_schur(c)
     *             return {(Y_i, X_i): b_i}
     * X_i, c, mu, z = Y.split_bottom_vertex()
     *         if X.num_uncoupled == 0:
     *             e = X_i.coupled
     *             Y_i = FusionTree.from_sector(symmetry, e, is_dual=not is_dual)
     *             b_i = symmetry.inv_sqrt_qdim(e)
     *             if not is_dual:
     *                 b_i = b_i * symmetry.frobenius_schur(e)
     *             return {(Y_i, X_i): b_i}
     * B = symmetry.b_symbol(X_i.coupled, z, c)
     * chi_z = symmetry.frobenius_schur(z)
     * zbar = symmetry.dual_sector(z)
     * res = {}
     *         for nu in range(B.shape[1]):
     *             b_i = B[mu, nu]
     *             Y_i = X.extended(zbar, nu, X_i.coupled, not is_dual)
     *             if is_dual:
     *                 b_i = b_i * chi_z
     *             if do_conj:
     *                 b_i = np.conj(b_i)
     *             res[Y_i, X_i] = b_i
     * return res
     */
    if (!bend_downward) {
        // OPTIMIZE: do it explicitly instead?
        // bend_up(dagger(Y) @ X)
        // == dagger(dagger(bend_up(dagger(Y) @ X))
        // == dagger(bend_down(dagger(dagger(Y) @ X))))
        // == dagger(bend_down(dagger(X) @ Y))
        // == dagger(sum_i b_i (dagger(X_i) @ Y_i))
        // == sum_i conj(b_i) dagger(Y_i) @ X_i
        // i.e. we need to swap the order of inputs and invert bend_downward,
        // then for the result, swap the trees back and conj the coefficients (invert do_conj)
        auto /* CHECKME: type? */ other = FusionTree.bend_leg(Y, X, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['bend_downward', 'do_conj'] */;
        return /* FIXME: DictComp: {(Y_i, X_i): b_i for (X_i, Y_i), b_i in other.items()} */;
    }
    // OPTIMIZE remove input checks?
    /* FIXME: Assert: assert Y.symmetry == X.symmetry */
    auto /* CHECKME: type? */ symmetry = Y.symmetry;
    /* FIXME: Assert: assert Y.coupled == X.coupled */
    auto /* CHECKME: type? */ c = Y.coupled;
    if (Y.num_uncoupled == 0) {
        throw std::invalid_argument("No leg to be bent.");
    }
    auto /* CHECKME: type? */ is_dual = Y.are_dual[-1];
    if (Y.num_uncoupled == 1) {
        auto /* CHECKME: type? */ X_i = FusionTree.from_empty(symmetry);
        auto /* CHECKME: type? */ Y_i = X.extended(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['new_uncoupled', 'mu', 'new_coupled', 'is_dual'] */;
        auto /* CHECKME: type? */ b_i = symmetry.sqrt_qdim(c);
        if (is_dual) {
            b_i = b_i * symmetry.frobenius_schur(c);
        }
        return {{std::make_tuple(Y_i, X_i), b_i}};
    }
    std::make_tuple(X_i, c, mu, z) = Y.split_bottom_vertex();
    if (X.num_uncoupled == 0) {
        auto /* CHECKME: type? */ e = X_i.coupled;
        Y_i = FusionTree.from_sector(symmetry, e, py::arg({keyword.key}) = val) /* CHECKME: keywords ['is_dual'] */;
        b_i = symmetry.inv_sqrt_qdim(e);
        if (!is_dual) {
            b_i = b_i * symmetry.frobenius_schur(e);
        }
        return {{std::make_tuple(Y_i, X_i), b_i}};
    }
    auto /* CHECKME: type? */ B = symmetry.b_symbol(X_i.coupled, z, c);
    auto /* CHECKME: type? */ chi_z = symmetry.frobenius_schur(z);
    auto /* CHECKME: type? */ zbar = symmetry.dual_sector(z);
    auto /* CHECKME: type? */ res = {};
    for (auto nu = 0; nu < B.shape[1]; ++nu) {
        b_i = /* Multidimensional slice using std::gslice
 * NOTE: Requires B_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   B_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
B[std::gslice(mu * B_strides[0] + nu * B_strides[1], std::valarray<std::size_t>{1, 1}, std::valarray<std::size_t>{B_strides[0], B_strides[1]})];
        Y_i = X.extended(zbar, nu, X_i.coupled, !is_dual);
        if (is_dual) {
            b_i = b_i * chi_z;
        }
        if (do_conj) {
            b_i = np.conj(b_i);
        }
        /* Multidimensional slice using std::gslice
 * NOTE: Requires res_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   res_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
res[std::gslice(Y_i * res_strides[0] + X_i * res_strides[1], std::valarray<std::size_t>{1, 1}, std::valarray<std::size_t>{res_strides[0], res_strides[1]})] = b_i;
    }
    return res;
}

/// Braid a leg on a fusion tree, return the resulting linear combination of trees.
FusionTreeLinearCombination FusionTree::braid(int64 j, bool overbraid, float64 cutoff, bool do_conj) {
    /* CHECKME: converted from following python code:
     * assert 0 <= j < self.num_uncoupled - 1
     *         if j == 0:  # R-move
     *             a, b, mu, c = self.vertex_labels(0)
     *             if overbraid:
     *                 a_i = self.symmetry.r_symbol(a, b, c)[mu]
     *             else:
     *                 a_i = np.conj(self.symmetry.r_symbol(b, a, c)[mu])
     *             if do_conj:
     *                 a_i = np.conj(a_i)
     *             X_i = self.copy(deep=True)
     *             X_i.uncoupled[0] = b
     *             X_i.uncoupled[1] = a
     *             X_i.are_dual[:2] = X_i.are_dual[1::-1]
     *             return {X_i: a_i}
     * # C-move
     * res = {}
     * a, b, mu, e = self.vertex_labels(j - 1)
     * _e, c, nu, d = self.vertex_labels(j)
     * X_new = self.copy(deep=True)
     * X_new.uncoupled[j] = c
     * X_new.uncoupled[j + 1] = b
     * X_new.are_dual[j] = self.are_dual[j + 1]
     * X_new.are_dual[j + 1] = self.are_dual[j]
     *         for f in self.symmetry.fusion_outcomes(a, c):
     *             if not self.symmetry.can_fuse_to(f, b, d):
     *                 continue
     *             if overbraid:
     *                 C_sym = self.symmetry.c_symbol(a, b, c, d, e, f)[mu, nu]
     *             else:
     *                 # underbraid compared to overbraid:
     *                 #  - conj
     *                 #  - b <-> c  [in args of c_symbol(...)]
     *                 #  - e <-> f  [in args of c_symbol(...)]
     *                 #  - (mu,nu) <-> (kappa,lambda)  [by indexing c_symbol(...) differently]
     *                 C_sym = np.conj(self.symmetry.c_symbol(a, c, b, d, f, e)[:, :, mu, nu])
     *             if do_conj:
     *                 C_sym = np.conj(C_sym)
     *             for kappa, C_kappa in enumerate(C_sym):
     *                 for lambda_, a_i in enumerate(C_kappa):
     *                     if abs(a_i) < cutoff:
     *                         continue
     *                     X_i = X_new.copy(deep=True)
     *                     X_i.inner_sectors[j - 1] = f
     *                     X_i.multiplicities[j - 1] = kappa
     *                     X_i.multiplicities[j] = lambda_
     *                     assert X_i not in res  # OPTIMIZE rm check
     *                     res[X_i] = a_i
     * return res
     */
    /* FIXME: Assert: assert 0 <= j < self.num_uncoupled - 1 */
    if (j == 0) {
        /* R-move */
        std::make_tuple(a, b, mu, c) = vertex_labels(0);
        if (overbraid) {
            auto /* CHECKME: type? */ a_i = symmetry.r_symbol(a, b, c)[mu];
        } else {
            a_i = np.conj(symmetry.r_symbol(b, a, c)[mu]);
        }
        if (do_conj) {
            a_i = np.conj(a_i);
        }
        auto /* CHECKME: type? */ X_i = copy(py::arg({keyword.key}) = val) /* CHECKME: keywords ['deep'] */;
        X_i.uncoupled[0] = b;
        X_i.uncoupled[1] = a;
        X_i.are_dual[std::slice(0, 2, 1)] = X_i.are_dual[std::slice(1, (((X_i.are_dual.size() - 1) + -1 - 1) / -1), -1)];
        return {{X_i, a_i}};
    }
    // C-move
    auto /* CHECKME: type? */ res = {};
    std::make_tuple(a, b, mu, e) = vertex_labels(j - 1);
    std::make_tuple(_e, c, nu, d) = vertex_labels(j);
    auto /* CHECKME: type? */ X_new = copy(py::arg({keyword.key}) = val) /* CHECKME: keywords ['deep'] */;
    X_new.uncoupled[j] = c;
    X_new.uncoupled[j + 1] = b;
    X_new.are_dual[j] = are_dual[j + 1];
    X_new.are_dual[j + 1] = are_dual[j];
    /* FIXME: for loop:         for f in self.symmetry.fusion_outcomes(a, c):
            if not self.symmetry.can_fuse_to(f, b, d):
                continue
            if overbraid:
                C_sym = self.symmetry.c_symbol(a, b, c, d, e, f)[mu, nu]
            else:
                # underbraid compared to overbraid:
                #  - conj
                #  - b <-> c  [in args of c_symbol(...)]
                #  - e <-> f  [in args of c_symbol(...)]
                #  - (mu,nu) <-> (kappa,lambda)  [by indexing c_symbol(...) differently]
                C_sym = np.conj(self.symmetry.c_symbol(a, c, b, d, f, e)[:, :, mu, nu])
            if do_conj:
                C_sym = np.conj(C_sym)
            for kappa, C_kappa in enumerate(C_sym):
                for lambda_, a_i in enumerate(C_kappa):
                    if abs(a_i) < cutoff:
                        continue
                    X_i = X_new.copy(deep=True)
                    X_i.inner_sectors[j - 1] = f
                    X_i.multiplicities[j - 1] = kappa
                    X_i.multiplicities[j] = lambda_
                    assert X_i not in res  # OPTIMIZE rm check
                    res[X_i] = a_i */
    return res;
}

/// For the ``n``-th fusion vertex, get the respective sectors.
std::tuple<Sector, Sector, int64, Sector> FusionTree::vertex_labels(int64 n) {
    /* CHECKME: converted from following python code:
     *         if n == 0:
     *             a, b = self.uncoupled[:2]
     *         else:
     *             a = self.inner_sectors[n - 1]
     *             b = self.uncoupled[n + 1]
     *         if n == self.num_vertices - 1:
     *             c = self.coupled
     *         else:
     *             c = self.inner_sectors[n]
     * return a, b, self.multiplicities[n], c
     */
    if (n == 0) {
        std::make_tuple(a, b) = uncoupled[std::slice(0, 2, 1)];
    } else {
        auto /* CHECKME: type? */ a = inner_sectors[n - 1];
        auto /* CHECKME: type? */ b = uncoupled[n + 1];
    }
    if (n == num_vertices - 1) {
        auto /* CHECKME: type? */ c = coupled;
    } else {
        c = inner_sectors[n];
    }
    return std::make_tuple(a, b, multiplicities[n], c);
}

/// Update the multiplicity and the three sectors around the ``n``-th vertex.
FusionTree FusionTree::modify_vertex_labels(int64 n, Sector a, Sector b, int64 mu, Sector c, bool copy) {
    /* CHECKME: converted from following python code:
     *         if copy:
     *             return self.copy(deep=True).modify_vertex_labels(n, a=a, b=b, mu=mu, c=c, copy=False)
     *         if n == 0:
     *             self.uncoupled[0] = a
     *         else:
     *             self.inner_sectors[n - 1] = a
     * self.uncoupled[n + 1] = b
     *         if n == self.num_vertices - 1:
     *             self.coupled = c
     *         else:
     *             self.inner_sectors[n] = c
     * self.multiplicities[n] = mu
     * return self
     */
    if (copy) {
        return copy(py::arg({keyword.key}) = val) /* CHECKME: keywords ['deep'] */.modify_vertex_labels(n, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['a', 'b', 'mu', 'c', 'copy'] */;
    }
    if (n == 0) {
        uncoupled[0] = a;
    } else {
        inner_sectors[n - 1] = a;
    }
    uncoupled[n + 1] = b;
    if (n == num_vertices - 1) {
        coupled = c;
    } else {
        inner_sectors[n] = c;
    }
    multiplicities[n] = mu;
    return self  /* FIXME: standalone self reference */;
}

str FusionTree::__str__() {
    /* CHECKME: converted from following python code:
     * ascii = self._ascii_diagram(dagger=False)
     * res = f'<FusionTree   symmetry: {self.symmetry!s}>'
     *         for row in ascii.T:
     *             res = res + '\n    |   ' + ''.join(row)
     * return res
     */
    auto /* CHECKME: type? */ ascii = _ascii_diagram(py::arg({keyword.key}) = val) /* CHECKME: keywords ['dagger'] */;
    auto /* CHECKME: type? */ res = std::format("<FusionTree   symmetry: {}>", symmetry);
    /* FIXME: for loop:         for row in ascii.T:
            res = res + '\n    |   ' + ''.join(row) */
    return res;
}

str FusionTree::__repr__() {
    /* CHECKME: converted from following python code:
     * inner = str(self.inner_sectors).replace('\n', ',')
     * uncoupled = str(self.uncoupled).replace('\n', ',')
     *         return (
     *             f'FusionTree({self.symmetry}, {uncoupled}, {self.are_dual}, coupled={self.coupled}, '
     *             f'inner_sectors={inner}, multiplicities={self.multiplicities})'
     *         )
     */
    auto /* CHECKME: type? */ inner = str(inner_sectors).replace("
", ",");
    auto /* CHECKME: type? */ uncoupled = str(uncoupled).replace("
", ",");
    return std::format("FusionTree({}, {}, {}, coupled={}, inner_sectors={}, multiplicities={})", symmetry, uncoupled, are_dual, coupled, inner, multiplicities);
}

/// Get the matrix elements of the map as a backend Block.
BlockBackend::BlockPtr FusionTree::to_dense_block(
    BlockBackend * backend,
    std::optional<Dtype> dtype,
    bool understood_braiding
) {
    /* CHECKME: converted from following python code:
     *         if not self.symmetry.can_be_dropped:
     *             raise SymmetryError(f'Can not convert to block for symmetry {self.symmetry}')
     *         if not self.symmetry.has_trivial_braid and not understood_braiding:
     *             msg = (
     *                 'If the symmetry has non-trivial braids, dense block representations do not '
     *                 'consistently reproduce the braiding statistics. Make sure you understand what '
     *                 'that means (read the docstring of from_dense_block). Then you can disable '
     *                 'this error by setting ``understood_braiding=True``.'
     *             )
     *             raise SymmetryError(msg)
     *         if backend is None:
     *             block_backend = NumpyBlockBackend.from_factory('cpu')
     *         else:
     *             block_backend = backend.block_backend
     *         if dtype is None:
     *             dtype = self.symmetry.fusion_tensor_dtype
     * # handle special cases of small trees
     *         if self.num_uncoupled == 0:
     *             # must be identity on the trivial sector. But since there is no uncoupled sector,
     *             # do not even give it an axis.
     *             return block_backend.ones_block([1], dtype=dtype)
     *         if self.num_uncoupled == 1:
     *             if self.are_dual[0]:
     *                 Z = self.symmetry.Z_iso(self.symmetry.dual_sector(self.uncoupled[0]))
     *                 # [m_c, m_a1] -> need to transpose!
     *                 return block_backend.block_from_numpy(Z.T, dtype=dtype)
     *             else:
     *                 dim_c = self.symmetry.sector_dim(self.coupled)
     *                 return block_backend.eye_block([dim_c], dtype)
     *         if self.num_uncoupled == 2:
     *             mu = self.multiplicities[0]
     *             # OPTIMIZE should we offer a symmetry function to compute only the mu slice?
     *             X = self.symmetry.fusion_tensor(*self.uncoupled, self.coupled, *self.are_dual)[mu]
     *             return block_backend.block_from_numpy(X, dtype)  # [a0, a1, c]
     * # larger trees: iterate over vertices
     * mu0 = self.multiplicities[0]
     *         X0 = self.symmetry.fusion_tensor(
     *             self.uncoupled[0], self.uncoupled[1], self.inner_sectors[0], Z_a=self.are_dual[0], Z_b=self.are_dual[1]
     *         )[mu0]
     * res = block_backend.block_from_numpy(X0, dtype)
     * # [a0, a1, i0]
     *         for vertex in range(1, self.num_vertices):
     *             mu = self.multiplicities[vertex]
     *             a = self.inner_sectors[vertex - 1]
     *             b = self.uncoupled[vertex + 1]
     *             c = self.inner_sectors[vertex] if vertex < self.num_inner_edges else self.coupled
     *             X = self.symmetry.fusion_tensor(a, b, c, Z_b=self.are_dual[vertex + 1])[mu]
     *             X_block = block_backend.block_from_numpy(X, dtype)
     *             #  [a0, a1, ..., an, i{n-1}] & [i{n-1}, a{n+1}, in] -> [a0, a1, ..., a{n+1}, in]
     *             res = block_backend.tdot(res, X_block, [-1], [0])
     * return res
     */
    if (!symmetry.can_be_dropped) {
        throw std::runtime_error(std::format("Can not convert to block for symmetry {}", symmetry));
    }
    if (!symmetry.has_trivial_braid && !understood_braiding) {
        auto /* CHECKME: type? */ msg = "If the symmetry has non-trivial braids, dense block representations do not consistently reproduce the braiding statistics. Make sure you understand what that means (read the docstring of from_dense_block). Then you can disable this error by setting ``understood_braiding=True``.";
        throw std::runtime_error(msg);
    }
    if (backend == py::none()) {
        auto /* CHECKME: type? */ block_backend = NumpyBlockBackend.from_factory("cpu");
    } else {
        block_backend = backend.block_backend;
    }
    if (dtype == py::none()) {
        dtype = symmetry.fusion_tensor_dtype;
    }
    // handle special cases of small trees
    if (num_uncoupled == 0) {
        // must be identity on the trivial sector. But since there is no uncoupled sector,
        // do not even give it an axis.
        return block_backend.ones_block({1}, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */;
    }
    if (num_uncoupled == 1) {
        if (are_dual[0]) {
            auto /* CHECKME: type? */ Z = symmetry.Z_iso(symmetry.dual_sector(uncoupled[0]));
            // [m_c, m_a1] -> need to transpose!
            return block_backend.block_from_numpy(Z.T, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */;
        } else {
            auto /* CHECKME: type? */ dim_c = symmetry.sector_dim(coupled);
            return block_backend.eye_block({dim_c}, dtype);
        }
    }
    if (num_uncoupled == 2) {
        auto /* CHECKME: type? */ mu = multiplicities[0];
        // OPTIMIZE should we offer a symmetry function to compute only the mu slice?
        auto /* CHECKME: type? */ X = symmetry.fusion_tensor(/* FIXME: Starred: *self.uncoupled */, coupled, /* FIXME: Starred: *self.are_dual */)[mu];
        return block_backend.block_from_numpy(X, dtype);
        /* [a0, a1, c] */
    }
    // larger trees: iterate over vertices
    auto /* CHECKME: type? */ mu0 = multiplicities[0];
    auto /* CHECKME: type? */ X0 = symmetry.fusion_tensor(uncoupled[0], uncoupled[1], inner_sectors[0], py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['Z_a', 'Z_b'] */[mu0];
    auto /* CHECKME: type? */ res = block_backend.block_from_numpy(X0, dtype);
    /* [a0, a1, i0] */
    for (auto vertex = 1; vertex < num_vertices; ++vertex) {
        mu = multiplicities[vertex];
        auto /* CHECKME: type? */ a = inner_sectors[vertex - 1];
        auto /* CHECKME: type? */ b = uncoupled[vertex + 1];
        auto /* CHECKME: type? */ c = vertex < num_inner_edges ? inner_sectors[vertex] : coupled;
        X = symmetry.fusion_tensor(a, b, c, py::arg({keyword.key}) = val) /* CHECKME: keywords ['Z_b'] */[mu];
        auto /* CHECKME: type? */ X_block = block_backend.block_from_numpy(X, dtype);
        //  [a0, a1, ..., an, i{n-1}] & [i{n-1}, a{n+1}, in] -> [a0, a1, ..., a{n+1}, in]
        res = block_backend.tdot(res, X_block, {-1}, {0});
    }
    return res;
}

/// Return a shallow (or deep) copy.
FusionTree FusionTree::copy(bool deep) {
    /* CHECKME: converted from following python code:
     *         if deep:
     *             return FusionTree(
     *                 self.symmetry,
     *                 self.uncoupled.copy(),
     *                 self.coupled.copy(),
     *                 self.are_dual.copy(),
     *                 self.inner_sectors.copy(),
     *                 self.multiplicities.copy(),
     *             )
     *         return FusionTree(
     *             self.symmetry, self.uncoupled, self.coupled, self.are_dual, self.inner_sectors, self.multiplicities
     *         )
     */
    if (deep) {
        return FusionTree(symmetry, uncoupled.copy(), coupled.copy(), are_dual.copy(), inner_sectors.copy(), multiplicities.copy());
    }
    return FusionTree(symmetry, uncoupled, coupled, are_dual, inner_sectors, multiplicities);
}

/// A new tree, from adding a new fusion node at the bottom, below the coupled sector.
FusionTree FusionTree::extended(Sector new_uncoupled, int64 mu, Sector new_coupled, bool is_dual) {
    /* CHECKME: converted from following python code:
     *         if self.num_uncoupled == 0:
     *             assert mu == 0
     *             multiplicities = []
     *         else:
     *             multiplicities = np.append(self.multiplicities, mu)
     *         if self.num_uncoupled < 2:
     *             # result has one vertex, and thus no inner sectors
     *             inner_sectors = self.inner_sectors
     *         else:
     *             inner_sectors = concat_sector_arrays(self.inner_sectors, sector_array_from_sector(self.coupled))
     *         return FusionTree(
     *             self.symmetry,
     *             uncoupled=concat_sector_arrays(self.uncoupled, sector_array_from_sector(as_sector(new_uncoupled))),
     *             coupled=new_coupled,
     *             are_dual=np.append(self.are_dual, is_dual),
     *             inner_sectors=inner_sectors,
     *             multiplicities=multiplicities,
     *         )
     */
    if (num_uncoupled == 0) {
        /* FIXME: Assert: assert mu == 0 */
        auto /* CHECKME: type? */ multiplicities = {} /* FIXME: empty list */;
    } else {
        multiplicities = np.append(multiplicities, mu);
    }
    if (num_uncoupled < 2) {
        // result has one vertex, and thus no inner sectors
        auto /* CHECKME: type? */ inner_sectors = inner_sectors;
    } else {
        inner_sectors = concat_sector_arrays(inner_sectors, sector_array_from_sector(coupled));
    }
    return FusionTree(symmetry, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['uncoupled', 'coupled', 'are_dual', 'inner_sectors', 'multiplicities'] */;
}

/// Insert a tree `t2` above the first uncoupled sector.
FusionTree FusionTree::insert(const FusionTree & t2) {
    /* CHECKME: converted from following python code:
     *         return FusionTree(
     *             symmetry=self.symmetry,
     *             uncoupled=concat_sector_arrays(t2.uncoupled, self.uncoupled[1:]),
     *             coupled=self.coupled,
     *             are_dual=np.concatenate([t2.are_dual, self.are_dual[1:]]),
     *             inner_sectors=_concat_sector_arrays(t2.inner_sectors, self.uncoupled[:1], self.inner_sectors),
     *             multiplicities=np.concatenate([t2.multiplicities, self.multiplicities]),
     *         )
     */
    return FusionTree(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['symmetry', 'uncoupled', 'coupled', 'are_dual', 'inner_sectors', 'multiplicities'] */;
}

/// Insert a tree `t2` above the `n`-th uncoupled sector.
FusionTreeLinearCombination FusionTree::insert_at(int64 n, const FusionTree & t2, float64 eps) {
    /* CHECKME: converted from following python code:
     * assert self.symmetry == t2.symmetry
     * assert self.uncoupled[n] == t2.coupled
     * assert not self.are_dual[n]
     *         if t2.num_uncoupled == 0:
     *             # special case: empty tree with trivial coupled sector
     *             # -> effectively remove self.uncoupled[n] (replace with empty set of sectors)
     *             res_unc = concat_sector_arrays(self.uncoupled[:n], self.uncoupled[n + 1 :])
     *             res_dual = np.concatenate([self.are_dual[:n], self.are_dual[n + 1 :]])
     *             idx = max(0, n - 1)
     *             res_inners = concat_sector_arrays(self.inner_sectors[:idx], self.inner_sectors[idx + 1 :])
     *             res_mults = np.concatenate([self.multiplicities[:idx], self.multiplicities[idx + 1 :]])
     *             res = FusionTree(self.symmetry, res_unc, self.coupled, res_dual, res_inners, res_mults)
     *             return {res: 1}
     *         if t2.num_vertices == 0:
     *             # t2 has no actual fusion, it is either identity or a Z iso
     *             if t2.are_dual[0]:
     *                 res = self.copy()
     *                 res.are_dual = self.are_dual.copy()
     *                 res.are_dual[n] = True
     *                 return {res: 1}
     *             return {self: 1}
     *         if self.num_vertices == 0:
     *             return {t2: 1}
     *         if n == 0:
     *             # result is already a canonical tree -> no need to do F moves
     *             return {self.insert(t2): 1}
     * # should be more efficient than using recursion
     * sym = self.symmetry
     * coefficients = {}
     * new_unc = _concat_sector_arrays(self.uncoupled[:n], t2.uncoupled, self.uncoupled[n + 1 :])
     * new_dual = np.concatenate([self.are_dual[:n], t2.are_dual, self.are_dual[n + 1 :]])
     * new_inners_left = self.inner_sectors[: n - 1]
     * new_inners_right = self.inner_sectors[n - 1 :]
     * new_multis_left = self.multiplicities[: n - 1]
     * new_multis_right = self.multiplicities[n:]
     * # build the remaining parts (inner and multiplicities) from the right
     * a = self.uncoupled[0] if len(new_inners_left) == 0 else new_inners_left[-1]
     * d_initial = self.coupled if n == self.num_uncoupled - 1 else new_inners_right[0]
     * tree_parts = {(tuple(), (self.multiplicities[n - 1],)): 1}
     *         for i in range(t2.num_uncoupled - 1, 0, -1):
     *             new_tree_parts = {}  # contains new inner_sectors and multiplicities
     *             for (inners, multis), amplitude in tree_parts.items():
     *                 b = t2.inner_sectors[i - 2] if i > 1 else t2.uncoupled[0]
     *                 c = t2.uncoupled[i]
     *                 d = as_sector(inners[0]) if len(inners) > 0 else d_initial
     *                 e = t2.coupled if len(inners) == 0 else t2.inner_sectors[i - 1]
     *                 multi = t2.multiplicities[i - 1]
     *                 for f in sym.fusion_outcomes(a, b):
     *                     if not sym.can_fuse_to(f, c, d):
     *                         continue
     *                     fs = sym._f_symbol(a, b, c, d, e, f)[multi, multis[0], :, :]
     *                     for (kap, lam), factor in np.ndenumerate(fs):
     *                         if abs(factor) < eps:
     *                             continue
     *                         new_parts = ((tuple(f), *inners), (kap, lam, *multis[1:]))
     *                         if new_parts in new_tree_parts:
     *                             new_tree_parts[new_parts] += amplitude * factor
     *                         else:
     *                             new_tree_parts[new_parts] = amplitude * factor
     *             tree_parts = new_tree_parts
     *         for (inners, multis), amplitude in tree_parts.items():
     *             inners = as_sector_array(inners, sector_ind_len=sym.sector_ind_len)
     *             new_inners = _concat_sector_arrays(new_inners_left, inners, new_inners_right)
     *             new_multis = np.concatenate([new_multis_left, multis, new_multis_right])
     *             new_tree = FusionTree(sym, new_unc, self.coupled, new_dual, new_inners, new_multis)
     *             coefficients[new_tree] = amplitude
     * return coefficients
     */
    /* FIXME: Assert: assert self.symmetry == t2.symmetry */
    /* FIXME: Assert: assert self.uncoupled[n] == t2.coupled */
    /* FIXME: Assert: assert not self.are_dual[n] */
    if (t2.num_uncoupled == 0) {
        // special case: empty tree with trivial coupled sector
        // -> effectively remove self.uncoupled[n] (replace with empty set of sectors)
        auto /* CHECKME: type? */ res_unc = concat_sector_arrays(uncoupled[std::slice(0, n, 1)], uncoupled[std::slice(n + 1, (uncoupled.size() - n + 1), 1)]);
        auto /* CHECKME: type? */ res_dual = np.concatenate({are_dual[std::slice(0, n, 1)], are_dual[std::slice(n + 1, (are_dual.size() - n + 1), 1)]});
        auto /* CHECKME: type? */ idx = max(0, n - 1);
        auto /* CHECKME: type? */ res_inners = concat_sector_arrays(inner_sectors[std::slice(0, idx, 1)], inner_sectors[std::slice(idx + 1, (inner_sectors.size() - idx + 1), 1)]);
        auto /* CHECKME: type? */ res_mults = np.concatenate({multiplicities[std::slice(0, idx, 1)], multiplicities[std::slice(idx + 1, (multiplicities.size() - idx + 1), 1)]});
        auto /* CHECKME: type? */ res = FusionTree(symmetry, res_unc, coupled, res_dual, res_inners, res_mults);
        return {{res, 1}};
    }
    if (t2.num_vertices == 0) {
        // t2 has no actual fusion, it is either identity or a Z iso
        if (t2.are_dual[0]) {
            res = copy();
            res.are_dual = are_dual.copy();
            res.are_dual[n] = true;
            return {{res, 1}};
        }
        return {{self  /* FIXME: standalone self reference */, 1}};
    }
    if (num_vertices == 0) {
        return {{t2, 1}};
    }
    if (n == 0) {
        // result is already a canonical tree -> no need to do F moves
        return {{insert(t2), 1}};
    }
    // should be more efficient than using recursion
    auto /* CHECKME: type? */ sym = symmetry;
    auto /* CHECKME: type? */ coefficients = {};
    auto /* CHECKME: type? */ new_unc = _concat_sector_arrays(uncoupled[std::slice(0, n, 1)], t2.uncoupled, uncoupled[std::slice(n + 1, (uncoupled.size() - n + 1), 1)]);
    auto /* CHECKME: type? */ new_dual = np.concatenate({are_dual[std::slice(0, n, 1)], t2.are_dual, are_dual[std::slice(n + 1, (are_dual.size() - n + 1), 1)]});
    auto /* CHECKME: type? */ new_inners_left = inner_sectors[std::slice(0, n - 1, 1)];
    auto /* CHECKME: type? */ new_inners_right = inner_sectors[std::slice(n - 1, (inner_sectors.size() - n - 1), 1)];
    auto /* CHECKME: type? */ new_multis_left = multiplicities[std::slice(0, n - 1, 1)];
    auto /* CHECKME: type? */ new_multis_right = multiplicities[std::slice(n, (multiplicities.size() - n), 1)];
    // build the remaining parts (inner and multiplicities) from the right
    auto /* CHECKME: type? */ a = len(new_inners_left) == 0 ? uncoupled[0] : new_inners_left[-1];
    auto /* CHECKME: type? */ d_initial = n == num_uncoupled - 1 ? coupled : new_inners_right[0];
    auto /* CHECKME: type? */ tree_parts = {{std::make_tuple(tuple(), std::make_tuple(multiplicities[n - 1])), 1}};
    for (auto i = t2.num_uncoupled - 1; i < 0; i += -1) {
        auto /* CHECKME: type? */ new_tree_parts = {};
        /* contains new inner_sectors and multiplicities */
        /* FIXME: for loop:             for (inners, multis), amplitude in tree_parts.items():
                b = t2.inner_sectors[i - 2] if i > 1 else t2.uncoupled[0]
                c = t2.uncoupled[i]
                d = as_sector(inners[0]) if len(inners) > 0 else d_initial
                e = t2.coupled if len(inners) == 0 else t2.inner_sectors[i - 1]
                multi = t2.multiplicities[i - 1]
                for f in sym.fusion_outcomes(a, b):
                    if not sym.can_fuse_to(f, c, d):
                        continue
                    fs = sym._f_symbol(a, b, c, d, e, f)[multi, multis[0], :, :]
                    for (kap, lam), factor in np.ndenumerate(fs):
                        if abs(factor) < eps:
                            continue
                        new_parts = ((tuple(f), *inners), (kap, lam, *multis[1:]))
                        if new_parts in new_tree_parts:
                            new_tree_parts[new_parts] += amplitude * factor
                        else:
                            new_tree_parts[new_parts] = amplitude * factor */
        tree_parts = new_tree_parts;
    }
    /* FIXME: for loop:         for (inners, multis), amplitude in tree_parts.items():
            inners = as_sector_array(inners, sector_ind_len=sym.sector_ind_len)
            new_inners = _concat_sector_arrays(new_inners_left, inners, new_inners_right)
            new_multis = np.concatenate([new_multis_left, multis, new_multis_right])
            new_tree = FusionTree(sym, new_unc, self.coupled, new_dual, new_inners, new_multis)
            coefficients[new_tree] = amplitude */
    return coefficients;
}

/// Outer product with another tree.
FusionTreeLinearCombination FusionTree::outer(const FusionTree & right_tree, float64 eps) {
    /* CHECKME: converted from following python code:
     * # trivial cases
     *         if self.num_uncoupled == 0:
     *             return {right_tree: 1}
     *         if right_tree.num_uncoupled == 0:
     *             return {self: 1}
     * # use self.insert_at(right_tree) -> construct new tree with
     * # right_tree.coupled as uncoupled sector at the end
     * sym = self.symmetry
     * res = {}
     * unc = concat_sector_arrays(self.uncoupled, sector_array_from_sector(right_tree.coupled))
     * dual = np.concatenate([self.are_dual, [False]])
     *         if self.num_uncoupled <= 1:
     *             inner = sym.empty_sector_array
     *         else:
     *             inner = concat_sector_arrays(self.inner_sectors, sector_array_from_sector(self.coupled))
     *         for new_coupled in sym.fusion_outcomes(self.coupled, right_tree.coupled):
     *             for m in range(sym._n_symbol(self.coupled, right_tree.coupled, new_coupled)):
     *                 multi = np.concatenate([self.multiplicities, [m]])
     *                 tree = FusionTree(
     *                     symmetry=sym,
     *                     uncoupled=unc,
     *                     coupled=new_coupled,
     *                     are_dual=dual,
     *                     inner_sectors=inner,
     *                     multiplicities=multi,
     *                 )
     *                 res.update(tree.insert_at(self.num_uncoupled, right_tree, eps=eps))
     * return res
     */
    // trivial cases
    if (num_uncoupled == 0) {
        return {{right_tree, 1}};
    }
    if (right_tree.num_uncoupled == 0) {
        return {{self  /* FIXME: standalone self reference */, 1}};
    }
    // use self.insert_at(right_tree) -> construct new tree with
    // right_tree.coupled as uncoupled sector at the end
    auto /* CHECKME: type? */ sym = symmetry;
    auto /* CHECKME: type? */ res = {};
    auto /* CHECKME: type? */ unc = concat_sector_arrays(uncoupled, sector_array_from_sector(right_tree.coupled));
    auto /* CHECKME: type? */ dual = np.concatenate({are_dual, {false}});
    if (num_uncoupled <= 1) {
        auto /* CHECKME: type? */ inner = sym.empty_sector_array;
    } else {
        inner = concat_sector_arrays(inner_sectors, sector_array_from_sector(coupled));
    }
    /* FIXME: for loop:         for new_coupled in sym.fusion_outcomes(self.coupled, right_tree.coupled):
            for m in range(sym._n_symbol(self.coupled, right_tree.coupled, new_coupled)):
                multi = np.concatenate([self.multiplicities, [m]])
                tree = FusionTree(
                    symmetry=sym,
                    uncoupled=unc,
                    coupled=new_coupled,
                    are_dual=dual,
                    inner_sectors=inner,
                    multiplicities=multi,
                )
                res.update(tree.insert_at(self.num_uncoupled, right_tree, eps=eps)) */
    return res;
}

/// Split into two separate fusion trees.
std::pair<FusionTree, FusionTree> FusionTree::split(int64 n) {
    /* CHECKME: converted from following python code:
     * n = int(n)
     *         if n < 2:
     *             raise ValueError('Left tree has no vertices (n < 2)')
     *         if n >= self.num_uncoupled:
     *             raise ValueError('Right tree has no vertices (n >= num_uncoupled)')
     * cut_sector = self.inner_sectors[n - 2]
     *         t1 = FusionTree(
     *             self.symmetry,
     *             uncoupled=self.uncoupled[:n],
     *             coupled=cut_sector,
     *             are_dual=self.are_dual[:n],
     *             inner_sectors=self.inner_sectors[: n - 2],
     *             multiplicities=self.multiplicities[: n - 1],
     *         )
     *         t2 = FusionTree(
     *             self.symmetry,
     *             uncoupled=concat_sector_arrays(sector_array_from_sector(cut_sector), self.uncoupled[n:]),
     *             coupled=self.coupled,
     *             are_dual=np.insert(self.are_dual[n:], 0, False),
     *             inner_sectors=self.inner_sectors[n - 1 :],
     *             multiplicities=self.multiplicities[n - 1 :],
     *         )
     * return t1, t2
     */
    n = int(n);
    if (n < 2) {
        throw std::invalid_argument("Left tree has no vertices (n < 2)");
    }
    if (n >= num_uncoupled) {
        throw std::invalid_argument("Right tree has no vertices (n >= num_uncoupled)");
    }
    auto /* CHECKME: type? */ cut_sector = inner_sectors[n - 2];
    auto /* CHECKME: type? */ t1 = FusionTree(symmetry, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['uncoupled', 'coupled', 'are_dual', 'inner_sectors', 'multiplicities'] */;
    auto /* CHECKME: type? */ t2 = FusionTree(symmetry, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['uncoupled', 'coupled', 'are_dual', 'inner_sectors', 'multiplicities'] */;
    return std::make_tuple(t1, t2);
}

/// Split off the bottom vertex.
std::tuple<FusionTree, Sector, int64, Sector> FusionTree::split_bottom_vertex() {
    /* CHECKME: converted from following python code:
     *         if self.num_uncoupled == 0:
     *             raise ValueError('Cant split empty tree')
     *         if self.num_uncoupled == 1:
     *             return FusionTree.from_empty(self.symmetry), self.coupled, 0, self.coupled
     *         if self.num_uncoupled == 2:
     *             rest_tree = FusionTree.from_sector(self.symmetry, self.uncoupled[0], is_dual=self.are_dual[0])
     *             return rest_tree, self.coupled, self.multiplicities[0], self.uncoupled[-1]
     *         rest_tree = FusionTree(
     *             self.symmetry,
     *             uncoupled=self.uncoupled[:-1],
     *             coupled=self.inner_sectors[-1],
     *             are_dual=self.are_dual[:-1],
     *             inner_sectors=self.inner_sectors[:-1],
     *             multiplicities=self.multiplicities[:-1],
     *         )
     * return rest_tree, self.coupled, self.multiplicities[-1], self.uncoupled[-1]
     */
    if (num_uncoupled == 0) {
        throw std::invalid_argument("Cant split empty tree");
    }
    if (num_uncoupled == 1) {
        return std::make_tuple(FusionTree.from_empty(symmetry), coupled, 0, coupled);
    }
    if (num_uncoupled == 2) {
        auto /* CHECKME: type? */ rest_tree = FusionTree.from_sector(symmetry, uncoupled[0], py::arg({keyword.key}) = val) /* CHECKME: keywords ['is_dual'] */;
        return std::make_tuple(rest_tree, coupled, multiplicities[0], uncoupled[-1]);
    }
    rest_tree = FusionTree(symmetry, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['uncoupled', 'coupled', 'are_dual', 'inner_sectors', 'multiplicities'] */;
    return std::make_tuple(rest_tree, coupled, multiplicities[-1], uncoupled[-1]);
}

/// Twist some legs above a tree, return the resulting linear combination of trees.
FusionTreeLinearCombination FusionTree::twist(const std::vector<int64> & idcs, bool overtwist) {
    /* CHECKME: converted from following python code:
     *         if self.symmetry.has_trivial_braid:
     *             # twists are trivial
     *             return {self: 1}
     *         if len(idcs) == 0:
     *             return {self: 1}
     *         if len(idcs) == 1:
     *             # single wire twist
     *             i = to_valid_idx(idcs[0], self.num_uncoupled)
     *             theta = self.symmetry.topological_twist(self.uncoupled[i])
     *             if not overtwist:
     *                 theta = np.conj(theta)
     *             return {self: theta}
     * idcs = sorted([to_valid_idx(i, self.num_uncoupled) for i in idcs])
     * assert all(i2 > i1 for i2, i1 in zip(idcs[1:], idcs[:-1])), 'duplicate idcs'
     *         if len(idcs) == self.num_uncoupled:
     *             # we can just slide the whole tree through the twist and end up with a twist of the
     *             # coupled sector
     *             theta = self.symmetry.topological_twist(self.coupled)
     *             if not overtwist:
     *                 theta = np.conj(theta)
     *             return {self: theta}
     *         if idcs == [*range(len(idcs))]:
     *             # we can slide a subtree through the twist and get a twist on an inner sector
     *             a = self.inner_sectors[idcs[-1] - 1]
     *             # note: have already excluded the special cases where this index would be out of bounds
     *             theta = self.symmetry.topological_twist(a)
     *             if not overtwist:
     *                 theta = np.conj(theta)
     *             return {self: theta}
     * # Not sure what the best strategy is in the general case.
     * # Option A: we could do the twist on range(i, j) as:
     * #           - twist on range(j)
     * #           - inverse twist on range(i)
     * #           - some extra braiding
     * # Option B: break it down recursively
     * #           - twist range(i, mid)
     * #           - twist range(mid, j)
     * #           - braid twice
     * raise NotImplementedError
     */
    if (symmetry.has_trivial_braid) {
        // twists are trivial
        return {{self  /* FIXME: standalone self reference */, 1}};
    }
    if (len(idcs) == 0) {
        return {{self  /* FIXME: standalone self reference */, 1}};
    }
    if (len(idcs) == 1) {
        // single wire twist
        auto /* CHECKME: type? */ i = to_valid_idx(idcs[0], num_uncoupled);
        auto /* CHECKME: type? */ theta = symmetry.topological_twist(uncoupled[i]);
        if (!overtwist) {
            theta = np.conj(theta);
        }
        return {{self  /* FIXME: standalone self reference */, theta}};
    }
    idcs = sorted(/* FIXME: ListComp: [to_valid_idx(i, self.num_uncoupled) for i in idcs] */);
    /* FIXME: Assert: assert all(i2 > i1 for i2, i1 in zip(idcs[1:], idcs[:-1])), 'duplicate idcs' */
    if (len(idcs) == num_uncoupled) {
        // we can just slide the whole tree through the twist and end up with a twist of the
        // coupled sector
        theta = symmetry.topological_twist(coupled);
        if (!overtwist) {
            theta = np.conj(theta);
        }
        return {{self  /* FIXME: standalone self reference */, theta}};
    }
    if (idcs == {/* FIXME: Starred: *range(len(idcs)) */}) {
        // we can slide a subtree through the twist and get a twist on an inner sector
        auto /* CHECKME: type? */ a = inner_sectors[idcs[-1] - 1];
        // note: have already excluded the special cases where this index would be out of bounds
        theta = symmetry.topological_twist(a);
        if (!overtwist) {
            theta = np.conj(theta);
        }
        return {{self  /* FIXME: standalone self reference */, theta}};
    }
    // Not sure what the best strategy is in the general case.
    // Option A: we could do the twist on range(i, j) as:
    //           - twist on range(j)
    //           - inverse twist on range(i)
    //           - some extra braiding
    // Option B: break it down recursively
    //           - twist range(i, mid)
    //           - twist range(mid, j)
    //           - braid twice
    throw std::logic_error("");
}

std::size_t FusionTree::hash() {
    // FIXME: implement
}

bool FusionTree::operator<(const FusionTree & other) {
    // FIXME: implement
}

std::string FusionTree::str_uncoupled_coupled(
    const Symmetry & symmetry,
    const SectorArray & uncoupled,
    Sector coupled,
    const std::vector<std::uint8_t> & are_dual
) {
    // FIXME: implement
}

std::string FusionTree::str() {
    // FIXME: implement
}

std::string FusionTree::repr() {
    // FIXME: implement
}

std::vector<std::vector<char>> FusionTree::ascii_diagram_chars(
    bool dagger,
    int uncoupled_padding,
    int inner_sector_padding
) {
    // FIXME: implement
}
