"""TeNPy ``np_conserved`` U(1) spin-1/2 example, rewritten for Cyten.

Compare with ``examples/userguide/b_npc_arrays.py`` in TeNPy.
"""

import numpy as np

import cyten as ct

# U(1) generated by Sz. Sectors are the 2 Sz values of the local basis |↑⟩, |↓⟩.
sym = ct.u1_symmetry
p = ct.ElementarySpace.from_basis(sym, [[1], [-1]])

# Sz conserves the charge, so it is a SymmetricTensor (a map p → p).
Sz = ct.tensor([[0.5, 0.0], [0.0, -0.5]], codomain=[p], domain=[p], labels=['p', 'p*'])

# S+ raises Sz by 2 and is therefore *not* a SymmetricTensor.
# Represent it as a ChargedTensor with a one-dimensional charge space of sector +2.
charge_plus = ct.ElementarySpace.from_defining_sectors(sym, [[2]])
Sp = ct.ChargedTensor.from_dense_block(
    [[0.0, 1.0], [0.0, 0.0]],
    codomain=[p],
    domain=[p],
    charge=charge_plus,
    labels=['p', 'p*'],
)
print('Sp =\n', Sp.to_numpy())

# The two-site Heisenberg coupling conserves *total* Sz, so it is symmetric.
# Dense blocks follow Tensor.legs: first the codomain, then the domain in reverse.
# For domain == [p0, p1] that means axes (p0_out, p1_out, p1_in, p0_in).
H_mat = np.array(
    [
        [0.25, 0.00, 0.00, 0.00],
        [0.00, -0.25, 0.50, 0.00],
        [0.00, 0.50, -0.25, 0.00],
        [0.00, 0.00, 0.00, 0.25],
    ]
).reshape(2, 2, 2, 2)  # (p0_out, p1_out, p0_in, p1_in)
H = ct.tensor(
    np.transpose(H_mat, (0, 1, 3, 2)),
    codomain=[p, p],
    domain=[p, p],
    labels=['p0', 'p1', 'p1*', 'p0*'],
)

# eigh acts on the map p⊗p → p⊗p; no explicit reshape to a matrix is required.
W, _V = ct.eigh(H, new_labels=['e'], new_leg_dual=False)
evals = np.sort(np.real(W.diagonal_as_numpy()))
print(evals)
# [-0.75  0.25  0.25  0.25]
np.testing.assert_allclose(evals, [-0.75, 0.25, 0.25, 0.25], atol=1e-12)

# The zz piece can still be built as an outer product of two maps:
Hz = ct.outer(Sz, Sz, relabel1={'p': 'p0', 'p*': 'p0*'}, relabel2={'p': 'p1', 'p*': 'p1*'})
print('Hz labels:', Hz.labels)
