#pragma once

#include <cyten/cyten.h>
#include <map>
#include <optional>
#include <string>
#include <utility>
#include <vector>

namespace cyten {

class NotImplemented : public std::logic_error
{
  public:
    NotImplemented(std::string name);
};

/// Format elements of an iterable as if it were a plain list.
std::string format_like_list(py::iterable it);

/// If the given object is iterable.
bool is_iterable(py::object a);

/// If `a` is not iterable or a string, return [a], else return a.
py::object to_iterable(py::object a);

/// Convert to a valid index into the given length, with python convention of negative indices from
/// back
int64 to_valid_idx(int64 idx, int64 length);

// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py
// gen_cpp_declaration --py-name BigOMonomial --header-file include/cyten/tools.h

/// A symbolic representation of an algorithmic cost as a monomial.
class BigOMonomial
{
  public:
  public:
    BigOMonomial(dict_str_int_ factors);
    virtual ~BigOMonomial() = default;
    /// Initialize from a string representation like ``'x^2 y^3'``.
    TYPEOF_return from_str(std::string mono);
    TYPEOF_return __add__(TYPEOF_other other);
    int __hash__();
    TYPEOF_return __mul__(TYPEOF_other other);
    str __repr__();
    str __str__();
    bool __eq__(TYPEOF_other other);
    /// If the given monomial is negligible compared to `others`, s.t. ``O(self + x) = O(x)``.
    TYPEOF_return is_negligible(TYPEOF_relations relations = py::none());
};
// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py
// gen_cpp_declaration --py-name BigOPolynomial --header-file include/cyten/tools.h

/// A symbolic representation of an algorithmic cost as a monomial.
class BigOPolynomial
{
  public:
    static TYPEOF___radd__ __radd__;
    static TYPEOF___rmul__ __rmul__;

  public:
    BigOPolynomial(list_BigOMonomial_ terms = py::none());
    virtual ~BigOPolynomial() = default;
    /// Simplify a list of terms by dropping negligible terms.
    TYPEOF_return simplify_terms(list_BigOMonomial_ terms,
                                  list_tuple_BigOMonomial_BigOMonomial__ relations = py::none());
    /// Initialize from a string representation like ``'x^2 y^3 + x^4'``.
    TYPEOF_return from_str(std::string poly);
    str __repr__();
    str __str__();
    TYPEOF_return __add__(TYPEOF_other other);
    bool __eq__(TYPEOF_other other);
    int __hash__();
    TYPEOF_return __mul__(TYPEOF_other other);
    /// Product of multiply symmetries
    TYPEOF_return prod();
};

} // namespace cyten
