
#include <cyten/backends/abelian.h>

namespace cyten {

// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_definition --py-name AbelianBackendData --header-file include/cyten/backends/abelian.h --src-file src/backends/abelian.cpp

AbelianBackendData::AbelianBackendData(
    Dtype dtype,
    std::string device,
    std::vector<BlockBackend::BlockPtr> blocks,
    py::array_t<int64> block_inds,
    bool is_sorted
) {
    /* CHECKME: converted from following python code:
     *         if not is_sorted:
     *             perm = np.lexsort(block_inds.T)
     *             block_inds = block_inds[perm, :]
     *             blocks = [blocks[n] for n in perm]
     * self.dtype = dtype
     * self.device = device
     * self.blocks = blocks
     * self.block_inds = block_inds
     */
    if (!is_sorted) {
        auto /* CHECKME: type? */ perm = np.lexsort(block_inds.T);
        block_inds = /* Multidimensional slice using std::gslice
 * NOTE: Requires block_inds_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   block_inds_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
block_inds[std::gslice(perm * block_inds_strides[0], std::valarray<std::size_t>{1, block_inds.shape(1)}, std::valarray<std::size_t>{block_inds_strides[0], block_inds_strides[1]})];
        blocks = /* FIXME: ListComp: [blocks[n] for n in perm] */;
    }
    dtype = dtype;
    device = device;
    blocks = blocks;
    block_inds = block_inds;
}

/// Return the index ``n`` of the block which matches the block_inds.
std::optional<int64> AbelianBackendData::get_block_num(py::array_t<int64> block_inds) {
    /* CHECKME: converted from following python code:
     * # OPTIMIZE use sorted for lookup?
     * match = np.argwhere(np.all(self.block_inds == block_inds, axis=1))[:, 0]
     *         if len(match) == 0:
     *             return None
     * return match[0]
     */
    // OPTIMIZE use sorted for lookup?
    auto /* CHECKME: type? */ match = /* Multidimensional slice using std::gslice
 * NOTE: Requires np.argwhere(np.all(block_inds == block_inds, py::arg({keyword.key}) = val) /* CHECKME: keywords ['axis'] */)_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   np.argwhere(np.all(block_inds == block_inds, py::arg({keyword.key}) = val) /* CHECKME: keywords ['axis'] */)_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
np.argwhere(np.all(block_inds == block_inds, py::arg({keyword.key}) = val) /* CHECKME: keywords ['axis'] */)[std::gslice(0, std::valarray<std::size_t>{np.argwhere(np.all(block_inds == block_inds, py::arg({keyword.key}) = val) /* CHECKME: keywords ['axis'] */).shape(0), 1}, std::valarray<std::size_t>{np.argwhere(np.all(block_inds == block_inds, py::arg({keyword.key}) = val) /* CHECKME: keywords ['axis'] */)_strides[0], np.argwhere(np.all(block_inds == block_inds, py::arg({keyword.key}) = val) /* CHECKME: keywords ['axis'] */)_strides[1]})];
    if (len(match) == 0) {
        return py::none();
    }
    return match[0];
}

/// Get the block at given block indices.
BlockBackend::BlockPtr AbelianBackendData::get_block(py::array_t<int64> block_inds) {
    /* CHECKME: converted from following python code:
     * block_num = self.get_block_num(block_inds)
     * return None if block_num is None else self.blocks[block_num]
     */
    auto /* CHECKME: type? */ block_num = get_block_num(block_inds);
    return block_num == py::none() ? py::none() : blocks[block_num];
}

void AbelianBackendData::save_hdf5(py::object hdf5_saver, py::object h5gr, const std::string & subpath) {
    /* CHECKME: converted from following python code:
     * hdf5_saver.save(self.block_inds, subpath + 'block_inds')
     * hdf5_saver.save(self.blocks, subpath + 'blocks')
     * hdf5_saver.save(self.dtype.to_numpy_dtype(), subpath + 'dtype')
     * hdf5_saver.save(self.device, subpath + 'device')
     */
    hdf5_saver.save(block_inds, subpath + "block_inds");
    hdf5_saver.save(blocks, subpath + "blocks");
    hdf5_saver.save(dtype.to_numpy_dtype(), subpath + "dtype");
    hdf5_saver.save(device, subpath + "device");
}

Ptr AbelianBackendData::from_hdf5(py::object hdf5_loader, py::object h5gr, const std::string & subpath) {
    /* CHECKME: converted from following python code:
     * obj = cls.__new__(cls)
     * hdf5_loader.memorize_load(h5gr, obj)
     * obj.block_inds = hdf5_loader.load(subpath + 'block_inds')
     * obj.blocks = hdf5_loader.load(subpath + 'blocks')
     * obj.device = hdf5_loader.load(subpath + 'device')
     * dt = hdf5_loader.load(subpath + 'dtype')
     * obj.dtype = Dtype.from_numpy_dtype(dt)
     * return obj
     */
    auto /* CHECKME: type? */ obj = cls.__new__(cls);
    hdf5_loader.memorize_load(h5gr, obj);
    obj.block_inds = hdf5_loader.load(subpath + "block_inds");
    obj.blocks = hdf5_loader.load(subpath + "blocks");
    obj.device = hdf5_loader.load(subpath + "device");
    auto /* CHECKME: type? */ dt = hdf5_loader.load(subpath + "dtype");
    obj.dtype = Dtype.from_numpy_dtype(dt);
    return obj;
}

} // namespace cyten
