#include <cyten/backends/fusion_tree_backend.h>

namespace cyten {

// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_definition --py-name FusionTreeData --header-file include/cyten/backends/fusion_tree_backend.h --src-file src/backends/fusion_tree_backend.cpp

FusionTreeData::FusionTreeData(
    py::array block_inds,
    std::vector<BlockBackend::BlockPtr> blocks,
    Dtype dtype,
    std::string device,
    bool is_sorted
) {
    /* CHECKME: converted from following python code:
     *         if not is_sorted:
     *             perm = np.lexsort(block_inds.T)
     *             block_inds = block_inds[perm, :]
     *             blocks = [blocks[n] for n in perm]
     * self.block_inds = block_inds
     * self.blocks = blocks
     * self.dtype = dtype
     * self.device = device
     */
    if (!is_sorted) {
        auto /* CHECKME: type? */ perm = np.lexsort(block_inds.T);
        block_inds = /* Multidimensional slice using std::gslice
 * NOTE: Requires block_inds_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   block_inds_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
block_inds[std::gslice(perm * block_inds_strides[0], std::valarray<std::size_t>{1, block_inds.shape(1)}, std::valarray<std::size_t>{block_inds_strides[0], block_inds_strides[1]})];
        blocks = /* FIXME: ListComp: [blocks[n] for n in perm] */;
    }
    block_inds = block_inds;
    blocks = blocks;
    dtype = dtype;
    device = device;
}

/// Return `ind` such that ``blocks[ind]`` is associated with the `coupled` sector.
std::optional<int64> FusionTreeData::block_ind_from_coupled(Sector coupled, TensorProduct::Ptr domain) {
    /* CHECKME: converted from following python code:
     * domain_sector_ind = domain.sector_decomposition_where(coupled)
     *         if domain_sector_ind is None:
     *             return None
     * return self.block_ind_from_domain_sector_ind(domain_sector_ind)
     */
    auto /* CHECKME: type? */ domain_sector_ind = domain.sector_decomposition_where(coupled);
    if (domain_sector_ind == py::none()) {
        return py::none();
    }
    return block_ind_from_domain_sector_ind(domain_sector_ind);
}

/// Return `ind` such that ``block_inds[ind, 1] == domain_sector_ind``
std::optional<int64> FusionTreeData::block_ind_from_domain_sector_ind(int64 domain_sector_ind) {
    /* CHECKME: converted from following python code:
     * ind = np.searchsorted(self.block_inds[:, 1], domain_sector_ind)
     *         if ind >= len(self.block_inds) or self.block_inds[ind, 1] != domain_sector_ind:
     *             return None
     *         if ind + 1 < self.block_inds.shape[0] and self.block_inds[ind + 1, 1] == domain_sector_ind:
     *             raise RuntimeError
     * return ind
     */
    auto /* CHECKME: type? */ ind = np.searchsorted(/* Multidimensional slice using std::gslice
 * NOTE: Requires block_inds_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   block_inds_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
block_inds[std::gslice(1 * block_inds_strides[1], std::valarray<std::size_t>{block_inds.shape(0), 1}, std::valarray<std::size_t>{block_inds_strides[0], block_inds_strides[1]})], domain_sector_ind);
    if (ind >= len(block_inds) || /* Multidimensional slice using std::gslice
 * NOTE: Requires block_inds_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   block_inds_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
block_inds[std::gslice(ind * block_inds_strides[0] + 1 * block_inds_strides[1], std::valarray<std::size_t>{1, 1}, std::valarray<std::size_t>{block_inds_strides[0], block_inds_strides[1]})] != domain_sector_ind) {
        return py::none();
    }
    if (ind + 1 < block_inds.shape[0] && /* Multidimensional slice using std::gslice
 * NOTE: Requires block_inds_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   block_inds_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
block_inds[std::gslice(ind + 1 * block_inds_strides[0] + 1 * block_inds_strides[1], std::valarray<std::size_t>{1, 1}, std::valarray<std::size_t>{block_inds_strides[0], block_inds_strides[1]})] == domain_sector_ind) {
        throw std::runtime_error("");
    }
    return ind;
}

/// Discard blocks whose norm is below the threshold `eps`
void FusionTreeData::discard_zero_blocks(std::shared_ptr<BlockBackend> backend, float64 eps) {
    /* CHECKME: converted from following python code:
     * keep = []
     *         for i, block in enumerate(self.blocks):
     *             if backend.norm(block) >= eps:
     *                 keep.append(i)
     * self.blocks = [self.blocks[i] for i in keep]
     * self.block_inds = self.block_inds[keep]
     */
    auto /* CHECKME: type? */ keep = {} /* FIXME: empty list */;
    for (auto [i, block] : std::views::enumerate(blocks)) {
        if (backend.norm(block) >= eps) {
            keep.append(i);
        }
    }
    blocks = /* FIXME: ListComp: [self.blocks[i] for i in keep] */;
    block_inds = block_inds[keep];
}

void FusionTreeData::save_hdf5(py::object hdf5_saver, py::object h5gr, std::string subpath) {
    /* CHECKME: converted from following python code:
     * hdf5_saver.save(self.block_inds, subpath + 'block_inds')
     * hdf5_saver.save(self.blocks, subpath + 'blocks')
     * hdf5_saver.save(self.dtype, subpath + 'dtype')
     * hdf5_saver.save(self.device, subpath + 'device')
     */
    hdf5_saver.save(block_inds, subpath + "block_inds");
    hdf5_saver.save(blocks, subpath + "blocks");
    hdf5_saver.save(dtype, subpath + "dtype");
    hdf5_saver.save(device, subpath + "device");
}

Ptr FusionTreeData::from_hdf5(py::object hdf5_loader, py::object h5gr, std::string subpath) {
    /* CHECKME: converted from following python code:
     * obj = cls.__new__(cls)
     * hdf5_loader.memorize_load(h5gr, obj)
     * obj.block_inds = hdf5_loader.load(subpath + 'block_inds')
     * obj.blocks = hdf5_loader.load(subpath + 'blocks')
     * obj.device = hdf5_loader.load(subpath + 'device')
     * obj.dtype = hdf5_loader.load(subpath + 'dtype')
     * return obj
     */
    auto /* CHECKME: type? */ obj = cls.__new__(cls);
    hdf5_loader.memorize_load(h5gr, obj);
    obj.block_inds = hdf5_loader.load(subpath + "block_inds");
    obj.blocks = hdf5_loader.load(subpath + "blocks");
    obj.device = hdf5_loader.load(subpath + "device");
    obj.dtype = hdf5_loader.load(subpath + "dtype");
    return obj;
}
