#include <cyten/backends/no_symmetry.h>

namespace cyten {

} // namespace cyten
// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_definition --py-name NoSymmetryBackend --header-file include/cyten/backends/no_symmetry.h --src-file src/backends/no_symmetry.cpp

NoSymmetryBackend::NoSymmetryBackend(std::shared_ptr<BlockBackend> block_backend) {
    /* CHECKME: converted from following python code:
     * super().__init__(block_backend=block_backend)
     * self.DataCls = block_backend.BlockCls
     */
    super().__init__(py::arg({keyword.key}) = val) /* CHECKME: keywords ['block_backend'] */;
    DataCls = block_backend.BlockCls;
}

void NoSymmetryBackend::test_tensor_sanity(py::object a, bool is_diagonal) {
    /* CHECKME: converted from following python code:
     * super().test_tensor_sanity(a, is_diagonal=is_diagonal)
     *         if is_diagonal:
     *             expect_shape = (a.legs[0].dim,)
     *         else:
     *             expect_shape = a.shape
     *         self.block_backend.test_block_sanity(
     *             a.data, expect_shape=expect_shape, expect_dtype=a.dtype, expect_device=a.device
     *         )
     */
    super().test_tensor_sanity(a, py::arg({keyword.key}) = val) /* CHECKME: keywords ['is_diagonal'] */;
    if (is_diagonal) {
        auto /* CHECKME: type? */ expect_shape = std::make_tuple(a.legs[0].dim);
    } else {
        expect_shape = a.shape;
    }
    block_backend.test_block_sanity(a.data, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['expect_shape', 'expect_dtype', 'expect_device'] */;
}

void NoSymmetryBackend::test_mask_sanity(py::object a) {
    /* CHECKME: converted from following python code:
     * super().test_mask_sanity(a)
     *         self.block_backend.test_block_sanity(
     *             a.data, expect_shape=(a.large_leg.dim,), expect_dtype=Dtype.bool, expect_device=a.device
     *         )
     * assert self.block_backend.sum_all(a.data).as_int64() == a.small_leg.dim
     */
    super().test_mask_sanity(a);
    block_backend.test_block_sanity(a.data, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['expect_shape', 'expect_dtype', 'expect_device'] */;
    /* FIXME: Assert: assert self.block_backend.sum_all(a.data).as_int64() == a.small_leg.dim */
}

DataPtr NoSymmetryBackend::act_block_diagonal_square_matrix(
    py::object a,
    py::function block_method,
    py::object dtype_map
) {
    /* CHECKME: converted from following python code:
     * return block_method(a.data)
     */
    return block_method(a.data);
}

DataPtr NoSymmetryBackend::add_trivial_leg(
    py::object a,
    int64 legs_pos,
    bool add_to_domain,
    int64 co_domain_pos,
    TensorProduct::Ptr new_codomain,
    TensorProduct::Ptr new_domain
) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.add_axis(a.data, legs_pos)
     */
    return block_backend.add_axis(a.data, legs_pos);
}

bool NoSymmetryBackend::almost_equal(py::object a, py::object b, float64 rtol, float64 atol) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.allclose(a.data, b.data, rtol=rtol, atol=atol)
     */
    return block_backend.allclose(a.data, b.data, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['rtol', 'atol'] */;
}

DataPtr NoSymmetryBackend::apply_mask_to_DiagonalTensor(py::object tensor, py::object mask) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.apply_mask(tensor.data, mask.data, ax=0)
     */
    return block_backend.apply_mask(tensor.data, mask.data, py::arg({keyword.key}) = val) /* CHECKME: keywords ['ax'] */;
}

DataPtr NoSymmetryBackend::combine_legs(
    py::object tensor,
    std::vector<std::vector<int64>> leg_idcs_combine,
    std::vector<LegPipe::Ptr> pipes,
    TensorProduct::Ptr new_codomain,
    TensorProduct::Ptr new_domain
) {
    /* CHECKME: converted from following python code:
     * in_domain = [group[0] >= tensor.num_codomain_legs for group in leg_idcs_combine]
     * cstyles = [pipe.combine_cstyle != in_dom for pipe, in_dom in zip(pipes, in_domain)]
     * return self.block_backend.combine_legs(tensor.data, leg_idcs_combine, cstyles)
     */
    auto /* CHECKME: type? */ in_domain = /* FIXME: ListComp: [group[0] >= tensor.num_codomain_legs for group in leg_idcs_combine] */;
    auto /* CHECKME: type? */ cstyles = /* FIXME: ListComp: [pipe.combine_cstyle != in_dom for pipe, in_dom in zip(pipes, in_domain)] */;
    return block_backend.combine_legs(tensor.data, leg_idcs_combine, cstyles);
}

DataPtr NoSymmetryBackend::compose(py::object a, py::object b) {
    /* CHECKME: converted from following python code:
     * a_domain = list(reversed(range(a.num_codomain_legs, a.num_legs)))
     * b_codomain = list(range(b.num_codomain_legs))
     * return self.block_backend.tdot(a.data, b.data, a_domain, b_codomain)
     */
    auto /* CHECKME: type? */ a_domain = list(reversed(range(a.num_codomain_legs, a.num_legs)));
    auto /* CHECKME: type? */ b_codomain = list(range(b.num_codomain_legs));
    return block_backend.tdot(a.data, b.data, a_domain, b_codomain);
}

DataPtr NoSymmetryBackend::copy_data(py::object a, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.copy_block(a.data, device=device)
     */
    return block_backend.copy_block(a.data, py::arg({keyword.key}) = val) /* CHECKME: keywords ['device'] */;
}

DataPtr NoSymmetryBackend::dagger(py::object a) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.dagger(a.data)
     */
    return block_backend.dagger(a.data);
}

BlockBackend::Scalar NoSymmetryBackend::data_item(DataPtr a) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.item(a)
     */
    return block_backend.item(a);
}

bool NoSymmetryBackend::diagonal_all(py::object a) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.all(a.data)
     */
    return block_backend.all(a.data);
}

bool NoSymmetryBackend::diagonal_any(py::object a) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.any(a.data)
     */
    return block_backend.any(a.data);
}

DataPtr NoSymmetryBackend::diagonal_elementwise_binary(
    py::object a,
    py::object b,
    py::function func,
    py::dict func_kwargs,
    bool partial_zero_is_zero
) {
    /* CHECKME: converted from following python code:
     * return func(a.data, b.data, **func_kwargs)
     */
    return func(a.data, b.data, py::arg({keyword.key}) = val) /* CHECKME: keywords [None] */;
}

DataPtr NoSymmetryBackend::diagonal_elementwise_unary(
    py::object a,
    py::function func,
    py::dict func_kwargs,
    bool maps_zero_to_zero
) {
    /* CHECKME: converted from following python code:
     * return func(a.data, **func_kwargs)
     */
    return func(a.data, py::arg({keyword.key}) = val) /* CHECKME: keywords [None] */;
}

DataPtr NoSymmetryBackend::diagonal_from_block(BlockBackend::BlockPtr a, TensorProduct::Ptr co_domain, float64 tol) {
    /* CHECKME: converted from following python code:
     * return a
     */
    return a;
}

DataPtr NoSymmetryBackend::diagonal_from_sector_block_func(py::function func, TensorProduct::Ptr co_domain) {
    /* CHECKME: converted from following python code:
     * coupled = co_domain.symmetry.trivial_sector
     * shape = (co_domain.dim,)
     * return func(shape, coupled)
     */
    auto /* CHECKME: type? */ coupled = co_domain.symmetry.trivial_sector;
    auto /* CHECKME: type? */ shape = std::make_tuple(co_domain.dim);
    return func(shape, coupled);
}

DataPtr NoSymmetryBackend::diagonal_tensor_from_full_tensor(py::object a, std::optional<float64> tol) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.get_diagonal(a.data, tol=tol)
     */
    return block_backend.get_diagonal(a.data, py::arg({keyword.key}) = val) /* CHECKME: keywords ['tol'] */;
}

BlockBackend::Scalar NoSymmetryBackend::diagonal_tensor_trace_full(py::object a) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.sum_all(a.data)
     */
    return block_backend.sum_all(a.data);
}

BlockBackend::BlockPtr NoSymmetryBackend::diagonal_tensor_to_block(py::object a) {
    /* CHECKME: converted from following python code:
     * return a.data
     */
    return a.data;
}

std::tuple<DataPtr, ElementarySpace::Ptr> NoSymmetryBackend::diagonal_to_mask(py::object tens) {
    /* CHECKME: converted from following python code:
     * large_leg = tens.leg
     * basis_perm = large_leg._basis_perm
     * data = tens.data
     *         if basis_perm is not None:
     *             basis_perm = rank_data(basis_perm[self.block_backend.to_numpy(data)])
     *         small_leg = ElementarySpace.from_trivial_sector(
     *             dim=self.block_backend.sum_all(data).as_int64(),
     *             symmetry=large_leg.symmetry,
     *             is_dual=large_leg.is_dual,
     *             basis_perm=basis_perm,
     *         )
     * return data, small_leg
     */
    auto /* CHECKME: type? */ large_leg = tens.leg;
    auto /* CHECKME: type? */ basis_perm = large_leg._basis_perm;
    auto /* CHECKME: type? */ data = tens.data;
    if (basis_perm != py::none()) {
        basis_perm = rank_data(basis_perm[block_backend.to_numpy(data)]);
    }
    auto /* CHECKME: type? */ small_leg = ElementarySpace.from_trivial_sector(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dim', 'symmetry', 'is_dual', 'basis_perm'] */;
    return std::make_tuple(data, small_leg);
}

std::tuple<Space::Ptr, DataPtr> NoSymmetryBackend::diagonal_transpose(py::object tens) {
    /* CHECKME: converted from following python code:
     * return tens.leg.dual, tens.data
     */
    return std::make_tuple(tens.leg.dual, tens.data);
}

std::tuple<DataPtr, DataPtr, ElementarySpace::Ptr> NoSymmetryBackend::eigh(
    py::object a,
    bool new_leg_dual,
    std::optional<std::string> sort
) {
    /* CHECKME: converted from following python code:
     * new_leg = a.domain.as_ElementarySpace(is_dual=new_leg_dual)
     * J = a.num_codomain_legs
     * N = 2 * J
     * mat = self.block_backend.permute_axes(a.data, [*range(J), *reversed(range(J, N))])
     * k = a.domain.dim
     * mat = self.block_backend.reshape(mat, (k,) * 2)
     * w, v = self.block_backend.eigh(mat, sort=sort)
     * v = self.block_backend.reshape(v, a.shape[:J] + (k,))
     * return w, v, new_leg
     */
    auto /* CHECKME: type? */ new_leg = a.domain.as_ElementarySpace(py::arg({keyword.key}) = val) /* CHECKME: keywords ['is_dual'] */;
    auto /* CHECKME: type? */ J = a.num_codomain_legs;
    auto /* CHECKME: type? */ N = 2 * J;
    auto /* CHECKME: type? */ mat = block_backend.permute_axes(a.data, {/* FIXME: Starred: *range(J) */, /* FIXME: Starred: *reversed(range(J, N)) */});
    auto /* CHECKME: type? */ k = a.domain.dim;
    mat = block_backend.reshape(mat, std::make_tuple(k) * 2);
    std::make_tuple(w, v) = block_backend.eigh(mat, py::arg({keyword.key}) = val) /* CHECKME: keywords ['sort'] */;
    auto /* CHECKME: type? */ v = block_backend.reshape(v, a.shape[std::slice(0, J, 1)] + std::make_tuple(k));
    return std::make_tuple(w, v, new_leg);
}

DataPtr NoSymmetryBackend::eye_data(TensorProduct::Ptr co_domain, Dtype dtype, std::string device) {
    /* CHECKME: converted from following python code:
     * # Note: the identity has the same matrix elements in all ONB, so ne need to consider
     * #       the basis perms.
     * return self.block_backend.eye_block(legs=[l.dim for l in co_domain.factors], dtype=dtype, device=device)
     */
    // Note: the identity has the same matrix elements in all ONB, so ne need to consider
    //       the basis perms.
    return block_backend.eye_block(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['legs', 'dtype', 'device'] */;
}

DataPtr NoSymmetryBackend::from_dense_block(
    BlockBackend::BlockPtr a,
    TensorProduct::Ptr codomain,
    TensorProduct::Ptr domain,
    float64 tol
) {
    /* CHECKME: converted from following python code:
     * return a
     */
    return a;
}

DataPtr NoSymmetryBackend::from_dense_block_trivial_sector(BlockBackend::BlockPtr block, Space::Ptr leg) {
    /* CHECKME: converted from following python code:
     * # there are no other sectors, so this is just the unmodified block.
     * assert self.block_backend.get_shape(block) == (leg.dim,)
     */
    // there are no other sectors, so this is just the unmodified block.
    /* FIXME: Assert: assert self.block_backend.get_shape(block) == (leg.dim,) */
}

DataPtr NoSymmetryBackend::from_grid(
    std::vector<std::vector<py::object>> grid,
    TensorProduct::Ptr new_codomain,
    TensorProduct::Ptr new_domain,
    std::vector<std::vector<int64>> left_mult_slices,
    std::vector<std::vector<int64>> right_mult_slices,
    Dtype dtype,
    std::string device
) {
    /* CHECKME: converted from following python code:
     * heights = left_mult_slices[0]
     * widths = right_mult_slices[0]
     * data = self.zero_data(codomain=new_codomain, domain=new_domain, dtype=dtype, device=device)
     * codom_slcs = [slice(None)] * (len(new_codomain) - 1)
     * dom_slcs = [slice(None)] * (len(new_domain) - 1)
     *         for i, row in enumerate(grid):
     *             for j, op in enumerate(row):
     *                 if op is None:
     *                     continue
     *                 row_slc = slice(widths[j], widths[j + 1])
     *                 col_slc = slice(heights[i], heights[i + 1])
     *                 slcs = (col_slc, *codom_slcs, row_slc, *dom_slcs)
     *                 data[slcs] += op.data
     * return data
     */
    auto /* CHECKME: type? */ heights = left_mult_slices[0];
    auto /* CHECKME: type? */ widths = right_mult_slices[0];
    auto /* CHECKME: type? */ data = zero_data(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['codomain', 'domain', 'dtype', 'device'] */;
    auto /* CHECKME: type? */ codom_slcs = {slice(py::none())} * len(new_codomain) - 1;
    auto /* CHECKME: type? */ dom_slcs = {slice(py::none())} * len(new_domain) - 1;
    for (auto [i, row] : std::views::enumerate(grid)) {
        for (auto [j, op] : std::views::enumerate(row)) {
            if (op == py::none()) {
                continue;
            }
            auto /* CHECKME: type? */ row_slc = slice(widths[j], widths[j + 1]);
            auto /* CHECKME: type? */ col_slc = slice(heights[i], heights[i + 1]);
            auto /* CHECKME: type? */ slcs = std::make_tuple(col_slc, /* FIXME: Starred: *codom_slcs */, row_slc, /* FIXME: Starred: *dom_slcs */);
            data[slcs] += op.data;
        }
    }
    return data;
}

DataPtr NoSymmetryBackend::from_random_normal(
    TensorProduct::Ptr codomain,
    TensorProduct::Ptr domain,
    float64 sigma,
    Dtype dtype,
    std::string device
) {
    /* CHECKME: converted from following python code:
     * shape = [leg.dim for leg in conventional_leg_order(codomain, domain)]
     * return self.block_backend.random_normal(shape, dtype=dtype, sigma=sigma, device=device)
     */
    auto /* CHECKME: type? */ shape = /* FIXME: ListComp: [leg.dim for leg in conventional_leg_order(codomain, domain)] */;
    return block_backend.random_normal(shape, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype', 'sigma', 'device'] */;
}

/// Generate tensor data from a function ``func(shape: tuple[int], coupled: Sector) -> Block``.
DataPtr NoSymmetryBackend::from_sector_block_func(
    py::function func,
    TensorProduct::Ptr codomain,
    TensorProduct::Ptr domain
) {
    /* CHECKME: converted from following python code:
     * coupled = codomain.symmetry.trivial_sector
     * shape = tuple(l.dim for l in conventional_leg_order(codomain, domain))
     * return func(shape, coupled)
     */
    auto /* CHECKME: type? */ coupled = codomain.symmetry.trivial_sector;
    auto /* CHECKME: type? */ shape = tuple(/* FIXME: GeneratorExp: (l.dim for l in conventional_leg_order(codomain, domain)) */);
    return func(shape, coupled);
}

DataPtr NoSymmetryBackend::from_tree_pairs(
    std::map<std::pair<FusionTree, FusionTree>, BlockBackend::BlockPtr> trees,
    TensorProduct::Ptr codomain,
    TensorProduct::Ptr domain,
    Dtype dtype,
    std::string device
) {
    /* CHECKME: converted from following python code:
     * assert len(trees) == 1
     * (block,) = trees.values()
     * expect_shape = tuple(l.dim for l in conventional_leg_order(codomain, domain))
     * assert self.block_backend.get_shape(block) == expect_shape
     * return block
     */
    /* FIXME: Assert: assert len(trees) == 1 */
    std::make_tuple(block) = trees.values();
    auto /* CHECKME: type? */ expect_shape = tuple(/* FIXME: GeneratorExp: (l.dim for l in conventional_leg_order(codomain, domain)) */);
    /* FIXME: Assert: assert self.block_backend.get_shape(block) == expect_shape */
    return block;
}

DataPtr NoSymmetryBackend::full_data_from_diagonal_tensor(py::object a) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.block_from_diagonal(a.data)
     */
    return block_backend.block_from_diagonal(a.data);
}

DataPtr NoSymmetryBackend::full_data_from_mask(py::object a, Dtype dtype) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.block_from_mask(a.data, dtype=dtype)
     */
    return block_backend.block_from_mask(a.data, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */;
}

std::string NoSymmetryBackend::get_device_from_data(DataPtr a) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.get_device(a)
     */
    return block_backend.get_device(a);
}

Dtype NoSymmetryBackend::get_dtype_from_data(DataPtr a) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.get_dtype(a)
     */
    return block_backend.get_dtype(a);
}

BlockBackend::Scalar NoSymmetryBackend::get_element(py::object a, std::vector<int64> idcs) {
    /* CHECKME: converted from following python code:
     *         idcs = [
     *             l.apply_basis_perm(idx, inverse=True, pre_compose=True) for l, idx in zip(conventional_leg_order(a), idcs)
     *         ]
     * return self.block_backend.get_block_element(a.data, idcs)
     */
    idcs = /* FIXME: ListComp:                [
            l.apply_basis_perm(idx, inverse=True, pre_compose=True) for l, idx in zip(conventional_leg_order(a), idcs)
        ] */;
    return block_backend.get_block_element(a.data, idcs);
}

BlockBackend::Scalar NoSymmetryBackend::get_element_diagonal(py::object a, int64 idx) {
    /* CHECKME: converted from following python code:
     * # a.data is a single 1D block
     * _, idx = a.leg.parse_index(idx)
     * return self.block_backend.get_block_element(a.data, [idx])
     */
    // a.data is a single 1D block
    std::make_tuple(_, idx) = a.leg.parse_index(idx);
    return block_backend.get_block_element(a.data, {idx});
}

BlockBackend::Scalar NoSymmetryBackend::get_element_mask(py::object a, std::vector<int64> idcs) {
    /* CHECKME: converted from following python code:
     * idcs = [l.parse_index(idx)[1] for l, idx in zip(conventional_leg_order(a), idcs)]
     *         if a.is_projection:
     *             small, large = idcs
     *         else:
     *             large, small = idcs
     * return self.block_backend.get_block_mask_element(a.data, large, small)
     */
    idcs = /* FIXME: ListComp: [l.parse_index(idx)[1] for l, idx in zip(conventional_leg_order(a), idcs)] */;
    if (a.is_projection) {
        std::make_tuple(small, large) = idcs;
    } else {
        std::make_tuple(large, small) = idcs;
    }
    return block_backend.get_block_mask_element(a.data, large, small);
}

BlockBackend::Scalar NoSymmetryBackend::inner(py::object a, py::object b, bool do_dagger) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.inner(a.data, b.data, do_dagger=do_dagger)
     */
    return block_backend.inner(a.data, b.data, py::arg({keyword.key}) = val) /* CHECKME: keywords ['do_dagger'] */;
}

DataPtr NoSymmetryBackend::inv_part_from_dense_block_single_sector(
    BlockBackend::BlockPtr vector,
    Space::Ptr space,
    ElementarySpace::Ptr charge_leg
) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.add_axis(vector, pos=1)
     */
    return block_backend.add_axis(vector, py::arg({keyword.key}) = val) /* CHECKME: keywords ['pos'] */;
}

BlockBackend::BlockPtr NoSymmetryBackend::inv_part_to_dense_block_single_sector(py::object tensor) {
    /* CHECKME: converted from following python code:
     * return tensor.data[:, 0]
     */
    return /* Multidimensional slice using std::gslice
 * NOTE: Requires tensor.data_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   tensor.data_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
tensor.data[std::gslice(0, std::valarray<std::size_t>{tensor.data.shape(0), 1}, std::valarray<std::size_t>{tensor.data_strides[0], tensor.data_strides[1]})];
}

DataPtr NoSymmetryBackend::linear_combination(
    BlockBackend::Scalar a,
    py::object v,
    BlockBackend::Scalar b,
    py::object w
) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.linear_combination(a, v.data, b, w.data)
     */
    return block_backend.linear_combination(a, v.data, b, w.data);
}

std::tuple<DataPtr, DataPtr> NoSymmetryBackend::lq(py::object tensor, TensorProduct::Ptr new_co_domain) {
    /* CHECKME: converted from following python code:
     * l_dims = tensor.shape[: tensor.num_codomain_legs]
     * q_dims = tensor.shape[tensor.num_codomain_legs :]
     * mat = self.block_backend.reshape(tensor.data, (prod(l_dims), prod(q_dims)))
     * l, q = self.block_backend.matrix_lq(mat, full=False)
     * k = self.block_backend.get_shape(q)[0]
     * l = self.block_backend.reshape(l, l_dims + (k,))
     * q = self.block_backend.reshape(q, (k,) + q_dims)
     * return l, q
     */
    auto /* CHECKME: type? */ l_dims = tensor.shape[std::slice(0, tensor.num_codomain_legs, 1)];
    auto /* CHECKME: type? */ q_dims = tensor.shape[std::slice(tensor.num_codomain_legs, (tensor.shape.size() - tensor.num_codomain_legs), 1)];
    auto /* CHECKME: type? */ mat = block_backend.reshape(tensor.data, std::make_tuple(prod(l_dims), prod(q_dims)));
    std::make_tuple(l, q) = block_backend.matrix_lq(mat, py::arg({keyword.key}) = val) /* CHECKME: keywords ['full'] */;
    auto /* CHECKME: type? */ k = block_backend.get_shape(q)[0];
    auto /* CHECKME: type? */ l = block_backend.reshape(l, l_dims + std::make_tuple(k));
    auto /* CHECKME: type? */ q = block_backend.reshape(q, std::make_tuple(k) + q_dims);
    return std::make_tuple(l, q);
}

std::tuple<DataPtr, ElementarySpace::Ptr> NoSymmetryBackend::mask_binary_operand(
    py::object mask1,
    py::object mask2,
    py::function func
) {
    /* CHECKME: converted from following python code:
     * large_leg = mask1.large_leg
     * basis_perm = large_leg._basis_perm
     * data = func(mask1.data, mask2.data)
     *         if basis_perm is not None:
     *             basis_perm = rank_data(basis_perm[data.to_numpy()])
     *         small_leg = ElementarySpace.from_trivial_sector(
     *             dim=self.block_backend.sum_all(data).as_int64(),
     *             symmetry=large_leg.symmetry,
     *             is_dual=large_leg.is_dual,
     *             basis_perm=basis_perm,
     *         )
     * return data, small_leg
     */
    auto /* CHECKME: type? */ large_leg = mask1.large_leg;
    auto /* CHECKME: type? */ basis_perm = large_leg._basis_perm;
    auto /* CHECKME: type? */ data = func(mask1.data, mask2.data);
    if (basis_perm != py::none()) {
        basis_perm = rank_data(basis_perm[data.to_numpy()]);
    }
    auto /* CHECKME: type? */ small_leg = ElementarySpace.from_trivial_sector(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dim', 'symmetry', 'is_dual', 'basis_perm'] */;
    return std::make_tuple(data, small_leg);
}

std::tuple<DataPtr, TensorProduct::Ptr, TensorProduct::Ptr> NoSymmetryBackend::mask_contract_large_leg(
    py::object tensor,
    py::object mask,
    int64 leg_idx
) {
    /* CHECKME: converted from following python code:
     * in_domain, co_domain_idx, leg_idx = tensor._parse_leg_idx(leg_idx)
     * data = self.block_backend.apply_mask(tensor.data, mask.data, leg_idx)
     *         if in_domain:
     *             codomain = tensor.codomain
     *             spaces = tensor.domain.factors[:]
     *             spaces[co_domain_idx] = mask.small_leg
     *             domain = TensorProduct(spaces, symmetry=tensor.symmetry)
     *         else:
     *             domain = tensor.domain
     *             spaces = tensor.codomain.factors[:]
     *             spaces[co_domain_idx] = mask.small_leg
     *             codomain = TensorProduct(spaces, symmetry=tensor.symmetry)
     * return data, codomain, domain
     */
    std::make_tuple(in_domain, co_domain_idx, leg_idx) = tensor._parse_leg_idx(leg_idx);
    auto /* CHECKME: type? */ data = block_backend.apply_mask(tensor.data, mask.data, leg_idx);
    if (in_domain) {
        auto /* CHECKME: type? */ codomain = tensor.codomain;
        auto /* CHECKME: type? */ spaces = tensor.domain.factors[std::slice(0, tensor.domain.factors.size(), 1)];
        spaces[co_domain_idx] = mask.small_leg;
        auto /* CHECKME: type? */ domain = TensorProduct(spaces, py::arg({keyword.key}) = val) /* CHECKME: keywords ['symmetry'] */;
    } else {
        domain = tensor.domain;
        spaces = tensor.codomain.factors[std::slice(0, tensor.codomain.factors.size(), 1)];
        spaces[co_domain_idx] = mask.small_leg;
        codomain = TensorProduct(spaces, py::arg({keyword.key}) = val) /* CHECKME: keywords ['symmetry'] */;
    }
    return std::make_tuple(data, codomain, domain);
}

std::tuple<DataPtr, TensorProduct::Ptr, TensorProduct::Ptr> NoSymmetryBackend::mask_contract_small_leg(
    py::object tensor,
    py::object mask,
    int64 leg_idx
) {
    /* CHECKME: converted from following python code:
     * in_domain, co_domain_idx, leg_idx = tensor._parse_leg_idx(leg_idx)
     * data = self.block_backend.enlarge_leg(tensor.data, mask.data, leg_idx)
     *         if in_domain:
     *             codomain = tensor.codomain
     *             spaces = tensor.domain.factors[:]
     *             spaces[co_domain_idx] = mask.large_leg
     *             domain = TensorProduct(spaces, symmetry=tensor.symmetry)
     *         else:
     *             domain = tensor.domain
     *             spaces = tensor.codomain.factors[:]
     *             spaces[co_domain_idx] = mask.large_leg
     *             codomain = TensorProduct(spaces, symmetry=tensor.symmetry)
     * return data, codomain, domain
     */
    std::make_tuple(in_domain, co_domain_idx, leg_idx) = tensor._parse_leg_idx(leg_idx);
    auto /* CHECKME: type? */ data = block_backend.enlarge_leg(tensor.data, mask.data, leg_idx);
    if (in_domain) {
        auto /* CHECKME: type? */ codomain = tensor.codomain;
        auto /* CHECKME: type? */ spaces = tensor.domain.factors[std::slice(0, tensor.domain.factors.size(), 1)];
        spaces[co_domain_idx] = mask.large_leg;
        auto /* CHECKME: type? */ domain = TensorProduct(spaces, py::arg({keyword.key}) = val) /* CHECKME: keywords ['symmetry'] */;
    } else {
        domain = tensor.domain;
        spaces = tensor.codomain.factors[std::slice(0, tensor.codomain.factors.size(), 1)];
        spaces[co_domain_idx] = mask.large_leg;
        codomain = TensorProduct(spaces, py::arg({keyword.key}) = val) /* CHECKME: keywords ['symmetry'] */;
    }
    return std::make_tuple(data, codomain, domain);
}

DataPtr NoSymmetryBackend::mask_dagger(py::object mask) {
    /* CHECKME: converted from following python code:
     * return mask.data
     */
    return mask.data;
}

std::tuple<DataPtr, ElementarySpace::Ptr> NoSymmetryBackend::mask_from_block(
    BlockBackend::BlockPtr a,
    Space::Ptr large_leg
) {
    /* CHECKME: converted from following python code:
     * basis_perm = large_leg._basis_perm
     *         if basis_perm is not None:
     *             basis_perm = rank_data(basis_perm[a.to_numpy()])
     *         small_leg = ElementarySpace.from_trivial_sector(
     *             dim=self.block_backend.sum_all(a).as_int64(),
     *             symmetry=large_leg.symmetry,
     *             is_dual=large_leg.is_dual,
     *             basis_perm=basis_perm,
     *         )
     * return a, small_leg
     */
    auto /* CHECKME: type? */ basis_perm = large_leg._basis_perm;
    if (basis_perm != py::none()) {
        basis_perm = rank_data(basis_perm[a.to_numpy()]);
    }
    auto /* CHECKME: type? */ small_leg = ElementarySpace.from_trivial_sector(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dim', 'symmetry', 'is_dual', 'basis_perm'] */;
    return std::make_tuple(a, small_leg);
}

BlockBackend::BlockPtr NoSymmetryBackend::mask_to_block(py::object a) {
    /* CHECKME: converted from following python code:
     * return a.data
     */
    return a.data;
}

DataPtr NoSymmetryBackend::mask_to_diagonal(py::object a, Dtype dtype) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.to_dtype(a.data, dtype)
     */
    return block_backend.to_dtype(a.data, dtype);
}

std::tuple<Space::Ptr, Space::Ptr, DataPtr> NoSymmetryBackend::mask_transpose(py::object tens) {
    /* CHECKME: converted from following python code:
     * space_in = tens.codomain[0].dual
     * space_out = tens.domain[0].dual
     * return space_in, space_out, tens.data
     */
    auto /* CHECKME: type? */ space_in = tens.codomain[0].dual;
    auto /* CHECKME: type? */ space_out = tens.domain[0].dual;
    return std::make_tuple(space_in, space_out, tens.data);
}

std::tuple<DataPtr, ElementarySpace::Ptr> NoSymmetryBackend::mask_unary_operand(py::object mask, py::function func) {
    /* CHECKME: converted from following python code:
     * large_leg = mask.large_leg
     * basis_perm = large_leg._basis_perm
     * data = func(mask.data)
     *         if basis_perm is not None:
     *             basis_perm = rank_data(basis_perm[data])
     *         small_leg = ElementarySpace.from_trivial_sector(
     *             dim=self.block_backend.sum_all(data).as_int64(),
     *             symmetry=large_leg.symmetry,
     *             is_dual=large_leg.is_dual,
     *             basis_perm=basis_perm,
     *         )
     * return data, small_leg
     */
    auto /* CHECKME: type? */ large_leg = mask.large_leg;
    auto /* CHECKME: type? */ basis_perm = large_leg._basis_perm;
    auto /* CHECKME: type? */ data = func(mask.data);
    if (basis_perm != py::none()) {
        basis_perm = rank_data(basis_perm[data]);
    }
    auto /* CHECKME: type? */ small_leg = ElementarySpace.from_trivial_sector(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dim', 'symmetry', 'is_dual', 'basis_perm'] */;
    return std::make_tuple(data, small_leg);
}

DataPtr NoSymmetryBackend::move_to_device(py::object a, std::string device) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.as_block(a.data, device=device)
     */
    return block_backend.as_block(a.data, py::arg({keyword.key}) = val) /* CHECKME: keywords ['device'] */;
}

DataPtr NoSymmetryBackend::mul(BlockBackend::Scalar a, py::object b) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.mul(a, b.data)
     */
    return block_backend.mul(a, b.data);
}

BlockBackend::Scalar NoSymmetryBackend::norm(py::object a) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.norm(a.data)
     */
    return block_backend.norm(a.data);
}

DataPtr NoSymmetryBackend::outer(py::object a, py::object b) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.tensor_outer(a.data, b.data, K=a.num_codomain_legs)
     */
    return block_backend.tensor_outer(a.data, b.data, py::arg({keyword.key}) = val) /* CHECKME: keywords ['K'] */;
}

DataPtr NoSymmetryBackend::partial_compose(
    py::object a,
    py::object b,
    int64 a_first_leg,
    TensorProduct::Ptr new_codomain,
    TensorProduct::Ptr new_domain
) {
    /* CHECKME: converted from following python code:
     *         if a_first_leg < a.num_codomain_legs:
     *             num_contr_legs = b.num_domain_legs
     *             num_add_legs = b.num_codomain_legs
     *             idcs_b = list(reversed(range(b.num_codomain_legs, b.num_legs)))
     *         else:
     *             num_contr_legs = b.num_codomain_legs
     *             num_add_legs = b.num_domain_legs
     *             idcs_b = list(reversed(range(b.num_codomain_legs)))
     * idcs_a = list(range(a_first_leg, a_first_leg + num_contr_legs))
     * res = self.block_backend.tdot(a.data, b.data, idcs_a, idcs_b)
     *         perm = (
     *             list(range(a_first_leg))
     *             + list(range(a.num_legs - num_contr_legs, a.num_legs - num_contr_legs + num_add_legs))
     *             + list(range(a_first_leg, a.num_legs - num_contr_legs))
     *         )
     * return self.block_backend.permute_axes(res, perm)
     */
    if (a_first_leg < a.num_codomain_legs) {
        auto /* CHECKME: type? */ num_contr_legs = b.num_domain_legs;
        auto /* CHECKME: type? */ num_add_legs = b.num_codomain_legs;
        auto /* CHECKME: type? */ idcs_b = list(reversed(range(b.num_codomain_legs, b.num_legs)));
    } else {
        num_contr_legs = b.num_codomain_legs;
        num_add_legs = b.num_domain_legs;
        idcs_b = list(reversed(range(b.num_codomain_legs)));
    }
    auto /* CHECKME: type? */ idcs_a = list(range(a_first_leg, a_first_leg + num_contr_legs));
    auto /* CHECKME: type? */ res = block_backend.tdot(a.data, b.data, idcs_a, idcs_b);
    auto /* CHECKME: type? */ perm = list(range(a_first_leg)) + list(range(a.num_legs - num_contr_legs, a.num_legs - num_contr_legs + num_add_legs)) + list(range(a_first_leg, a.num_legs - num_contr_legs));
    return block_backend.permute_axes(res, perm);
}

std::tuple<DataPtr, TensorProduct::Ptr, TensorProduct::Ptr> NoSymmetryBackend::partial_trace(
    py::object tensor,
    std::vector<std::pair<int64, int64>> pairs,
    std::optional<std::vector<int64>> levels
) {
    /* CHECKME: converted from following python code:
     * N = tensor.num_legs
     * idcs1 = []
     * idcs2 = []
     *         for i1, i2 in pairs:
     *             idcs1.append(i1)
     *             idcs2.append(i2)
     * remaining = [n for n in range(N) if n not in idcs1 and n not in idcs2]
     * data = self.block_backend.trace_partial(tensor.data, idcs1, idcs2, remaining)
     *         if len(remaining) == 0:
     *             return self.block_backend.item(data), None, None
     *         codomain = TensorProduct(
     *             [leg for n, leg in enumerate(tensor.codomain) if n in remaining], symmetry=tensor.symmetry
     *         )
     *         domain = TensorProduct(
     *             [leg for n, leg in enumerate(tensor.domain) if N - 1 - n in remaining], symmetry=tensor.symmetry
     *         )
     * return data, codomain, domain
     */
    auto /* CHECKME: type? */ N = tensor.num_legs;
    auto /* CHECKME: type? */ idcs1 = {} /* FIXME: empty list */;
    auto /* CHECKME: type? */ idcs2 = {} /* FIXME: empty list */;
    /* FIXME: for loop:         for i1, i2 in pairs:
            idcs1.append(i1)
            idcs2.append(i2) */
    auto /* CHECKME: type? */ remaining = /* FIXME: ListComp: [n for n in range(N) if n not in idcs1 and n not in idcs2] */;
    auto /* CHECKME: type? */ data = block_backend.trace_partial(tensor.data, idcs1, idcs2, remaining);
    if (len(remaining) == 0) {
        return std::make_tuple(block_backend.item(data), py::none(), py::none());
    }
    auto /* CHECKME: type? */ codomain = TensorProduct(/* FIXME: ListComp: [leg for n, leg in enumerate(tensor.codomain) if n in remaining] */, py::arg({keyword.key}) = val) /* CHECKME: keywords ['symmetry'] */;
    auto /* CHECKME: type? */ domain = TensorProduct(/* FIXME: ListComp: [leg for n, leg in enumerate(tensor.domain) if N - 1 - n in remaining] */, py::arg({keyword.key}) = val) /* CHECKME: keywords ['symmetry'] */;
    return std::make_tuple(data, codomain, domain);
}

DataPtr NoSymmetryBackend::permute_legs(
    py::object a,
    std::vector<int64> codomain_idcs,
    std::vector<int64> domain_idcs,
    TensorProduct::Ptr new_codomain,
    TensorProduct::Ptr new_domain,
    bool mixes_codomain_domain,
    std::vector<std::optional<int64>> levels,
    std::vector<std::optional<bool>> bend_right
) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.permute_axes(a.data, [*codomain_idcs, *reversed(domain_idcs)])
     */
    return block_backend.permute_axes(a.data, {/* FIXME: Starred: *codomain_idcs */, /* FIXME: Starred: *reversed(domain_idcs) */});
}

std::tuple<DataPtr, DataPtr> NoSymmetryBackend::qr(py::object a, TensorProduct::Ptr new_co_domain) {
    /* CHECKME: converted from following python code:
     * q_dims = a.shape[: a.num_codomain_legs]
     * r_dims = a.shape[a.num_codomain_legs :]
     * mat = self.block_backend.reshape(a.data, (prod(q_dims), prod(r_dims)))
     * q, r = self.block_backend.matrix_qr(mat, full=False)
     * k = self.block_backend.get_shape(r)[0]
     * q = self.block_backend.reshape(q, q_dims + (k,))
     * r = self.block_backend.reshape(r, (k,) + r_dims)
     * return q, r
     */
    auto /* CHECKME: type? */ q_dims = a.shape[std::slice(0, a.num_codomain_legs, 1)];
    auto /* CHECKME: type? */ r_dims = a.shape[std::slice(a.num_codomain_legs, (a.shape.size() - a.num_codomain_legs), 1)];
    auto /* CHECKME: type? */ mat = block_backend.reshape(a.data, std::make_tuple(prod(q_dims), prod(r_dims)));
    std::make_tuple(q, r) = block_backend.matrix_qr(mat, py::arg({keyword.key}) = val) /* CHECKME: keywords ['full'] */;
    auto /* CHECKME: type? */ k = block_backend.get_shape(r)[0];
    auto /* CHECKME: type? */ q = block_backend.reshape(q, q_dims + std::make_tuple(k));
    auto /* CHECKME: type? */ r = block_backend.reshape(r, std::make_tuple(k) + r_dims);
    return std::make_tuple(q, r);
}

BlockBackend::Scalar NoSymmetryBackend::reduce_DiagonalTensor(
    py::object tensor,
    py::function block_func,
    py::function func
) {
    /* CHECKME: converted from following python code:
     * return block_func(tensor.data)
     */
    return block_func(tensor.data);
}

DataPtr NoSymmetryBackend::scale_axis(py::object a, py::object b, int64 leg) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.scale_axis(a.data, b.data, leg)
     */
    return block_backend.scale_axis(a.data, b.data, leg);
}

DataPtr NoSymmetryBackend::split_legs(
    py::object a,
    std::vector<int64> leg_idcs,
    TensorProduct::Ptr new_codomain,
    TensorProduct::Ptr new_domain
) {
    /* CHECKME: converted from following python code:
     * dims = []
     * cstyles = []
     *         for n in leg_idcs:
     *             cstyles.append(a.legs[n].combine_cstyle)
     *             if cstyles[-1]:
     *                 dims.append([s.dim for s in a.legs[n].legs])
     *             else:
     *                 dims.append([s.dim for s in reversed(a.legs[n].legs)])
     * return self.block_backend.split_legs(a.data, leg_idcs, dims, cstyles)
     */
    auto /* CHECKME: type? */ dims = {} /* FIXME: empty list */;
    auto /* CHECKME: type? */ cstyles = {} /* FIXME: empty list */;
    /* FIXME: for loop:         for n in leg_idcs:
            cstyles.append(a.legs[n].combine_cstyle)
            if cstyles[-1]:
                dims.append([s.dim for s in a.legs[n].legs])
            else:
                dims.append([s.dim for s in reversed(a.legs[n].legs)]) */
    return block_backend.split_legs(a.data, leg_idcs, dims, cstyles);
}

DataPtr NoSymmetryBackend::squeeze_legs(py::object a, std::vector<int64> idcs) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.squeeze_axes(a.data, idcs)
     */
    return block_backend.squeeze_axes(a.data, idcs);
}

bool NoSymmetryBackend::supports_symmetry(Symmetry::Ptr symmetry) {
    /* CHECKME: converted from following python code:
     * return symmetry == no_symmetry
     */
    return symmetry == no_symmetry;
}

std::tuple<DataPtr, DataPtr, DataPtr> NoSymmetryBackend::svd(
    py::object a,
    TensorProduct::Ptr new_co_domain,
    std::optional<std::string> algorithm
) {
    /* CHECKME: converted from following python code:
     * u_dims = a.shape[: a.num_codomain_legs]
     * vh_dims = a.shape[a.num_codomain_legs :]
     * mat = self.block_backend.reshape(a.data, (prod(u_dims), prod(vh_dims)))
     * u, s, vh = self.block_backend.matrix_svd(mat, algorithm=algorithm)
     * k = self.block_backend.get_shape(s)[0]
     * u = self.block_backend.reshape(u, u_dims + (k,))
     * vh = self.block_backend.reshape(vh, (k,) + vh_dims)
     * return u, s, vh
     */
    auto /* CHECKME: type? */ u_dims = a.shape[std::slice(0, a.num_codomain_legs, 1)];
    auto /* CHECKME: type? */ vh_dims = a.shape[std::slice(a.num_codomain_legs, (a.shape.size() - a.num_codomain_legs), 1)];
    auto /* CHECKME: type? */ mat = block_backend.reshape(a.data, std::make_tuple(prod(u_dims), prod(vh_dims)));
    std::make_tuple(u, s, vh) = block_backend.matrix_svd(mat, py::arg({keyword.key}) = val) /* CHECKME: keywords ['algorithm'] */;
    auto /* CHECKME: type? */ k = block_backend.get_shape(s)[0];
    auto /* CHECKME: type? */ u = block_backend.reshape(u, u_dims + std::make_tuple(k));
    auto /* CHECKME: type? */ vh = block_backend.reshape(vh, std::make_tuple(k) + vh_dims);
    return std::make_tuple(u, s, vh);
}

py::object NoSymmetryBackend::state_tensor_product(
    BlockBackend::BlockPtr state1,
    BlockBackend::BlockPtr state2,
    LegPipe::Ptr pipe
) {
    /* CHECKME: converted from following python code:
     * # TODO clearly define what this should do in tensors.py first!
     * raise NotImplementedError('state_tensor_product not implemented')
     */
    // TODO clearly define what this should do in tensors.py first!
    throw std::logic_error("state_tensor_product not implemented");
}

DataPtr NoSymmetryBackend::to_block_backend(
    DataPtr data,
    std::shared_ptr<BlockBackend> block_backend,
    std::optional<Dtype> dtype,
    std::optional<std::string> device
) {
    /* CHECKME: converted from following python code:
     * return block_backend.as_block(data, dtype=dtype, device=device)
     */
    return block_backend.as_block(data, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype', 'device'] */;
}

BlockBackend::BlockPtr NoSymmetryBackend::to_dense_block(py::object a) {
    /* CHECKME: converted from following python code:
     * return a.data
     */
    return a.data;
}

BlockBackend::BlockPtr NoSymmetryBackend::to_dense_block_trivial_sector(py::object tensor) {
    /* CHECKME: converted from following python code:
     * # there are no other sectors, so this is essentially the same as to_dense_block.
     * return tensor.data
     */
    // there are no other sectors, so this is essentially the same as to_dense_block.
    return tensor.data;
}

DataPtr NoSymmetryBackend::to_dtype(py::object a, Dtype dtype) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.to_dtype(a.data, dtype)
     */
    return block_backend.to_dtype(a.data, dtype);
}

BlockBackend::Scalar NoSymmetryBackend::trace_full(py::object a, std::vector<int64> idcs1, std::vector<int64> idcs2) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.trace_full(a.data)
     */
    return block_backend.trace_full(a.data);
}

std::tuple<DataPtr, ElementarySpace::Ptr, float64, float64> NoSymmetryBackend::truncate_singular_values(
    py::object S,
    std::optional<int64> chi_max,
    int64 chi_min,
    float64 degeneracy_tol,
    float64 trunc_cut,
    float64 svd_min,
    bool minimize_error
) {
    /* CHECKME: converted from following python code:
     * S_np = self.block_backend.to_numpy(S.data)
     *         keep, err, new_norm = self._truncate_singular_values_selection(
     *             S=S_np,
     *             qdims=None,
     *             chi_max=chi_max,
     *             chi_min=chi_min,
     *             degeneracy_tol=degeneracy_tol,
     *             trunc_cut=trunc_cut,
     *             svd_min=svd_min,
     *             minimize_error=minimize_error,
     *         )
     * mask_data = self.block_backend.block_from_numpy(keep, dtype=Dtype.bool)
     *         if isinstance(S.leg, ElementarySpace):
     *             is_dual = S.leg.is_dual
     *         else:
     *             is_dual = True
     * new_leg = ElementarySpace.from_trivial_sector(dim=keep.sum(), symmetry=S.symmetry, is_dual=is_dual)
     * return mask_data, new_leg, err, new_norm
     */
    auto /* CHECKME: type? */ S_np = block_backend.to_numpy(S.data);
    std::make_tuple(keep, err, new_norm) = _truncate_singular_values_selection(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['S', 'qdims', 'chi_max', 'chi_min', 'degeneracy_tol', 'trunc_cut', 'svd_min', 'minimize_error'] */;
    auto /* CHECKME: type? */ mask_data = block_backend.block_from_numpy(keep, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */;
    if (isinstance(S.leg, ElementarySpace)) {
        auto /* CHECKME: type? */ is_dual = S.leg.is_dual;
    } else {
        is_dual = true;
    }
    auto /* CHECKME: type? */ new_leg = ElementarySpace.from_trivial_sector(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dim', 'symmetry', 'is_dual'] */;
    return std::make_tuple(mask_data, new_leg, err, new_norm);
}

DataPtr NoSymmetryBackend::zero_data(
    TensorProduct::Ptr codomain,
    TensorProduct::Ptr domain,
    Dtype dtype,
    std::string device,
    bool all_blocks
) {
    /* CHECKME: converted from following python code:
     *         return self.block_backend.zeros(
     *             shape=[l.dim for l in conventional_leg_order(codomain, domain)], dtype=dtype, device=device
     *         )
     */
    return block_backend.zeros(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['shape', 'dtype', 'device'] */;
}

DataPtr NoSymmetryBackend::zero_mask_data(Space::Ptr large_leg, std::string device) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.zeros(shape=[large_leg.dim], dtype=Dtype.bool, device=device)
     */
    return block_backend.zeros(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['shape', 'dtype', 'device'] */;
}

DataPtr NoSymmetryBackend::zero_diagonal_data(TensorProduct::Ptr co_domain, Dtype dtype, std::string device) {
    /* CHECKME: converted from following python code:
     * return self.block_backend.zeros(shape=[co_domain.dim], dtype=dtype, device=device)
     */
    return block_backend.zeros(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['shape', 'dtype', 'device'] */;
}

DataPtr NoSymmetryBackend::wrap(BlockBackend::BlockPtr b) {
    // FIXME: implement
}

BlockBackend::BlockPtr NoSymmetryBackend::unwrap(DataPtr d) {
    // FIXME: implement
}

BlockBackend::BlockPtr NoSymmetryBackend::block_from_tensor(py::object tensor) {
    // FIXME: implement
}
