/*
  Generated by pybind11_mkdoc from include/cyten/tensors/ops_algebra.h.
  Checked into git so builds work without mkdoc/libclang.

  To regenerate (optional; needs pybind11-mkdoc, clangdev, libclang):
    cmake --build <build-dir> --target cyten_mkdoc_docstrings
 */

#define MKD_EXPAND(x) x
#define MKD_COUNT(_1, _2, _3, _4, _5, _6, _7, COUNT, ...) COUNT
#define MKD_VA_SIZE(...) MKD_EXPAND(MKD_COUNT(__VA_ARGS__, 7, 6, 5, 4, 3, 2, 1, 0))
#define MKD_CAT1(a, b) a##b
#define MKD_CAT2(a, b) MKD_CAT1(a, b)
#define MKD_DOC1(n1) mkd_doc_##n1
#define MKD_DOC2(n1, n2) mkd_doc_##n1##_##n2
#define MKD_DOC3(n1, n2, n3) mkd_doc_##n1##_##n2##_##n3
#define MKD_DOC4(n1, n2, n3, n4) mkd_doc_##n1##_##n2##_##n3##_##n4
#define MKD_DOC5(n1, n2, n3, n4, n5) mkd_doc_##n1##_##n2##_##n3##_##n4##_##n5
#define MKD_DOC6(n1, n2, n3, n4, n5, n6) mkd_doc_##n1##_##n2##_##n3##_##n4##_##n5##_##n6
#define MKD_DOC7(n1, n2, n3, n4, n5, n6, n7) mkd_doc_##n1##_##n2##_##n3##_##n4##_##n5##_##n6##_##n7
#define DOC(...) MKD_EXPAND(MKD_EXPAND(MKD_CAT2(MKD_DOC, MKD_VA_SIZE(__VA_ARGS__)))(__VA_ARGS__))

#if defined(__GNUG__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-variable"
#endif

static const char* mkd_doc_cyten_almost_equal =
  R"doc(Checks if two tensors are equal up to numerical tolerance.

We compare the blocks, i.e. the free parameters of the tensors. The
tensors count as almost equal if all block-entries, i.e. all their
free parameters individually fulfill ``abs(a1 - a2) <= atol + rtol *
abs(a1)``.

Parameters
----------
tensor_1, tensor_2 : TensorCPtr
    The tensors to compare.
rtol, atol : float64
    Relative and absolute tolerances.
allow_different_types : bool
    If true, allow comparing tensors of different concrete types.

)doc";

static const char* mkd_doc_cyten_apply_mask =
  R"doc(Apply a projection Mask to one leg of a tensor, *projecting* it to a
smaller leg.

Parameters
----------
tensor : TensorCPtr
    The tensor to project.
mask : MaskCPtr
    Projection mask on ``leg``.
leg : LegRef
    Leg index or label to project.

)doc";

static const char* mkd_doc_cyten_compose =
  R"doc(Tensor contraction as map composition. Requires ``tensor1.domain ==
tensor2.codomain``.

If both tensors have no remaining open legs, returns a scalar.

Parameters
----------
tensor1, tensor2 : TensorCPtr
    Maps to compose: ``tensor1`` after ``tensor2``.
relabel1, relabel2 : std::optional<std::map<std::string, std::string>>
    Optional label maps applied before composition. ``nullopt`` means
    no relabel.

Returns
-------
std::variant<TensorPtr, BlockBackend::Scalar>
    The composed tensor, or a scalar if no open legs remain.

)doc";

static const char* mkd_doc_cyten_dagger =
  R"doc(The hermitian conjugate tensor, a.k.a the dagger of a tensor.)doc";

static const char* mkd_doc_cyten_enlarge_leg =
  R"doc(Apply an inclusion Mask to one leg of a tensor *embedding* it into a
larger leg.

Parameters
----------
tensor : TensorCPtr
    The tensor to enlarge.
mask : MaskCPtr
    Inclusion mask on ``leg``.
leg : LegRef
    Leg index or label to enlarge.

)doc";

static const char* mkd_doc_cyten_get_same_device =
  R"doc(If the given tensors have the same device, return it. Raise otherwise.

Parameters
----------
tensors : std::vector<TensorCPtr>
    Tensors whose devices must agree.
error_msg : std::string
    Message used if devices differ.

)doc";

static const char* mkd_doc_cyten_inner =
  R"doc(The Frobenius inner product of two tensors.

Parameters
----------
A, B : TensorCPtr
    Tensors to take the inner product of.
do_dagger : bool
    If true, dagger ``A`` before contracting.

)doc";

static const char* mkd_doc_cyten_inner_2 =
  R"doc(Inner product of two ``VectorLike`` objects (Tensor or DirectSum).

Parameters
----------
A, B : VectorLikeCPtr
    Vector-like objects to take the inner product of.
do_dagger : bool
    If true, dagger ``A`` before contracting.

)doc";

static const char* mkd_doc_cyten_is_scalar =
  R"doc(If the tensor is a scalar (single-sector, all multiplicities 1).)doc";

static const char* mkd_doc_cyten_item =
  R"doc(If the tensor is a scalar (with only trivial legs), convert to a
Scalar.

)doc";

static const char* mkd_doc_cyten_linear_combination =
  R"doc(The linear combination ``a * v + b * w``.

Parameters
----------
a, b : BlockBackend::Scalar
    Scalar coefficients.
v, w : TensorCPtr
    Tensors to combine.

)doc";

static const char* mkd_doc_cyten_linear_combination_2 =
  R"doc(Linear combination of two ``VectorLike`` objects.

Parameters
----------
a, b : BlockBackend::Scalar
    Scalar coefficients.
v, w : VectorLikeCPtr
    Vector-like objects to combine.

)doc";

static const char* mkd_doc_cyten_norm = R"doc(The Frobenius norm of a Tensor.)doc";

static const char* mkd_doc_cyten_norm_2 =
  R"doc(Norm of a ``VectorLike`` (Tensor or DirectSum).)doc";

static const char* mkd_doc_cyten_on_device =
  R"doc(An equivalent tensor (with the same entries) on another device.

Parameters
----------
tensor : TensorCPtr
    Source tensor.
device : std::string
    Target device name.
copy : bool
    If true, always return a new tensor; otherwise may reuse storage.

)doc";

static const char* mkd_doc_cyten_outer =
  R"doc(The outer product, or tensor product.

Parameters
----------
tensor1, tensor2 : TensorCPtr
    Factors of the outer product.
relabel1, relabel2 : std::optional<std::map<std::string, std::string>>
    Optional label maps. ``nullopt`` means no relabel.

)doc";

static const char* mkd_doc_cyten_partial_compose =
  R"doc(Tensor contraction / composition involving only a part of the full
(co)domain.

Parameters
----------
tensor1, tensor2 : TensorCPtr
    Tensors to partially compose.
tensor1_first_leg : LegRef
    First leg of ``tensor1`` involved in the partial contraction.
relabel1, relabel2 : std::optional<std::map<std::string, std::string>>
    Optional label maps. ``nullopt`` means no relabel.

)doc";

static const char* mkd_doc_cyten_partial_trace =
  R"doc(Perform a partial trace over pairs of legs.

If all legs are traced, returns a scalar.

Parameters
----------
tensor : TensorCPtr
    Tensor to trace.
pairs : std::vector<std::vector<LegRef>>
    Pairs of legs to contract.
levels : std::optional<LevelsSpec>
    Optional per-leg braid levels; ``nullopt`` entries are
    unspecified.

Returns
-------
std::variant<TensorPtr, BlockBackend::Scalar>
    Remaining tensor, or a scalar if everything is traced.

)doc";

static const char* mkd_doc_cyten_pinv =
  R"doc(The Moore-Penrose pseudo-inverse of a tensor.

Parameters
----------
tensor : TensorCPtr
    Tensor to invert.
cutoff : float64
    Singular values below this threshold are discarded.

)doc";

static const char* mkd_doc_cyten_scalar_multiply =
  R"doc(The scalar multiplication ``a * v``.

Parameters
----------
a : BlockBackend::Scalar
    Scalar factor.
v : TensorCPtr
    Tensor to scale.

)doc";

static const char* mkd_doc_cyten_scalar_multiply_2 =
  R"doc(Scalar multiplication of a ``VectorLike``.

Parameters
----------
a : BlockBackend::Scalar
    Scalar factor.
v : VectorLikeCPtr
    Vector-like object to scale.

)doc";

static const char* mkd_doc_cyten_scale_axis =
  R"doc(Contract one `leg` of `tensor` with a diagonal tensor.

Parameters
----------
tensor : TensorCPtr
    Tensor to scale along one axis.
diag : DiagonalTensorCPtr
    Diagonal tensor contracted onto ``leg``.
leg : LegRef
    Leg index or label to contract.

)doc";

static const char* mkd_doc_cyten_tdot =
  R"doc(General tensor contraction, connecting arbitrary pairs of (matching!)
legs.

Parameters
----------
tensor1, tensor2 : TensorCPtr
    Tensors to contract.
legs1, legs2 : std::vector<LegRef>
    Matching legs of ``tensor1`` and ``tensor2`` to contract.
relabel1, relabel2 : std::optional<std::map<std::string, std::string>>
    Optional label maps. ``nullopt`` means no relabel.

Returns
-------
std::variant<TensorPtr, BlockBackend::Scalar>
    Contracted tensor, or a scalar if no open legs remain.

)doc";

static const char* mkd_doc_cyten_trace =
  R"doc(Perform the full trace. Requires ``tensor.domain == tensor.codomain``.)doc";

static const char* mkd_doc_cyten_transpose = R"doc(The transpose of a tensor.)doc";

#if defined(__GNUG__)
#pragma GCC diagnostic pop
#endif
