#include <cyten/tools.h>

#include "py_cyten_pybind11.h"

namespace py = pybind11;
namespace cyten {

void
bind_tools(py::module_& m)
{

    m.def("format_like_list",
          &cyten::format_like_list,
          R"pydoc(
          Format elements of an iterable as if it were a plain list.

          This means surrounding them with brackets and separating them by `', '`.
          )pydoc",
          py::arg("it"));

    m.def("is_iterable", &cyten::is_iterable, py::arg("a"), "If the given object is iterable.");

    m.def("to_iterable",
          &cyten::to_iterable,
          py::arg("a"),
          "If `a` is a not iterable or a string, return [a], else return a.");

    m.def("to_valid_idx",
          &cyten::to_valid_idx,
          py::arg("idx"),
          py::arg("length"),
          "Convert to a valid non-negative index into the given length.");
}

} // namespace cyten
// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_pyb11_binding --py-name BigOMonomial --header-file include/cyten/tools.h --binding-file pybind/py_tools.cpp

py::class_<BigOMonomial, py::smart_holder> big_omonomial(m, "BigOMonomial");
big_omonomial.doc() = R"pydoc(
A symbolic representation of an algorithmic cost as a monomial.

A monomial is of the form ``x^a y^b z^c``, i.e. a product of integer powers.

Attributes
----------
factors : dict {str: int}
    The factor, where an entry ``{'x': n}`` represents the symbol factor ``x^n``.
)pydoc";

big_omonomial // init and attributes
    .def(py::init<std::map<std::string, int64>>())
; // completed big_omonomial attributes

big_omonomial //  methods
    .def("from_str", &BigOMonomial::from_str,
        py::arg("mono"),
        "Initialize from a string representation like ``'x^2 y^3'``."
        )
    .def("__add__", &BigOMonomial::operator+,
        py::arg("other")
        )
    .def("__hash__", &BigOMonomial::__hash__
        )
    .def("__mul__", &BigOMonomial::operator*,
        py::arg("other")
        )
    .def("__repr__", &BigOMonomial::__repr__
        )
    .def("__str__", &BigOMonomial::__str__
        )
    .def("__eq__", &BigOMonomial::operator==,
        py::arg("other")
        )
    .def("is_negligible", &BigOMonomial::is_negligible,
        py::arg("relations") = py::none(),
        "If the given monomial is negligible compared to `others`, s.t. ``O(self + x) = O(x)``."
        )
; // completed big_omonomial methods
// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_pyb11_binding --py-name BigOPolynomial --header-file include/cyten/tools.h --binding-file pybind/py_tools.cpp

py::class_<BigOPolynomial, py::smart_holder> big_opolynomial(m, "BigOPolynomial");
big_opolynomial.doc() = R"pydoc(
A symbolic representation of an algorithmic cost as a monomial.

A polynomial is a sum of :class:`BigOMonomials`\ s, i.e. it is of the form::

    x^a y^b + y^c z^d

i.e. a sum of terms, which consist of integer powers of symbols.

Polynomials can be added and multiplied and compared via :meth:`is_negligible`.

Attributes
----------
terms : list of BigOMonomial
    The terms such that the polynomial is their sum.
)pydoc";

big_opolynomial // init and attributes
    .def(py::init<std::vector<BigOMonomial>>())
    .def_readonly_static("__radd__", &BigOPolynomial::_get___radd__)
    .def_readonly_static("__rmul__", &BigOPolynomial::_get___rmul__)
; // completed big_opolynomial attributes

big_opolynomial //  methods
    .def("simplify_terms", &BigOPolynomial::simplify_terms,
        py::arg("terms"),
        py::arg("relations") = py::none(),
        "Simplify a list of terms by dropping negligible terms."
        )
    .def("from_str", &BigOPolynomial::from_str,
        py::arg("poly"),
        "Initialize from a string representation like ``'x^2 y^3 + x^4'``."
        )
    .def("__repr__", &BigOPolynomial::__repr__
        )
    .def("__str__", &BigOPolynomial::__str__
        )
    .def("__add__", &BigOPolynomial::operator+,
        py::arg("other")
        )
    .def("__eq__", &BigOPolynomial::operator==,
        py::arg("other")
        )
    .def("__hash__", &BigOPolynomial::__hash__
        )
    .def("__mul__", &BigOPolynomial::operator*,
        py::arg("other")
        )
    .def("prod", &BigOPolynomial::prod,
        "Product of multiply symmetries"
        )
; // completed big_opolynomial methods
