#include <cyten/tensors/mask.h>

namespace cyten {

// Mask definitions will be appended by codegen.

} // namespace cyten
// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_definition --py-name Mask --header-file include/cyten/tensors/mask.h --src-file src/tensors/mask.cpp

Mask::Mask(
    TensorBackend::DataPtr data,
    py::object space_in,
    py::object space_out,
    std::optional<bool> is_projection,
    TensorBackend::Ptr backend,
    py::object labels
) {
    /* CHECKME: converted from following python code:
     *         if isinstance(space_in, LegPipe) or isinstance(space_out, LegPipe):
     *             raise ValueError('Mask is not defined on LegPipes.')
     *         if is_projection is None:
     *             if space_in.dim == space_out.dim:
     *                 raise ValueError('Need to specify is_projection for equal spaces.')
     *             is_projection = space_in.dim > space_out.dim
     *         elif is_projection is True:
     *             assert space_in.dim >= space_out.dim
     *         elif is_projection is False:
     *             assert space_in.dim <= space_out.dim
     *         else:
     *             raise TypeError('Invalid is_projection. Expected None or bool.')
     * self.is_projection = is_projection
     *         if is_projection:
     *             assert space_out.is_subspace_of(space_in)
     *         else:
     *             assert space_in.is_subspace_of(space_out)
     * assert space_out.is_dual == space_in.is_dual
     * assert isinstance(space_in, ElementarySpace)
     * assert isinstance(space_out, ElementarySpace)
     *         Tensor.__init__(
     *             self,
     *             codomain=[space_out],
     *             domain=[space_in],
     *             backend=backend,
     *             labels=labels,
     *             dtype=Dtype.bool,
     *             device=backend.get_device_from_data(data),
     *         )
     * self.data = data
     */
    if (isinstance(space_in, LegPipe) || isinstance(space_out, LegPipe)) {
        throw std::invalid_argument("Mask is not defined on LegPipes.");
    }
    if (is_projection == py::none()) {
        if (space_in.dim == space_out.dim) {
            throw std::invalid_argument("Need to specify is_projection for equal spaces.");
        }
        is_projection = space_in.dim > space_out.dim;
    } else {
        if (is_projection == true) {
            /* FIXME: Assert: assert space_in.dim >= space_out.dim */
        } else {
            if (is_projection == false) {
                /* FIXME: Assert: assert space_in.dim <= space_out.dim */
            } else {
                throw std::invalid_argument("Invalid is_projection. Expected None or bool.");
            }
        }
    }
    is_projection = is_projection;
    if (is_projection) {
        /* FIXME: Assert: assert space_out.is_subspace_of(space_in) */
    } else {
        /* FIXME: Assert: assert space_in.is_subspace_of(space_out) */
    }
    /* FIXME: Assert: assert space_out.is_dual == space_in.is_dual */
    /* FIXME: Assert: assert isinstance(space_in, ElementarySpace) */
    /* FIXME: Assert: assert isinstance(space_out, ElementarySpace) */
    Tensor.__init__(self  /* FIXME: standalone self reference */, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['codomain', 'domain', 'backend', 'labels', 'dtype', 'device'] */;
    data = data;
}

Mask::Mask(
    TensorBackend::DataPtr data,
    Space::Ptr space_in,
    Space::Ptr space_out,
    bool is_projection,
    TensorBackend::Ptr backend,
    Symmetry::Ptr symmetry,
    LegLabels labels,
    std::string device
) {
    // FIXME: implement
}

/// property getter
ElementarySpace::Ptr Mask::large_leg() {
    /* CHECKME: converted from following python code:
     *         if self.is_projection:
     *             return self.domain.factors[0]
     *         else:
     *             return self.codomain.factors[0]
     */
    if (is_projection) {
        return domain.factors[0];
    } else {
        return codomain.factors[0];
    }
}

/// property getter
ElementarySpace::Ptr Mask::small_leg() {
    /* CHECKME: converted from following python code:
     *         if self.is_projection:
     *             return self.codomain.factors[0]
     *         else:
     *             return self.domain.factors[0]
     */
    if (is_projection) {
        return codomain.factors[0];
    } else {
        return domain.factors[0];
    }
}

/// Perform sanity checks.
void Mask::test_sanity() {
    /* CHECKME: converted from following python code:
     * super().test_sanity()
     * self.backend.test_mask_sanity(self)
     * assert self.codomain.num_factors == 1 == self.domain.num_factors
     * assert isinstance(self.codomain.factors[0], ElementarySpace)
     * assert isinstance(self.domain.factors[0], ElementarySpace)
     * assert self.large_leg.is_dual == self.small_leg.is_dual
     * assert self.small_leg.is_subspace_of(self.large_leg)
     * assert self.dtype == Dtype.bool
     * assert self.device == self.backend.get_device_from_data(self.data)
     * # check consistency of the basis perm of the small leg.
     *         if self.large_leg._basis_perm is None:
     *             if self.small_leg._basis_perm is None:
     *                 pass  # this is consistent.
     *             else:
     *                 assert np.all(self.small_leg.basis_perm == np.arange(self.small_leg.dim))
     *         else:
     *             mask_in_internal_basis = self.backend.block_backend.to_numpy(self.backend.mask_to_block(self), bool)
     *             pi_1 = self.large_leg.basis_perm
     *             pi_2_inv = self.small_leg.inverse_basis_perm
     *             ranks = pi_1[mask_in_internal_basis][pi_2_inv]
     *             # check if ranks is sorted
     *             assert np.all(ranks[:-1] < ranks[1:])
     */
    super().test_sanity();
    backend.test_mask_sanity(self  /* FIXME: standalone self reference */);
    /* FIXME: Assert: assert self.codomain.num_factors == 1 == self.domain.num_factors */
    /* FIXME: Assert: assert isinstance(self.codomain.factors[0], ElementarySpace) */
    /* FIXME: Assert: assert isinstance(self.domain.factors[0], ElementarySpace) */
    /* FIXME: Assert: assert self.large_leg.is_dual == self.small_leg.is_dual */
    /* FIXME: Assert: assert self.small_leg.is_subspace_of(self.large_leg) */
    /* FIXME: Assert: assert self.dtype == Dtype.bool */
    /* FIXME: Assert: assert self.device == self.backend.get_device_from_data(self.data) */
    // check consistency of the basis perm of the small leg.
    if (large_leg._basis_perm == py::none()) {
        if (small_leg._basis_perm == py::none()) {
            // pass
            /* this is consistent. */
        } else {
            /* FIXME: Assert: assert np.all(self.small_leg.basis_perm == np.arange(self.small_leg.dim)) */
        }
    } else {
        auto /* CHECKME: type? */ mask_in_internal_basis = backend.block_backend.to_numpy(backend.mask_to_block(self  /* FIXME: standalone self reference */), bool);
        auto /* CHECKME: type? */ pi_1 = large_leg.basis_perm;
        auto /* CHECKME: type? */ pi_2_inv = small_leg.inverse_basis_perm;
        auto /* CHECKME: type? */ ranks = pi_1[mask_in_internal_basis][pi_2_inv];
        // check if ranks is sorted
        /* FIXME: Assert: assert np.all(ranks[:-1] < ranks[1:]) */
    }
}

/// property getter
ElementarySpace::Ptr Mask::large_leg() {
    /* CHECKME: converted from following python code:
     *         if self.is_projection:
     *             return self.domain.factors[0]
     *         else:
     *             return self.codomain.factors[0]
     */
    if (is_projection) {
        return domain.factors[0];
    } else {
        return codomain.factors[0];
    }
}

/// property getter
ElementarySpace::Ptr Mask::small_leg() {
    /* CHECKME: converted from following python code:
     *         if self.is_projection:
     *             return self.codomain.factors[0]
     *         else:
     *             return self.domain.factors[0]
     */
    if (is_projection) {
        return codomain.factors[0];
    } else {
        return domain.factors[0];
    }
}

/// The identity map as a Mask, i.e. the mask that keeps all states and discards none.
Ptr Mask::from_eye(
    py::object leg,
    bool is_projection,
    TensorBackend::Ptr backend,
    py::object labels,
    std::optional<std::string> device
) {
    /* CHECKME: converted from following python code:
     * diag = DiagonalTensor.from_eye(leg=leg, backend=backend, labels=labels, dtype=Dtype.bool, device=device)
     * res = cls.from_DiagonalTensor(diag)
     *         if not is_projection:
     *             return dagger(res)
     * return res
     */
    auto /* CHECKME: type? */ diag = DiagonalTensor.from_eye(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['leg', 'backend', 'labels', 'dtype', 'device'] */;
    auto /* CHECKME: type? */ res = cls.from_DiagonalTensor(diag);
    if (!is_projection) {
        return dagger(res);
    }
    return res;
}

/// Create a projection Mask from a boolean block.
Ptr Mask::from_block_mask(
    BlockBackend::BlockPtr block_mask,
    py::object large_leg,
    TensorBackend::Ptr backend,
    py::object labels,
    std::optional<std::string> device
) {
    /* CHECKME: converted from following python code:
     *         if not large_leg.symmetry.can_be_dropped:
     *             msg = f'Dense block representation is not supported for symmetry {large_leg.symmetry}'
     *             raise SymmetricTensor(msg)
     *         if backend is None:
     *             backend = get_backend(symmetry=large_leg.symmetry)
     * block_mask = backend.block_backend.as_block(block_mask, Dtype.bool, device=device)
     * block_mask = backend.block_backend.apply_basis_perm(block_mask, [large_leg])
     * data, small_leg = backend.mask_from_block(block_mask, large_leg=large_leg)
     *         return cls(
     *             data=data, space_in=large_leg, space_out=small_leg, is_projection=True, backend=backend, labels=labels
     *         )
     */
    if (!large_leg.symmetry.can_be_dropped) {
        auto /* CHECKME: type? */ msg = std::format("Dense block representation is not supported for symmetry {}", large_leg.symmetry);
        throw std::runtime_error(msg);
    }
    if (backend == py::none()) {
        backend = get_backend(py::arg({keyword.key}) = val) /* CHECKME: keywords ['symmetry'] */;
    }
    block_mask = backend.block_backend.as_block(block_mask, Dtype.bool, py::arg({keyword.key}) = val) /* CHECKME: keywords ['device'] */;
    block_mask = backend.block_backend.apply_basis_perm(block_mask, {large_leg});
    std::make_tuple(data, small_leg) = backend.mask_from_block(block_mask, py::arg({keyword.key}) = val) /* CHECKME: keywords ['large_leg'] */;
    return cls(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['data', 'space_in', 'space_out', 'is_projection', 'backend', 'labels'] */;
}

/// Create a projection Mask from a boolean DiagonalTensor.
Ptr Mask::from_DiagonalTensor(py::object diag) {
    /* CHECKME: converted from following python code:
     * assert diag.dtype == Dtype.bool
     * data, small_leg = diag.backend.diagonal_to_mask(diag)
     *         return cls(
     *             data=data,
     *             space_in=diag.domain.factors[0],
     *             space_out=small_leg,
     *             is_projection=True,
     *             backend=diag.backend,
     *             labels=diag.labels,
     *         )
     */
    /* FIXME: Assert: assert diag.dtype == Dtype.bool */
    std::make_tuple(data, small_leg) = diag.backend.diagonal_to_mask(diag);
    return cls(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['data', 'space_in', 'space_out', 'is_projection', 'backend', 'labels'] */;
}

/// Create a projection Mask from the indices that are kept.
Ptr Mask::from_indices(
    py::object indices,
    py::object large_leg,
    TensorBackend::Ptr backend,
    py::object labels,
    std::optional<std::string> device
) {
    /* CHECKME: converted from following python code:
     * block_mask = np.zeros(large_leg.dim, bool)
     * block_mask[indices] = True
     * return cls.from_block_mask(block_mask, large_leg=large_leg, backend=backend, labels=labels, device=device)
     */
    auto /* CHECKME: type? */ block_mask = np.zeros(large_leg.dim, bool);
    block_mask[indices] = true;
    return cls.from_block_mask(block_mask, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['large_leg', 'backend', 'labels', 'device'] */;
}

/// Create a random projection Mask.
Ptr Mask::from_random(
    py::object large_leg,
    py::object small_leg,
    TensorBackend::Ptr backend,
    float64 p_keep,
    int64 min_keep,
    py::object labels,
    std::optional<std::string> device,
    py::object np_random
) {
    /* CHECKME: converted from following python code:
     *         if backend is None:
     *             backend = get_backend(symmetry=large_leg.symmetry)
     *         if not isinstance(large_leg, ElementarySpace):
     *             raise ValueError('large_leg must be ElementarySpace.')
     *         if small_leg is None:
     *             assert 0 <= p_keep <= 1
     *             diag = DiagonalTensor.from_random_uniform(
     *                 large_leg, backend=backend, labels=labels, dtype=Dtype.float32, device=device
     *             )
     *             cutoff = 2 * p_keep - 1  # diagonal entries are uniform in [-1, 1].
     *             res = cls.from_DiagonalTensor(diag < cutoff)
     * 
     *             if np.sum(res.small_leg.multiplicities) >= min_keep:
     *                 return res
     * 
     *             large_leg_sector_num = np.sum(large_leg.multiplicities)
     *             assert min_keep <= large_leg_sector_num, 'min_keep can not be fulfilled'
     *             if min_keep == large_leg_sector_num:
     *                 return Mask.from_eye(large_leg, is_projection=True, backend=backend, labels=labels)
     *             # explicitly constructing the small_leg with exactly min_keep sectors kept is
     *             # quite annoying bc of basis_perm. Instead we increase p_keep until we get there.
     *             # first, try a heuristic
     *             p_keep = np.ceil(1.05 * min_keep / np.sum(large_leg.multiplicities))
     *             res = cls.from_DiagonalTensor(diag < (2 * p_keep - 1))
     *             for _ in range(20):
     *                 if np.sum(res.small_leg.multiplicities) >= min_keep:
     *                     return res
     *                 p_keep = 0.5 * (p_keep + 1)  # step halfway towards 100%
     *                 res = cls.from_DiagonalTensor(diag < (2 * p_keep - 1))
     *             raise RuntimeError('Could not fulfill min_keep')
     *         if not small_leg.is_subspace_of(large_leg):
     *             raise ValueError('small_leg must be a subspace of the large leg.')
     *         if not isinstance(small_leg, ElementarySpace):
     *             raise ValueError('small_leg must be ElementarySpace.')
     *         large_perm_trivial = large_leg._basis_perm is None or np.all(
     *             large_leg._basis_perm == np.arange(len(large_leg._basis_perm))
     *         )
     *         small_perm_trivial = small_leg._basis_perm is None or np.all(
     *             small_leg._basis_perm == np.arange(len(small_leg._basis_perm))
     *         )
     *         if (not large_perm_trivial) or (not small_perm_trivial):
     *             msg = 'Generating random Masks with non-trivial, fixed basis_perm is hard and hopefully never needed.'
     *             raise NotImplementedError(msg)
     *         def func(shape, coupled):
     *             num_keep = small_leg.sector_multiplicity(coupled)
     *             block = np.zeros(shape, bool)
     *             which = np_random.choice(shape[0], size=num_keep, replace=False)
     *             block[which] = True
     *             return block
     *         diag = DiagonalTensor.from_sector_block_func(
     *             func, leg=large_leg, backend=backend, labels=labels, dtype=Dtype.bool, device=device
     *         )
     * res = cls.from_DiagonalTensor(diag)
     * assert res.small_leg == small_leg
     * return res
     */
    if (backend == py::none()) {
        backend = get_backend(py::arg({keyword.key}) = val) /* CHECKME: keywords ['symmetry'] */;
    }
    if (!(isinstance(large_leg, ElementarySpace))) {
        throw std::invalid_argument("large_leg must be ElementarySpace.");
    }
    if (small_leg == py::none()) {
        /* FIXME: Assert: assert 0 <= p_keep <= 1 */
        auto /* CHECKME: type? */ diag = DiagonalTensor.from_random_uniform(large_leg, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['backend', 'labels', 'dtype', 'device'] */;
        auto /* CHECKME: type? */ cutoff = 2 * p_keep - 1;
        /* diagonal entries are uniform in [-1, 1]. */
        auto /* CHECKME: type? */ res = cls.from_DiagonalTensor(diag < cutoff);
        if (np.sum(res.small_leg.multiplicities) >= min_keep) {
            return res;
        }
        auto /* CHECKME: type? */ large_leg_sector_num = np.sum(large_leg.multiplicities);
        /* FIXME: Assert: assert min_keep <= large_leg_sector_num, 'min_keep can not be fulfilled' */
        if (min_keep == large_leg_sector_num) {
            return Mask.from_eye(large_leg, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['is_projection', 'backend', 'labels'] */;
        }
        // explicitly constructing the small_leg with exactly min_keep sectors kept is
        // quite annoying bc of basis_perm. Instead we increase p_keep until we get there.
        // first, try a heuristic
        p_keep = np.ceil(1.05 * min_keep / np.sum(large_leg.multiplicities));
        res = cls.from_DiagonalTensor(diag < 2 * p_keep - 1);
        for (auto _ = 0; _ < 20; ++_) {
            if (np.sum(res.small_leg.multiplicities) >= min_keep) {
                return res;
            }
            p_keep = 0.5 * p_keep + 1;
            /* step halfway towards 100% */
            res = cls.from_DiagonalTensor(diag < 2 * p_keep - 1);
        }
        throw std::runtime_error("Could not fulfill min_keep");
    }
    if (!small_leg.is_subspace_of(large_leg)) {
        throw std::invalid_argument("small_leg must be a subspace of the large leg.");
    }
    if (!(isinstance(small_leg, ElementarySpace))) {
        throw std::invalid_argument("small_leg must be ElementarySpace.");
    }
    auto /* CHECKME: type? */ large_perm_trivial = large_leg._basis_perm == py::none() || np.all(large_leg._basis_perm == np.arange(len(large_leg._basis_perm)));
    auto /* CHECKME: type? */ small_perm_trivial = small_leg._basis_perm == py::none() || np.all(small_leg._basis_perm == np.arange(len(small_leg._basis_perm)));
    if (!large_perm_trivial || !small_perm_trivial) {
        auto /* CHECKME: type? */ msg = "Generating random Masks with non-trivial, fixed basis_perm is hard and hopefully never needed.";
        throw std::logic_error(msg);
    }
    /* FIXME: FunctionDef:         def func(shape, coupled):
            num_keep = small_leg.sector_multiplicity(coupled)
            block = np.zeros(shape, bool)
            which = np_random.choice(shape[0], size=num_keep, replace=False)
            block[which] = True
            return block */
    diag = DiagonalTensor.from_sector_block_func(func, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['leg', 'backend', 'labels', 'dtype', 'device'] */;
    res = cls.from_DiagonalTensor(diag);
    /* FIXME: Assert: assert res.small_leg == small_leg */
    return res;
}

/// The zero projection Mask, that discards all states and keeps none.
Ptr Mask::from_zero(
    py::object large_leg,
    TensorBackend::Ptr backend,
    py::object labels,
    std::optional<std::string> device
) {
    /* CHECKME: converted from following python code:
     *         if backend is None:
     *             backend = get_backend(symmetry=large_leg.symmetry)
     * device = backend.block_backend.as_device(device)
     * data = backend.zero_mask_data(large_leg=large_leg, device=device)
     *         if isinstance(large_leg, ElementarySpace):
     *             is_dual = large_leg.is_dual
     *         else:
     *             is_dual = False
     * small_leg = ElementarySpace.from_null_space(symmetry=large_leg.symmetry, is_dual=is_dual)
     * return cls(data, space_in=large_leg, space_out=small_leg, is_projection=True, backend=backend, labels=labels)
     */
    if (backend == py::none()) {
        backend = get_backend(py::arg({keyword.key}) = val) /* CHECKME: keywords ['symmetry'] */;
    }
    device = backend.block_backend.as_device(device);
    auto /* CHECKME: type? */ data = backend.zero_mask_data(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['large_leg', 'device'] */;
    if (isinstance(large_leg, ElementarySpace)) {
        auto /* CHECKME: type? */ is_dual = large_leg.is_dual;
    } else {
        is_dual = false;
    }
    auto /* CHECKME: type? */ small_leg = ElementarySpace.from_null_space(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['symmetry', 'is_dual'] */;
    return cls(data, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['space_in', 'space_out', 'is_projection', 'backend', 'labels'] */;
}

TYPEOF_return Mask::operator&(TYPEOF_other other) {
    /* CHECKME: converted from following python code:
     * # ``self & other``
     * return self._binary_operand(other, operator.and_, '&')
     */
    /* ``self & other`` */
    return _binary_operand(other, operator.and_, "&");
}

bool Mask::operator bool() {
    /* CHECKME: converted from following python code:
     * msg = 'The truth value of a Mask is ambiguous. Use a.any() or a.all()'
     * raise TypeError(msg)
     */
    auto /* CHECKME: type? */ msg = "The truth value of a Mask is ambiguous. Use a.any() or a.all()";
    throw std::invalid_argument(msg);
}

bool Mask::operator==(TYPEOF_other other) {
    /* CHECKME: converted from following python code:
     * # ``self == other``
     * return self._binary_operand(other, func=operator.eq, operand='==')
     */
    /* ``self == other`` */
    return _binary_operand(other, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['func', 'operand'] */;
}

TYPEOF_return Mask::operator~() {
    /* CHECKME: converted from following python code:
     * # ``~self``
     * return self._unary_operand(operator.invert)
     */
    /* ``~self`` */
    return _unary_operand(operator.invert);
}

bool Mask::operator!=(TYPEOF_other other) {
    /* CHECKME: converted from following python code:
     * # ``self != other``
     * return self._binary_operand(other, func=operator.ne, operand='!=')
     */
    /* ``self != other`` */
    return _binary_operand(other, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['func', 'operand'] */;
}

TYPEOF_return Mask::operator|(TYPEOF_other other) {
    /* CHECKME: converted from following python code:
     * # ``self | other``
     * return self._binary_operand(other, func=operator.or_, operand='|')
     */
    /* ``self | other`` */
    return _binary_operand(other, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['func', 'operand'] */;
}

TYPEOF_return Mask::__rand__(TYPEOF_other other) {
    /* CHECKME: converted from following python code:
     * # ``other & self``
     * return self._binary_operand(other, func=operator.and_, operand='&')
     */
    /* ``other & self`` */
    return _binary_operand(other, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['func', 'operand'] */;
}

TYPEOF_return Mask::__ror__(TYPEOF_other other) {
    /* CHECKME: converted from following python code:
     * # ``other | self``
     * return self._binary_operand(other, func=operator.or_, operand='|')
     */
    /* ``other | self`` */
    return _binary_operand(other, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['func', 'operand'] */;
}

TYPEOF_return Mask::__rxor__(TYPEOF_other other) {
    /* CHECKME: converted from following python code:
     * # ``other ^ self``
     * return self._binary_operand(other, func=operator.xor, operand='^')
     */
    /* ``other ^ self`` */
    return _binary_operand(other, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['func', 'operand'] */;
}

TYPEOF_return Mask::operator^(TYPEOF_other other) {
    /* CHECKME: converted from following python code:
     * # ``self ^ other``
     * return self._binary_operand(other, func=operator.xor, operand='^')
     */
    /* ``self ^ other`` */
    return _binary_operand(other, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['func', 'operand'] */;
}

/// If the mask keeps all basis elements
bool Mask::all() {
    /* CHECKME: converted from following python code:
     * # assuming subspace, it is enough to check that the total sector number is the same.
     * return np.sum(self.small_leg.multiplicities) == np.sum(self.large_leg.multiplicities)
     */
    // assuming subspace, it is enough to check that the total sector number is the same.
    return np.sum(small_leg.multiplicities) == np.sum(large_leg.multiplicities);
}

/// If the mask keeps any basis elements
bool Mask::any() {
    /* CHECKME: converted from following python code:
     * return self.small_leg.dim > 0
     */
    return small_leg.dim > 0;
}

BlockBackend::BlockPtr Mask::as_block_mask() {
    /* CHECKME: converted from following python code:
     * res = self.backend.mask_to_block(self)
     * return self.backend.block_backend.apply_basis_perm(res, [self.large_leg], inv=True)
     */
    auto /* CHECKME: type? */ res = backend.mask_to_block(self  /* FIXME: standalone self reference */);
    return backend.block_backend.apply_basis_perm(res, {large_leg}, py::arg({keyword.key}) = val) /* CHECKME: keywords ['inv'] */;
}

py::array Mask::as_numpy_mask() {
    /* CHECKME: converted from following python code:
     * res = self.as_block_mask()
     * return self.backend.block_backend.to_numpy(res, numpy_dtype=bool)
     */
    auto /* CHECKME: type? */ res = as_block_mask();
    return backend.block_backend.to_numpy(res, py::arg({keyword.key}) = val) /* CHECKME: keywords ['numpy_dtype'] */;
}

Tensor::Ptr Mask::as_dtype(Dtype dtype) {
    /* CHECKME: converted from following python code:
     *         if dtype == self.dtype:
     *             return self
     *         raise ValueError(
     *             'Mask requires Dtype.bool; use as_DiagonalTensor() or as_SymmetricTensor() '
     *             'for conversion to other tensor classes'
     *         )
     */
    if (dtype == dtype) {
        return self  /* FIXME: standalone self reference */;
    }
    throw std::invalid_argument("Mask requires Dtype.bool; use as_DiagonalTensor() or as_SymmetricTensor() for conversion to other tensor classes");
}

DiagonalTensor::Ptr Mask::as_DiagonalTensor(Dtype dtype) {
    /* CHECKME: converted from following python code:
     *         return DiagonalTensor(
     *             data=self.backend.mask_to_diagonal(self, dtype=dtype),
     *             leg=self.large_leg,
     *             backend=self.backend,
     *             labels=self.labels,
     *         )
     */
    return DiagonalTensor(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['data', 'leg', 'backend', 'labels'] */;
}

py::object Mask::as_SymmetricTensor(bool guarantee_copy, std::optional<std::string> warning, Dtype dtype) {
    /* CHECKME: converted from following python code:
     *         if warning is not None:
     *             warnings.warn(warning, UserWarning, stacklevel=2)
     *         if not self.is_projection:
     *             # OPTIMIZE how hard is it to deal with inclusions in the backend?
     *             return dagger(dagger(self).as_SymmetricTensor())
     * data = self.backend.full_data_from_mask(self, dtype)
     *         return SymmetricTensor(
     *             data, codomain=self.codomain, domain=self.domain, backend=self.backend, labels=self.labels
     *         )
     */
    if (warning != py::none()) {
        warnings.warn(warning, UserWarning, py::arg({keyword.key}) = val) /* CHECKME: keywords ['stacklevel'] */;
    }
    if (!is_projection) {
        // OPTIMIZE how hard is it to deal with inclusions in the backend?
        return dagger(dagger(self  /* FIXME: standalone self reference */).as_SymmetricTensor());
    }
    auto /* CHECKME: type? */ data = backend.full_data_from_mask(self  /* FIXME: standalone self reference */, dtype);
    return SymmetricTensor(data, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['codomain', 'domain', 'backend', 'labels'] */;
}

/// Utility function for a shared implementation of binary functions.
py::object Mask::_binary_operand(
    py::object other,
    py::function func,
    const std::string & operand,
    bool return_NotImplemented
) {
    /* CHECKME: converted from following python code:
     * # deal with non-Mask types
     *         if isinstance(other, bool):
     *             return self._unary_operand(lambda block: func(block, other))
     *         elif isinstance(other, Mask):
     *             pass
     *         elif return_NotImplemented and not isinstance(other, (Tensor, Number)):
     *             return NotImplemented
     *         else:
     *             msg = f'Invalid types for operand "{operand}": {type(self)} and {type(other)}'
     *             raise TypeError(msg)
     * # remaining case: other is Mask
     *         if self.is_projection != other.is_projection:
     *             raise ValueError('Mismatching is_projection.')
     *         if not self.is_projection:
     *             # OPTIMIZE how hard is it to deal with inclusions in the backend?
     *             res_projection = dagger(self)._binary_operand(
     *                 dagger(other), func=func, operand=operand, return_NotImplemented=return_NotImplemented
     *             )
     *             return dagger(res_projection)
     * backend = get_same_backend(self, other)
     *         if self.domain != other.domain:
     *             raise ValueError('Incompatible domain.')
     * data, small_leg = backend.mask_binary_operand(self, other, func)
     *         return Mask(
     *             data,
     *             space_in=self.large_leg,
     *             space_out=small_leg,
     *             is_projection=self.is_projection,
     *             backend=backend,
     *             labels=_get_matching_labels(self.labels, other.labels),
     *         )
     */
    // deal with non-Mask types
    if (isinstance(other, bool)) {
        return _unary_operand(/* FIXME: Lambda: lambda block: func(block, other) */);
    } else {
        if (isinstance(other, Mask)) {
            // pass
        } else {
            if (return_NotImplemented && !(isinstance(other, std::make_tuple(Tensor, Number)))) {
                return NotImplemented;
            } else {
                auto /* CHECKME: type? */ msg = std::format("Invalid types for operand \"{}\": {} and {}", operand, type(self  /* FIXME: standalone self reference */), type(other));
                throw std::invalid_argument(msg);
            }
        }
    }
    // remaining case: other is Mask
    if (is_projection != other.is_projection) {
        throw std::invalid_argument("Mismatching is_projection.");
    }
    if (!is_projection) {
        // OPTIMIZE how hard is it to deal with inclusions in the backend?
        auto /* CHECKME: type? */ res_projection = dagger(self  /* FIXME: standalone self reference */)._binary_operand(dagger(other), py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['func', 'operand', 'return_NotImplemented'] */;
        return dagger(res_projection);
    }
    auto /* CHECKME: type? */ backend = get_same_backend(self  /* FIXME: standalone self reference */, other);
    if (domain != other.domain) {
        throw std::invalid_argument("Incompatible domain.");
    }
    std::make_tuple(data, small_leg) = backend.mask_binary_operand(self  /* FIXME: standalone self reference */, other, func);
    return Mask(data, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['space_in', 'space_out', 'is_projection', 'backend', 'labels'] */;
}

Tensor::Ptr Mask::copy(bool deep, std::optional<std::string> device, std::optional<Dtype> dtype) {
    /* CHECKME: converted from following python code:
     *         if dtype is not None and dtype != self.dtype:
     *             if device is not None or device != self.device:
     *                 return self.as_dtype(dtype)
     *             data = self.backend.move_to_device(self.as_dtype(dtype), device=device)
     *         elif deep:
     *             data = self.backend.copy_data(self)
     *         elif device is not None:
     *             data = self.backend.move_to_device(self, device=device)
     *         else:
     *             data = self.data
     *         return Mask(
     *             data,
     *             space_in=self.large_leg,
     *             space_out=self.small_leg,
     *             is_projection=self.is_projection,
     *             backend=self.backend,
     *             labels=self.labels,
     *         )
     */
    if (dtype != py::none() && dtype != dtype) {
        if (device != py::none() || device != device) {
            return as_dtype(dtype);
        }
        auto /* CHECKME: type? */ data = backend.move_to_device(as_dtype(dtype), py::arg({keyword.key}) = val) /* CHECKME: keywords ['device'] */;
    } else {
        if (deep) {
            data = backend.copy_data(self  /* FIXME: standalone self reference */);
        } else {
            if (device != py::none()) {
                data = backend.move_to_device(self  /* FIXME: standalone self reference */, py::arg({keyword.key}) = val) /* CHECKME: keywords ['device'] */;
            } else {
                data = data;
            }
        }
    }
    return Mask(data, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['space_in', 'space_out', 'is_projection', 'backend', 'labels'] */;
}

BlockBackend::Scalar Mask::_get_item(const std::vector<int64> & idx) {
    /* CHECKME: converted from following python code:
     * return self.backend.get_element_mask(self, idx)
     */
    return backend.get_element_mask(self  /* FIXME: standalone self reference */, idx);
}

/// Alias for :meth:`orthogonal_complement`
Ptr Mask::logical_not() {
    /* CHECKME: converted from following python code:
     * return self._unary_operand(operator.invert)
     */
    return _unary_operand(operator.invert);
}

void Mask::move_to_device(std::string device) {
    /* CHECKME: converted from following python code:
     * self.data = self.backend.move_to_device(self, device=device)
     * self.device = self.backend.block_backend.as_device(device)
     */
    data = backend.move_to_device(self  /* FIXME: standalone self reference */, py::arg({keyword.key}) = val) /* CHECKME: keywords ['device'] */;
    device = backend.block_backend.as_device(device);
}

/// The "opposite" Mask, that keeps exactly what self discards and vv.
Ptr Mask::orthogonal_complement() {
    /* CHECKME: converted from following python code:
     * return self._unary_operand(operator.invert)
     */
    return _unary_operand(operator.invert);
}

Tensor::Ptr Mask::to_backend(TensorBackend::Ptr backend, std::optional<Dtype> dtype, std::optional<std::string> device) {
    /* CHECKME: converted from following python code:
     *         if not backend.supports_symmetry(self.symmetry):
     *             raise SymmetryError('backend does not support symmetry')
     *         if not (dtype is None or dtype == Dtype.bool):
     *             raise ValueError('Mask requires Dtype.bool')
     * # similar to DiagonalTensor, we can just go via dense mask, with some exceptions.
     * # these exceptions only occurr for FusionTreeBackend -> FusionTreeBackend, and that allows
     * # a simple implementation directly
     * device = backend.block_backend.as_device(self.device if device is None else device)
     *         if isinstance(self.backend, FusionTreeBackend) and isinstance(backend, FusionTreeBackend):
     *             new_data = self.backend.to_block_backend(self.data, backend.block_backend, dtype=Dtype.bool, device=device)
     *         else:
     *             old_mask = self.backend.mask_to_block(self)
     *             new_mask = backend.block_backend.as_block(old_mask, dtype=Dtype.bool, device=device)
     *             new_data, _ = backend.mask_from_block(new_mask, large_leg=self.large_leg)
     *             if isinstance(backend, AbelianBackend) and not self.is_projection:
     *                 # mask_from_block assumes projection mask -> swap block_inds for inclusion
     *                 new_data.block_inds = new_data.block_inds[:, ::-1]
     *         return Mask(
     *             new_data,
     *             space_in=self.domain[0],
     *             space_out=self.codomain[0],
     *             is_projection=self.is_projection,
     *             backend=backend,
     *             labels=self.labels,
     *         )
     */
    if (!backend.supports_symmetry(symmetry)) {
        throw std::runtime_error("backend does not support symmetry");
    }
    if (!(dtype == py::none() || dtype == Dtype.bool)) {
        throw std::invalid_argument("Mask requires Dtype.bool");
    }
    // similar to DiagonalTensor, we can just go via dense mask, with some exceptions.
    // these exceptions only occurr for FusionTreeBackend -> FusionTreeBackend, and that allows
    // a simple implementation directly
    device = backend.block_backend.as_device(device == py::none() ? device : device);
    if (isinstance(backend, FusionTreeBackend) && isinstance(backend, FusionTreeBackend)) {
        auto /* CHECKME: type? */ new_data = backend.to_block_backend(data, backend.block_backend, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype', 'device'] */;
    } else {
        auto /* CHECKME: type? */ old_mask = backend.mask_to_block(self  /* FIXME: standalone self reference */);
        auto /* CHECKME: type? */ new_mask = backend.block_backend.as_block(old_mask, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype', 'device'] */;
        std::make_tuple(new_data, _) = backend.mask_from_block(new_mask, py::arg({keyword.key}) = val) /* CHECKME: keywords ['large_leg'] */;
        if (isinstance(backend, AbelianBackend) && !is_projection) {
            // mask_from_block assumes projection mask -> swap block_inds for inclusion
            new_data.block_inds = /* Multidimensional slice using std::gslice
 * NOTE: Requires new_data.block_inds_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   new_data.block_inds_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
new_data.block_inds[std::gslice(0, std::valarray<std::size_t>{new_data.block_inds.shape(0), new_data.block_inds.shape(1)}, std::valarray<std::size_t>{new_data.block_inds_strides[0], new_data.block_inds_strides[1] * -1})];
        }
    }
    return Mask(new_data, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['space_in', 'space_out', 'is_projection', 'backend', 'labels'] */;
}

BlockBackend::BlockPtr Mask::to_dense_block(
    std::optional<std::vector<std::variant<int64, std::string>>> leg_order,
    std::optional<Dtype> dtype,
    bool understood_braiding
) {
    /* CHECKME: converted from following python code:
     *         if not self.symmetry.can_be_dropped:
     *             msg = f'Dense block representation is not supported for symmetry {self.symmetry}'
     *             raise SymmetryError(msg)
     *         if not self.symmetry.has_trivial_braid and not understood_braiding:
     *             msg = (
     *                 'If the symmetry has non-trivial braids, dense block representations do not '
     *                 'consistently reproduce the braiding statistics. Make sure you understand what '
     *                 'that means (read the docstring of to_dense_block). Then you can disable '
     *                 'this error by setting ``understood_braiding=True``.'
     *             )
     *             raise SymmetryError(msg)
     * # for Mask, defining via numpy is actually easier, to use numpy indexing
     * numpy_dtype = None if dtype is None else dtype.to_numpy_dtype()
     * as_numpy = self.to_numpy(leg_order=leg_order, numpy_dtype=numpy_dtype)
     * return self.backend.block_backend.as_block(as_numpy, dtype=dtype)
     */
    if (!symmetry.can_be_dropped) {
        auto /* CHECKME: type? */ msg = std::format("Dense block representation is not supported for symmetry {}", symmetry);
        throw std::runtime_error(msg);
    }
    if (!symmetry.has_trivial_braid && !understood_braiding) {
        msg = "If the symmetry has non-trivial braids, dense block representations do not consistently reproduce the braiding statistics. Make sure you understand what that means (read the docstring of to_dense_block). Then you can disable this error by setting ``understood_braiding=True``.";
        throw std::runtime_error(msg);
    }
    // for Mask, defining via numpy is actually easier, to use numpy indexing
    auto /* CHECKME: type? */ numpy_dtype = dtype == py::none() ? py::none() : dtype.to_numpy_dtype();
    auto /* CHECKME: type? */ as_numpy = to_numpy(py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['leg_order', 'numpy_dtype'] */;
    return backend.block_backend.as_block(as_numpy, py::arg({keyword.key}) = val) /* CHECKME: keywords ['dtype'] */;
}

py::array Mask::to_numpy(
    std::optional<std::vector<std::variant<int64, std::string>>> leg_order,
    py::object numpy_dtype,
    bool understood_braiding
) {
    /* CHECKME: converted from following python code:
     *         if not self.symmetry.can_be_dropped:
     *             msg = f'Dense block representation is not supported for symmetry {self.symmetry}'
     *             raise SymmetryError(msg)
     *         if not self.symmetry.has_trivial_braid and not understood_braiding:
     *             msg = (
     *                 'If the symmetry has non-trivial braids, dense block representations do not '
     *                 'consistently reproduce the braiding statistics. Make sure you understand what '
     *                 'that means (read the docstring of to_dense_block). Then you can disable '
     *                 'this error by setting ``understood_braiding=True``.'
     *             )
     *             raise SymmetryError(msg)
     * assert self.symmetry.can_be_dropped
     * mask = self.as_numpy_mask()
     * res = np.zeros(self.shape, numpy_dtype or bool)
     * m, n = self.shape
     *         if self.is_projection:
     *             res[np.arange(m), mask] = 1  # sets the appropriate dtype. e.g. sets ``True`` for bool.
     *         else:
     *             res[mask, np.arange(n)] = 1
     *         if leg_order is not None:
     *             res = np.transpose(res, self.get_leg_idcs(leg_order))
     * return res
     */
    if (!symmetry.can_be_dropped) {
        auto /* CHECKME: type? */ msg = std::format("Dense block representation is not supported for symmetry {}", symmetry);
        throw std::runtime_error(msg);
    }
    if (!symmetry.has_trivial_braid && !understood_braiding) {
        msg = "If the symmetry has non-trivial braids, dense block representations do not consistently reproduce the braiding statistics. Make sure you understand what that means (read the docstring of to_dense_block). Then you can disable this error by setting ``understood_braiding=True``.";
        throw std::runtime_error(msg);
    }
    /* FIXME: Assert: assert self.symmetry.can_be_dropped */
    auto /* CHECKME: type? */ mask = as_numpy_mask();
    auto /* CHECKME: type? */ res = np.zeros(shape, numpy_dtype || bool);
    std::make_tuple(m, n) = shape;
    if (is_projection) {
        /* Multidimensional slice using std::gslice
 * NOTE: Requires res_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   res_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
res[std::gslice(np.arange(m) * res_strides[0] + mask * res_strides[1], std::valarray<std::size_t>{1, 1}, std::valarray<std::size_t>{res_strides[0], res_strides[1]})] = 1;
        /* sets the appropriate dtype. e.g. sets ``True`` for bool. */
    } else {
        /* Multidimensional slice using std::gslice
 * NOTE: Requires res_strides to be defined as std::valarray<size_t>
 *       containing the memory strides for each dimension.
 * For a row-major 2D array with shape (n0, n1, ..., n1):
 *   res_strides = {n1, 1};
 * Alternative: Consider using xtensor, Eigen, or C++23 mdspan
 */
res[std::gslice(mask * res_strides[0] + np.arange(n) * res_strides[1], std::valarray<std::size_t>{1, 1}, std::valarray<std::size_t>{res_strides[0], res_strides[1]})] = 1;
    }
    if (leg_order != py::none()) {
        res = np.transpose(res, get_leg_idcs(leg_order));
    }
    return res;
}

Ptr Mask::_unary_operand(py::function func) {
    /* CHECKME: converted from following python code:
     * # operate on the respective projection
     *         if not self.is_projection:
     *             # OPTIMIZE: how hard is it to deal with inclusion Masks in the backends?
     *             return dagger(dagger(self)._unary_operand(func))
     * data, small_leg = self.backend.mask_unary_operand(self, func)
     *         return Mask(
     *             data,
     *             space_in=self.large_leg,
     *             space_out=small_leg,
     *             is_projection=True,
     *             backend=self.backend,
     *             labels=self.labels,
     *         )
     */
    // operate on the respective projection
    if (!is_projection) {
        // OPTIMIZE: how hard is it to deal with inclusion Masks in the backends?
        return dagger(dagger(self  /* FIXME: standalone self reference */)._unary_operand(func));
    }
    std::make_tuple(data, small_leg) = backend.mask_unary_operand(self  /* FIXME: standalone self reference */, func);
    return Mask(data, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val, py::arg({keyword.key}) = val) /* CHECKME: keywords ['space_in', 'space_out', 'is_projection', 'backend', 'labels'] */;
}

/// Export Mask to hdf5 such that it can be re-imported with from_hdf5
void Mask::save_hdf5(py::object hdf5_saver, py::object h5gr, const std::string & subpath) {
    /* CHECKME: converted from following python code:
     * hdf5_saver.save(self.domain, subpath + 'domain')
     * hdf5_saver.save(self.codomain, subpath + 'codomain')
     * hdf5_saver.save(self.backend, subpath + 'backend')
     * hdf5_saver.save(self.data, subpath + 'data')
     * hdf5_saver.save(self.symmetry, subpath + 'symmetry')
     * h5gr.attrs['dtype'] = self.dtype.name
     * h5gr.attrs['num_legs'] = self.num_legs
     * h5gr.attrs['shape'] = np.array(self.shape, np.intp)
     */
    hdf5_saver.save(domain, subpath + "domain");
    hdf5_saver.save(codomain, subpath + "codomain");
    hdf5_saver.save(backend, subpath + "backend");
    hdf5_saver.save(data, subpath + "data");
    hdf5_saver.save(symmetry, subpath + "symmetry");
    h5gr.attrs["dtype"] = dtype.name;
    h5gr.attrs["num_legs"] = num_legs;
    h5gr.attrs["shape"] = np.array(shape, np.intp);
}

/// Import Mask from hdf5
Ptr Mask::from_hdf5(py::object hdf5_loader, py::object h5gr, const std::string & subpath) {
    /* CHECKME: converted from following python code:
     * obj = cls.__new__(cls)
     * hdf5_loader.memorize_load(h5gr, obj)
     * obj.domain = hdf5_loader.load(subpath + 'domain')
     * obj.codomain = hdf5_loader.load(subpath + 'codomain')
     * obj.symmetry = hdf5_loader.load(subpath + 'symmetry')
     * obj.backend = hdf5_loader.load(subpath + 'backend')
     * obj.data = hdf5_loader.load(subpath + 'data')
     * obj.dtype = hdf5_loader.get_attr(h5gr, 'dtype')
     * obj.num_legs = hdf5_loader.get_attr(h5gr, 'num_legs')
     * obj.shape = hdf5_loader.get_attr(h5gr, 'shape')
     * obj.dtype = hdf5_loader.get_attr(h5gr, 'dtype')
     * obj.num_legs = hdf5_loader.get_attr(h5gr, 'num_legs')
     * obj.shape = hdf5_loader.get_attr(h5gr, 'shape')
     */
    auto /* CHECKME: type? */ obj = cls.__new__(cls);
    hdf5_loader.memorize_load(h5gr, obj);
    obj.domain = hdf5_loader.load(subpath + "domain");
    obj.codomain = hdf5_loader.load(subpath + "codomain");
    obj.symmetry = hdf5_loader.load(subpath + "symmetry");
    obj.backend = hdf5_loader.load(subpath + "backend");
    obj.data = hdf5_loader.load(subpath + "data");
    obj.dtype = hdf5_loader.get_attr(h5gr, "dtype");
    obj.num_legs = hdf5_loader.get_attr(h5gr, "num_legs");
    obj.shape = hdf5_loader.get_attr(h5gr, "shape");
    obj.dtype = hdf5_loader.get_attr(h5gr, "dtype");
    obj.num_legs = hdf5_loader.get_attr(h5gr, "num_legs");
    obj.shape = hdf5_loader.get_attr(h5gr, "shape");
}

const std::vector<Dtype> & Mask::forbidden_dtypes() {
    // FIXME: implement
}

std::string Mask::ascii_diagram_type_name() {
    // FIXME: implement
}

std::string Mask::class_name() {
    // FIXME: implement
}

Tensor::Ptr Mask::dagger() {
    // FIXME: implement
}

py::object Mask::as_py_object() {
    // FIXME: implement
}
