#!/usr/bin/env python3
"""Post-process a pybind11_mkdoc header for cyten.

1. Restore NumPy ``Parameters`` / ``----------`` underlines mangled by mkdoc reflow.
2. Add a banner naming the source include.
3. Guard the shared ``DOC()`` macro preamble so several docstring headers can be
   included in one translation unit later.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# "Parameters ---------- rest" -> "Parameters\n----------\nrest"
_SECTION_RE = re.compile(
    r'^(Parameters|Returns|Raises|See Also|Notes|Warnings|Attributes|Methods)'
    r'[ \t]+(-{3,}|={3,})[ \t]*',
    re.MULTILINE,
)

# Shared DOC()/MKD_* macros only (not the per-file unused-variable pragma).
_PREAMBLE_RE = re.compile(
    r'(#define MKD_EXPAND.*?#define DOC\(\.\.\.\).*?\n)',
    re.DOTALL,
)


def fix_numpy_sections(text: str) -> str:
    return _SECTION_RE.sub(r'\1\n\2\n', text)


def guard_doc_macros(text: str) -> str:
    def repl(m: re.Match[str]) -> str:
        body = m.group(1).rstrip() + '\n'
        return (
            '#ifndef CYTEN_MKDOC_DOC_MACROS\n'
            '#define CYTEN_MKDOC_DOC_MACROS\n'
            f'{body}'
            '#endif /* CYTEN_MKDOC_DOC_MACROS */\n\n'
        )

    new, n = _PREAMBLE_RE.subn(repl, text, count=1)
    if n != 1:
        raise SystemExit('fix_mkdoc_numpy_sections: could not locate DOC() macro preamble')
    return new


def banner(source_rel: str) -> str:
    return f"""\
/*
  Generated by pybind11_mkdoc from include/cyten/{source_rel}.
  Checked into git so builds work without mkdoc/libclang.

  To regenerate (optional; needs pybind11-mkdoc, clangdev, libclang):
    cmake --build <build-dir> --target cyten_mkdoc_docstrings
 */

"""


def process(text: str, source_rel: str) -> str:
    text = re.sub(r'^/\*.*?\*/\s*', '', text, count=1, flags=re.S)
    text = fix_numpy_sections(text.lstrip())
    text = guard_doc_macros(text)
    return banner(source_rel) + text


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('input', type=Path, help='Raw docstrings.h from mkdoc')
    ap.add_argument('-o', '--output', type=Path, required=True, help='Fixed output path')
    ap.add_argument(
        '--source-rel',
        required=True,
        help='Path relative to include/cyten/ (e.g. tensors/ops_algebra.h)',
    )
    args = ap.parse_args()
    text = process(args.input.read_text(encoding='utf-8'), args.source_rel)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding='utf-8')
    return 0


if __name__ == '__main__':
    sys.exit(main())
