#pragma once

#include <cyten/cyten.h>

namespace cyten {

// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_declaration --py-name AbelianBackendData --header-file include/cyten/backends/abelian.h

/// Data stored in a Tensor for :class:`AbelianBackend`.
class AbelianBackendData {
public:
public:
    AbelianBackendData(Dtype dtype, std::string device, list_Block_ blocks, ndarray block_inds, bool is_sorted=false);
    virtual ~AbelianBackendData() = default;
    /// Return the index ``n`` of the block which matches the block_inds.
    BlockBackend::BlockPtr get_block_num(ndarray block_inds);
    /// Get the block at given block indices.
    BlockBackend::BlockPtr get_block(ndarray block_inds);
    TYPEOF_return save_hdf5(TYPEOF_hdf5_saver hdf5_saver, TYPEOF_h5gr h5gr, TYPEOF_subpath subpath);
    TYPEOF_return from_hdf5(TYPEOF_hdf5_loader hdf5_loader, TYPEOF_h5gr h5gr, TYPEOF_subpath subpath);
};

} // namespace cyten
