#include <cyten/tools.h>

#include <format>
#include <pybind11/numpy.h>

namespace cyten {

NotImplemented::NotImplemented(std::string name)
  : std::logic_error(std::format("Not implemented: {}", name)) {};

/// Format elements of an iterable as if it were a plain list.
std::string
format_like_list(py::iterable it)
{
    std::string result = "[";
    bool first = true;
    for (auto&& item : it) {
        if (!first)
            result += ", ";
        result += py::str(item).cast<std::string>();
        first = false;
    }
    result += "]";
    return result;
}

bool
is_iterable(py::object a)
{
    try {
        py::iter(a);
        return true;
    } catch (py::error_already_set& m) {
        // expected error: TypeError if not iterable
        if (!m.matches(PyExc_TypeError))
            throw;
    }
    return false;
}

py::object
to_iterable(py::object a)
{
    if (!py::isinstance<py::str>(a) && is_iterable(a))
        return a;
    py::list result(1);
    result[0] = a;
    return result;
}

int64
to_valid_idx(int64 idx, int64 length)
{
    if (idx < -length || idx >= length)
        throw std::out_of_range("Index " + std::to_string(idx) + " out of bounds for length " +
                                std::to_string(length));
    if (idx < 0)
        idx += length;
    return idx;
}

// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_definition --py-name BigOMonomial --header-file include/cyten/tools.h --src-file src/tools.cpp

BigOMonomial::BigOMonomial(int factors) {
    /* CHECKME: converted from following python code:
     * self.factors = factors
     */
    factors = factors;
}

/// Initialize from a string representation like ``'x^2 y^3'``.
BigOMonomial BigOMonomial::from_str(const std::string & mono) {
    /* CHECKME: converted from following python code:
     *         if isinstance(mono, BigOMonomial):
     *             return mono
     * mono = str(mono).strip()
     * str_factors = mono.split(' ')
     * factors = {}
     *         for f in str_factors:
     *             f = f.split('^')
     *             if len(f) == 1:
     *                 dim = f[0]
     *                 exp = 1
     *             elif len(f) == 2:
     *                 dim = f[0]
     *                 exp = int(f[1])
     *                 assert exp > 0
     *             else:
     *                 raise ValueError(f'Invalid monomial: "{mono}"')
     *             factors[dim] = factors.get(dim, 0) + exp
     * return cls(factors=factors)
     */
    if (isinstance(mono, BigOMonomial)) {
        return mono;
    }
    mono = str(mono).strip();
    auto /* CHECKME: type? */ str_factors = mono.split(" ");
    auto /* CHECKME: type? */ factors = {};
    /* FIXME: for loop:         for f in str_factors:
            f = f.split('^')
            if len(f) == 1:
                dim = f[0]
                exp = 1
            elif len(f) == 2:
                dim = f[0]
                exp = int(f[1])
                assert exp > 0
            else:
                raise ValueError(f'Invalid monomial: "{mono}"')
            factors[dim] = factors.get(dim, 0) + exp */
    return cls(py::arg({keyword.key}) = val) /* CHECKME: keywords ['factors'] */;
}

BigOPolynomial BigOMonomial::operator+(const BigOMonomial & other) {
    /* CHECKME: converted from following python code:
     *         if not isinstance(other, BigOMonomial):
     *             return NotImplemented
     * return BigOPolynomial([self, other])
     */
    if (!(isinstance(other, BigOMonomial))) {
        return NotImplemented;
    }
    return BigOPolynomial({self  /* FIXME: standalone self reference */, other});
}

int BigOMonomial::__hash__() {
    /* CHECKME: converted from following python code:
     * return hash(tuple(*self.factors.items()))
     */
    return hash(tuple(/* FIXME: Starred: *self.factors.items() */));
}

BigOMonomial BigOMonomial::operator*(const BigOMonomial & other) {
    /* CHECKME: converted from following python code:
     *         if not isinstance(other, BigOMonomial):
     *             return NotImplemented
     * factors = self.factors.copy()
     *         for s, e in other.factors.items():
     *             factors[s] = factors.get(s, 0) + e
     * return BigOMonomial(factors)
     */
    if (!(isinstance(other, BigOMonomial))) {
        return NotImplemented;
    }
    auto /* CHECKME: type? */ factors = factors.copy();
    /* FIXME: for loop:         for s, e in other.factors.items():
            factors[s] = factors.get(s, 0) + e */
    return BigOMonomial(factors);
}

str BigOMonomial::__repr__() {
    /* CHECKME: converted from following python code:
     * return f'<{type(self).__name__} {str(self)} >'
     */
    return std::format("<{} {} >", type(self  /* FIXME: standalone self reference */).__name__, str(self  /* FIXME: standalone self reference */));
}

str BigOMonomial::__str__() {
    /* CHECKME: converted from following python code:
     * return ' '.join(f'{dim}^{exp}' for dim, exp in self.factors.items())
     */
    return " ".join(/* FIXME: GeneratorExp: (f'{dim}^{exp}' for dim, exp in self.factors.items()) */);
}

bool BigOMonomial::operator==(const BigOMonomial & other) {
    /* CHECKME: converted from following python code:
     *         if not isinstance(other, BigOMonomial):
     *             return NotImplemented
     *         for s, e in self.factors.items():
     *             if other.factors.get(s, 0) != e:
     *                 return False
     *         for s, e in other.factors.items():
     *             if self.factors.get(s, 0) != e:
     *                 return False
     * return True
     */
    if (!(isinstance(other, BigOMonomial))) {
        return NotImplemented;
    }
    /* FIXME: for loop:         for s, e in self.factors.items():
            if other.factors.get(s, 0) != e:
                return False */
    /* FIXME: for loop:         for s, e in other.factors.items():
            if self.factors.get(s, 0) != e:
                return False */
    return true;
}

/// If the given monomial is negligible compared to `others`, s.t. ``O(self + x) = O(x)``.
bool BigOMonomial::is_negligible(const int & others, int relations) {
    /* CHECKME: converted from following python code:
     *         if relations is not None:
     *             raise NotImplementedError
     *         for o in others:
     *             if all(n <= o.factors.get(x, 0) for x, n in self.factors.items()):
     *                 # can safely ignore any keys in o.factors that are not in self.factors
     *                 return True
     * return False
     */
    if (relations != py::none()) {
        throw std::logic_error("");
    }
    /* FIXME: for loop:         for o in others:
            if all(n <= o.factors.get(x, 0) for x, n in self.factors.items()):
                # can safely ignore any keys in o.factors that are not in self.factors
                return True */
    return false;
}

bool BigOMonomial::operator!=(const BigOMonomial & other) {
    // FIXME: implement
}

std::size_t BigOMonomial::hash() {
    // FIXME: implement
}

std::string BigOMonomial::str() {
    // FIXME: implement
}

std::string BigOMonomial::repr() {
    // FIXME: implement
}
// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_cpp_definition --py-name BigOPolynomial --header-file include/cyten/tools.h --src-file src/tools.cpp

BigOPolynomial::BigOPolynomial(int terms) {
    /* CHECKME: converted from following python code:
     *         if terms is None:
     *             terms = []
     * self.terms = self.simplify_terms(terms)
     */
    if (terms == py::none()) {
        terms = {} /* FIXME: empty list */;
    }
    terms = simplify_terms(terms);
}

/// Simplify a list of terms by dropping negligible terms.
int BigOPolynomial::simplify_terms(const int & terms, int relations) {
    /* CHECKME: converted from following python code:
     * non_negligible = []
     *         for t in terms:
     *             if not t.is_negligible(*non_negligible, relations=relations):
     *                 non_negligible.append(t)
     * return non_negligible
     */
    auto /* CHECKME: type? */ non_negligible = {} /* FIXME: empty list */;
    /* FIXME: for loop:         for t in terms:
            if not t.is_negligible(*non_negligible, relations=relations):
                non_negligible.append(t) */
    return non_negligible;
}

/// Initialize from a string representation like ``'x^2 y^3 + x^4'``.
BigOPolynomial BigOPolynomial::from_str(const std::string & poly) {
    /* CHECKME: converted from following python code:
     *         if isinstance(poly, BigOPolynomial):
     *             return poly
     *         if isinstance(poly, BigOMonomial):
     *             return cls(terms=[poly])
     * terms = poly.split('+')
     * return cls(terms=[BigOMonomial.from_str(t.strip()) for t in terms])
     */
    if (isinstance(poly, BigOPolynomial)) {
        return poly;
    }
    if (isinstance(poly, BigOMonomial)) {
        return cls(py::arg({keyword.key}) = val) /* CHECKME: keywords ['terms'] */;
    }
    auto /* CHECKME: type? */ terms = poly.split("+");
    return cls(py::arg({keyword.key}) = val) /* CHECKME: keywords ['terms'] */;
}

str BigOPolynomial::__repr__() {
    /* CHECKME: converted from following python code:
     * return f'<{type(self).__name__} {str(self)} >'
     */
    return std::format("<{} {} >", type(self  /* FIXME: standalone self reference */).__name__, str(self  /* FIXME: standalone self reference */));
}

str BigOPolynomial::__str__() {
    /* CHECKME: converted from following python code:
     * return ' + '.join(str(t) for t in self.terms)
     */
    return " + ".join(/* FIXME: GeneratorExp: (str(t) for t in self.terms) */);
}

BigOPolynomial BigOPolynomial::operator+(const std::string & other) {
    /* CHECKME: converted from following python code:
     *         if isinstance(other, str):
     *             other = BigOPolynomial.from_str(other)
     *         if isinstance(other, BigOMonomial):
     *             other = BigOPolynomial([other])
     *         if not isinstance(other, BigOPolynomial):
     *             return NotImplemented
     * return BigOPolynomial([*self.terms, *other.terms])
     */
    if (isinstance(other, str)) {
        other = BigOPolynomial.from_str(other);
    }
    if (isinstance(other, BigOMonomial)) {
        other = BigOPolynomial({other});
    }
    if (!(isinstance(other, BigOPolynomial))) {
        return NotImplemented;
    }
    return BigOPolynomial({/* FIXME: Starred: *self.terms */, /* FIXME: Starred: *other.terms */});
}

bool BigOPolynomial::operator==(const BigOMonomial & other) {
    /* CHECKME: converted from following python code:
     *         if isinstance(other, BigOMonomial):
     *             if len(self.terms) == 1:
     *                 return self.terms[0] == other
     *             return False
     *         if not isinstance(other, BigOPolynomial):
     *             return NotImplemented
     *         for t in self.terms:
     *             # OPTIMIZE could impose a canonical order on terms, to save one loop...
     *             if not any(t == t2 for t2 in other.terms):
     *                 return False
     *         for t2 in other.terms:
     *             if not any(t == t2 for t in other.terms):
     *                 return False
     * return True
     */
    if (isinstance(other, BigOMonomial)) {
        if (len(terms) == 1) {
            return terms[0] == other;
        }
        return false;
    }
    if (!(isinstance(other, BigOPolynomial))) {
        return NotImplemented;
    }
    /* FIXME: for loop:         for t in self.terms:
            # OPTIMIZE could impose a canonical order on terms, to save one loop...
            if not any(t == t2 for t2 in other.terms):
                return False */
    /* FIXME: for loop:         for t2 in other.terms:
            if not any(t == t2 for t in other.terms):
                return False */
    return true;
}

int BigOPolynomial::__hash__() {
    /* CHECKME: converted from following python code:
     * return hash(tuple(self.terms))
     */
    return hash(tuple(terms));
}

BigOPolynomial BigOPolynomial::operator*(const std::string & other) {
    /* CHECKME: converted from following python code:
     *         if isinstance(other, str):
     *             other = BigOPolynomial.from_str(other)
     *         if isinstance(other, BigOMonomial):
     *             other = BigOPolynomial([other])
     *         if not isinstance(other, BigOPolynomial):
     *             return NotImplemented
     * terms = [m1 * m2 for m1, m2 in itertools.product(self.terms, other.terms)]
     * return BigOPolynomial(terms)
     */
    if (isinstance(other, str)) {
        other = BigOPolynomial.from_str(other);
    }
    if (isinstance(other, BigOMonomial)) {
        other = BigOPolynomial({other});
    }
    if (!(isinstance(other, BigOPolynomial))) {
        return NotImplemented;
    }
    auto /* CHECKME: type? */ terms = /* FIXME: ListComp: [m1 * m2 for m1, m2 in itertools.product(self.terms, other.terms)] */;
    return BigOPolynomial(terms);
}

/// Product of multiply symmetries
BigOPolynomial BigOPolynomial::prod(const int & others) {
    /* CHECKME: converted from following python code:
     *         if len(others) == 0:
     *             return self
     * first, *more = others
     * return (self * first).prod(*more)
     */
    if (len(others) == 0) {
        return self  /* FIXME: standalone self reference */;
    }
    std::make_tuple(first, /* FIXME: Starred: *more */) = others;
    return self  /* FIXME: standalone self reference */ * first.prod(/* FIXME: Starred: *more */);
}

std::string BigOPolynomial::str() {
    // FIXME: implement
}

std::string BigOPolynomial::repr() {
    // FIXME: implement
}

bool BigOPolynomial::operator!=(const BigOMonomial & other) {
    // FIXME: implement
}

std::size_t BigOPolynomial::hash() {
    // FIXME: implement
}

} // namespace cyten
