#include "py_cyten_pybind11.h"

namespace cyten {

} // namespace cyten
// CHECKME: the following was generated by .cursor/skills/pybind11-codegen/pybind11_codegen.py gen_pyb11_binding --py-name Leg --header-file include/cyten/symmetries/spaces.h --binding-file pybind/symmetries/py_spaces.cpp

py::class_<Leg, py::smart_holder> leg(m, "Leg");
leg.doc() = R"pydoc(
Common base class for a single leg of a tensor.

A single leg on a tensor can either be an :class:`ElementarySpace` or, e.g. as the result
of combining legs, a :class:`LegPipe`.

Attributes
----------
symmetry : Symmetry
    The symmetry associated with this leg.
dim : int or float
    The (quantum-)dimension of this leg.
    Is integer if ``symmetry.can_be_dropped``, otherwise may be float.
is_dual : bool
    A boolean flag that changes when the :attr:`dual` is taken. May or may not have additional
    meaning and implications, depending on the concrete subclass of :class:`Leg`.
)pydoc";

leg // init and attributes
    .def(py::init<Symmetry::Ptr,int64,bool,std::optional<std::vector<int64>>>())
    .def_property_readonly("dual", &Leg::_get_dual)
    .def_property_readonly("is_trivial", &Leg::_get_is_trivial)
    .def_property("basis_perm", &Leg::_get_basis_perm, &Leg::_set_basis_perm
    .def_property_readonly("flat_legs", &Leg::_get_flat_legs)
    .def_property_readonly("flat_spaces", &Leg::_get_flat_spaces)
    .def_property("inverse_basis_perm", &Leg::_get_inverse_basis_perm, &Leg::_set_inverse_basis_perm
    .def_property_readonly("num_flat_legs", &Leg::_get_num_flat_legs)
    .def_property_readonly("ascii_arrow", &Leg::_get_ascii_arrow)
; // completed leg attributes

leg //  methods
    .def("test_sanity", &Leg::test_sanity,
        "Perform sanity checks."
        )
    .def("as_Space", &Leg::as_Space,
        "Convert to (an appropriate subclass of) :class:`Space`."
        )
    .def("as_ElementarySpace", &Leg::as_ElementarySpace,
        py::arg("is_dual") = false,
        "Convert to an isomorphic :class:`ElementarySpace`"
        )
    .def("dual", &Leg::dual,
        "The dual leg, that is obtained when bending this leg."
        )
    .def("is_trivial", &Leg::is_trivial
        )
    .def("basis_perm", &Leg::basis_perm,
        py::arg("basis_perm")
        )
    .def("flat_legs", &Leg::flat_legs,
        R"pydoc(
        Flatten until there are no more pipes.
        
        See Also
        --------
        flat_spaces : Keeps :class:`AbelianLegPipes` nested.
        )pydoc"
        )
    .def("flat_spaces", &Leg::flat_spaces,
        R"pydoc(
        Flatten until we get spaces.
        
        See Also
        --------
        flat_legs : Also flattens :class:`AbelianLegPipes`.
        )pydoc"
        )
    .def("inverse_basis_perm", &Leg::set_inverse_basis_perm,
        py::arg("inverse_basis_perm")
        )
    .def("num_flat_legs", &Leg::num_flat_legs,
        "The number of :attr:`flat_legs`."
        )
    .def("_flat_leg_permutation", &Leg::_flat_leg_permutation,
        py::arg("offset") = 0,
        "Leg permutation such that combining legs would be in C style."
        )
    .def("ascii_arrow", &Leg::ascii_arrow,
        R"pydoc(
        A single character arrow, for use in tensor diagrams
        
        Indicates (a) if the leg is a pipe and (b) for ElementarySpaces, the duality
        )pydoc"
        )
    .def("__eq__", &Leg::operator==,
        py::arg("other")
        )
    .def("apply_basis_perm", &Leg::apply_basis_perm,
        py::arg("arr"),
        py::arg("axis") = 0,
        py::arg("inverse") = false,
        py::arg("pre_compose") = false,
        R"pydoc(
        Apply the basis_perm, i.e. form ``arr[self.basis_perm]``.
        
        This is the preferred method of accessing the permutation, since we may skip applying
        trivial permutations.
        
        Parameters
        ----------
        arr : numpy array
            The data to act on.
        axis : int
            Which axis of ``arr`` to act on. We use ``numpy.take(arr, perm, axis)``.
        inverse : bool
            If we should apply the inverse permutation :attr:`inverse_basis_perm` instead.
        pre_compose : bool
            If we should pre-compose instead, i.e. form ``basis_perm[arr]``.
            Note that in that case, `axis` is ignored.
        )pydoc"
        )
    .def("set_basis_perm", &Leg::set_basis_perm,
        py::arg("basis_perm") = UNSPECIFIED,
        py::arg("inverse_basis_perm") = UNSPECIFIED,
        "Common setter for :attr:`basis_perm` and :attr:`inverse_basis_perm`."
        )
; // completed leg methods
